const attractionsPage2 = [
  {
    id: 26,
    name: "Canyonlands National Park",
    slug: "canyonlands-ut",
    state: "Utah",
    region: "Southwest",
    category: "National Park",
    description: "Canyonlands is Utah's largest national park, where the Colorado and Green rivers carve the high desert plateau into three distinct districts of dramatic canyons, mesas, and buttes. The Island in the Sky mesa sits 1,000 feet above the surrounding terrain, offering some of the most expansive vistas in the American Southwest. Mesa Arch frames a sunrise that photographers travel from around the world to capture.",
    rating: 4.8,
    reviews: 18640,
    fee: "$30/vehicle",
    bestTime: "March–May, Sept–Oct",
    duration: "2–3 days",
    activities: ["Hiking", "4WD Off-Roading", "Photography", "Stargazing", "Camping"],
    difficulty: "Moderate to Strenuous",
    accessibility: true,
    image: "https://picsum.photos/seed/canyonlands-ut/800/450",
    tags: ["Canyons", "Mesa", "Colorado River", "Dark Sky"]
  },
  {
    id: 27,
    name: "Capitol Reef National Park",
    slug: "capitol-reef-ut",
    state: "Utah",
    region: "Southwest",
    category: "National Park",
    description: "Capitol Reef is one of Utah's least-visited but most rewarding parks, centered on the Waterpocket Fold—a 100-mile-long buckle in the Earth's crust exposing layers of brilliantly colored rock. The historic Fruita pioneer settlement still produces fruit from orchards visitors can freely pick in season. Narrow slot canyons like Grand Wash and Capitol Gorge offer intimate desert hiking experiences.",
    rating: 4.7,
    reviews: 12380,
    fee: "$20/vehicle",
    bestTime: "April–October",
    duration: "1–2 days",
    activities: ["Hiking", "Scenic Driving", "Fruit Picking", "Photography", "Camping"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "https://picsum.photos/seed/capitol-reef-ut/800/450",
    tags: ["Geology", "Slot Canyons", "Pioneer History", "Orchard"]
  },
  {
    id: 28,
    name: "Mesa Verde National Park",
    slug: "mesa-verde-cliff",
    state: "Colorado",
    region: "Rocky Mountains",
    category: "National Park",
    description: "Mesa Verde preserves over 5,000 archaeological sites, including the awe-inspiring Cliff Palace—the largest cliff dwelling in North America, built by the Ancestral Pueblo people around 1200 CE. Perched beneath overhanging sandstone alcoves, these 600-room stone villages reveal a sophisticated civilization that flourished and mysteriously departed within a single century. Ranger-led tours descend into kivas and ladder-accessed dwellings for a visceral connection to the ancient past.",
    rating: 4.8,
    reviews: 21450,
    fee: "$20/vehicle",
    bestTime: "May–October",
    duration: "1–2 days",
    activities: ["Guided Tours", "Hiking", "Museum Visit", "Photography", "Scenic Driving"],
    difficulty: "Moderate",
    accessibility: true,
    image: "https://picsum.photos/seed/mesa-verde-cliff/800/450",
    tags: ["Cliff Dwellings", "Ancestral Pueblo", "Archaeology", "UNESCO"]
  },
  {
    id: 29,
    name: "White Sands National Park",
    slug: "white-sands-nm",
    state: "New Mexico",
    region: "Southwest",
    category: "National Park",
    description: "White Sands is the world's largest gypsum dunefield, covering 275 square miles of brilliant white sand that never heats up the way quartz sand does, making it comfortable to walk barefoot even in summer. The dunes shift constantly, swallowing plants and recreating themselves in mesmerizing wave-like formations. Sunset turns the entire landscape soft shades of pink and lavender in one of the most surreal scenes in North America.",
    rating: 4.8,
    reviews: 16920,
    fee: "$25/vehicle",
    bestTime: "October–April",
    duration: "Half day–1 day",
    activities: ["Sand Sledding", "Hiking", "Photography", "Sunset Viewing", "Stargazing"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/white-sands-nm/800/450",
    tags: ["Sand Dunes", "Gypsum", "White Sand", "Surreal Landscape"]
  },
  {
    id: 30,
    name: "Guadalupe Mountains National Park",
    slug: "guadalupe-mountains-tx",
    state: "Texas",
    region: "Southwest",
    category: "National Park",
    description: "The Guadalupe Mountains contain the highest peak in Texas—Guadalupe Peak at 8,751 feet—and represent one of the world's finest examples of an ancient marine fossil reef, the Permian Reef, once submerged beneath a shallow tropical sea. Dramatic El Capitan cliff face dominates the skyline and served as a landmark for the Butterfield Overland Mail route. The park's remote character and brilliant fall foliage from maples and oaks makes it a hidden gem of the Chihuahuan Desert.",
    rating: 4.6,
    reviews: 7840,
    fee: "$10/person",
    bestTime: "October–April",
    duration: "1–2 days",
    activities: ["Hiking", "Backpacking", "Fossil Viewing", "Photography", "Stargazing"],
    difficulty: "Moderate to Strenuous",
    accessibility: false,
    image: "https://picsum.photos/seed/guadalupe-mountains-tx/800/450",
    tags: ["Fossil Reef", "Highest Point Texas", "Desert", "Remote"]
  },
  {
    id: 31,
    name: "Big Bend National Park",
    slug: "big-bend-tx",
    state: "Texas",
    region: "Southwest",
    category: "National Park",
    description: "Big Bend occupies a remote bend of the Rio Grande along the U.S.-Mexico border, encompassing the rugged Chisos Mountains, vast Chihuahuan Desert, and stunning river canyons including Santa Elena Canyon with its 1,500-foot limestone walls. It is one of the least-visited national parks due to its remoteness, yet rewards those who make the journey with world-class stargazing, hot springs along the river, and some 450 species of birds. The solitude here is extraordinary.",
    rating: 4.8,
    reviews: 13270,
    fee: "$30/vehicle",
    bestTime: "October–April",
    duration: "3–5 days",
    activities: ["Hiking", "Backpacking", "River Rafting", "Stargazing", "Hot Springs"],
    difficulty: "Moderate to Strenuous",
    accessibility: true,
    image: "https://picsum.photos/seed/big-bend-tx/800/450",
    tags: ["Remote", "Desert", "Rio Grande", "Dark Sky"]
  },
  {
    id: 32,
    name: "Carlsbad Caverns National Park",
    slug: "carlsbad-caverns-nm",
    state: "New Mexico",
    region: "Southwest",
    category: "National Park",
    description: "Carlsbad Caverns contains one of the largest cave chambers in North America—the Big Room, a single cave chamber covering 8.2 acres with a ceiling 255 feet high. Ancient cave formations called speleothems—stalactites, stalagmites, and delicate cave pearls—create an underground wonderland of breathtaking scale. Each evening from May through October, hundreds of thousands of Brazilian free-tailed bats spiral out of the cave entrance in a spectacular vortex at dusk.",
    rating: 4.8,
    reviews: 19530,
    fee: "$15/person",
    bestTime: "May–October",
    duration: "Half day–1 day",
    activities: ["Cave Tours", "Bat Flight Program", "Hiking", "Photography", "Junior Ranger"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "https://picsum.photos/seed/carlsbad-caverns-nm/800/450",
    tags: ["Caves", "Bats", "Stalactites", "Underground"]
  },
  {
    id: 33,
    name: "Petrified Forest National Park",
    slug: "petrified-forest-az",
    state: "Arizona",
    region: "Southwest",
    category: "National Park",
    description: "Petrified Forest preserves one of the world's largest and most colorful concentrations of petrified wood, where 225-million-year-old logs have been replaced atom by atom with quartz crystals creating stunning rainbow-hued stone. The park also protects a portion of the Painted Desert, whose badlands glow in vivid bands of red, orange, and lavender. Ancient petroglyphs and pueblo ruins scattered throughout reveal 13,000 years of human habitation.",
    rating: 4.6,
    reviews: 11280,
    fee: "$25/vehicle",
    bestTime: "March–October",
    duration: "Half day–1 day",
    activities: ["Scenic Driving", "Hiking", "Photography", "Fossil Viewing", "Petroglyph Viewing"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/petrified-forest-az/800/450",
    tags: ["Petrified Wood", "Painted Desert", "Fossils", "Geology"]
  },
  {
    id: 34,
    name: "Pinnacles National Park",
    slug: "pinnacles-ca",
    state: "California",
    region: "Pacific West",
    category: "National Park",
    description: "Pinnacles is the remnant of an ancient volcano that moved 200 miles north along the San Andreas Fault, leaving behind dramatic spires and rock formations rising above chaparral-covered hills east of the Salinas Valley. Its talus caves—formed by giant boulders wedged into narrow canyons—are among the few roosting sites for the critically endangered California condor, which visitors can watch soaring overhead. Spring wildflowers carpet the hillsides in vivid color.",
    rating: 4.6,
    reviews: 9870,
    fee: "$30/vehicle",
    bestTime: "February–May, Sept–Nov",
    duration: "1 day",
    activities: ["Hiking", "Rock Climbing", "Cave Exploration", "Condor Watching", "Stargazing"],
    difficulty: "Moderate",
    accessibility: true,
    image: "https://picsum.photos/seed/pinnacles-ca/800/450",
    tags: ["Condors", "Rock Formations", "Caves", "Volcanic"]
  },
  {
    id: 35,
    name: "Channel Islands National Park",
    slug: "channel-islands-ca",
    state: "California",
    region: "Pacific West",
    category: "National Park",
    description: "Five islands off the Southern California coast—often called the 'North American Galápagos'—harbor species found nowhere else on Earth, including the island fox and island scrub-jay. Giant kelp forests make Channel Islands one of the world's premier scuba diving and snorkeling destinations. Sea caves, elephant seal rookeries, and unobstructed views of both the Pacific horizon and the California mainland create an exceptional sense of wilderness just miles from Los Angeles.",
    rating: 4.7,
    reviews: 10540,
    fee: "$25/person (boat required)",
    bestTime: "April–October",
    duration: "1–3 days",
    activities: ["Kayaking", "Snorkeling", "Scuba Diving", "Hiking", "Wildlife Watching"],
    difficulty: "Moderate",
    accessibility: false,
    image: "https://picsum.photos/seed/channel-islands-ca/800/450",
    tags: ["Islands", "Marine Life", "Kelp Forest", "Endemic Species"]
  },
  {
    id: 36,
    name: "Redwood National and State Parks",
    slug: "redwood-np-ca",
    state: "California",
    region: "Pacific West",
    category: "National Park",
    description: "Home to the tallest trees on Earth—coast redwoods that soar above 350 feet and live for over 2,000 years—Redwood's ancient groves create a cathedral atmosphere of filtered green light and hushed awe. The park preserves nearly half of California's remaining old-growth redwood forests along a fog-shrouded stretch of the Northern California coast. Elk Prairie hosts large herds of Roosevelt elk grazing beneath towering trees in one of the most iconic wildlife scenes in North America.",
    rating: 4.8,
    reviews: 17340,
    fee: "Free",
    bestTime: "May–September",
    duration: "1–3 days",
    activities: ["Hiking", "Wildlife Watching", "Photography", "Scenic Driving", "Kayaking"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "https://picsum.photos/seed/redwood-np-ca/800/450",
    tags: ["Tallest Trees", "Old Growth", "Elk", "UNESCO"]
  },
  {
    id: 37,
    name: "Lassen Volcanic National Park",
    slug: "lassen-volcanic-ca",
    state: "California",
    region: "Pacific West",
    category: "National Park",
    description: "Lassen Peak is one of the largest plug-dome volcanoes in the world and the southernmost active peak of the Cascade Range, having last erupted between 1914 and 1917. The park is a bubbling, steaming volcanic laboratory featuring boiling mud pots, fumaroles, and sulfurous hot springs at Bumpass Hell—the largest hydrothermal area in the park. Pristine alpine lakes, conifer forests, and wildflower meadows surround the geothermal features in striking contrast.",
    rating: 4.7,
    reviews: 11920,
    fee: "$30/vehicle",
    bestTime: "July–September",
    duration: "1–2 days",
    activities: ["Hiking", "Hydrothermal Viewing", "Fishing", "Camping", "Snowshoeing"],
    difficulty: "Easy to Strenuous",
    accessibility: true,
    image: "https://picsum.photos/seed/lassen-volcanic-ca/800/450",
    tags: ["Volcano", "Hydrothermal", "Mud Pots", "Cascade Range"]
  },
  {
    id: 38,
    name: "North Cascades National Park",
    slug: "north-cascades-wa",
    state: "Washington",
    region: "Pacific West",
    category: "National Park",
    description: "Known as the 'American Alps,' North Cascades contains more glaciers than any other area in the contiguous United States outside of Alaska—over 300—draped across jagged peaks that rise steeply from deep emerald valleys. The park is among the least visited in the lower 48, making its wilderness feel genuinely untamed. Ross Lake, Diablo Lake's turquoise glacial water, and the North Cascades Highway offer spectacular scenery for those who make the journey.",
    rating: 4.7,
    reviews: 8960,
    fee: "$30/vehicle",
    bestTime: "July–September",
    duration: "2–4 days",
    activities: ["Hiking", "Backpacking", "Kayaking", "Photography", "Camping"],
    difficulty: "Strenuous",
    accessibility: false,
    image: "https://picsum.photos/seed/north-cascades-wa/800/450",
    tags: ["Glaciers", "Alpine", "Remote", "Turquoise Lakes"]
  },
  {
    id: 39,
    name: "Kenai Fjords National Park",
    slug: "kenai-fjords-ak",
    state: "Alaska",
    region: "Alaska",
    category: "National Park",
    description: "Kenai Fjords showcases the raw, dramatic meeting of land and sea along Alaska's Kenai Peninsula, where massive glaciers calve thunderously into the Pacific Ocean and fjords cut deep into a rugged coastline. The Harding Icefield—one of the largest icefields in the U.S.—feeds over 40 glaciers, and day cruises reveal abundant wildlife: orcas, humpback whales, sea otters, puffins, and Steller sea lions. Exit Glacier is the only part of the park accessible by road and offers a moving walk through glacier retreat history.",
    rating: 4.8,
    reviews: 12640,
    fee: "Free (boat tours extra)",
    bestTime: "May–September",
    duration: "1–3 days",
    activities: ["Boat Tours", "Glacier Viewing", "Hiking", "Wildlife Watching", "Kayaking"],
    difficulty: "Easy to Strenuous",
    accessibility: true,
    image: "https://picsum.photos/seed/kenai-fjords-ak/800/450",
    tags: ["Glaciers", "Fjords", "Marine Wildlife", "Icefield"]
  },
  {
    id: 40,
    name: "Gates of the Arctic National Park",
    slug: "gates-of-the-arctic-ak",
    state: "Alaska",
    region: "Alaska",
    category: "National Park",
    description: "Entirely above the Arctic Circle, Gates of the Arctic is the northernmost and one of the wildest national parks in the United States—with no roads, no trails, and no services. Named by explorer Robert Marshall for two peaks he called the 'gates' to the Arctic wilderness, the park preserves six wild rivers, the Brooks Range peaks, and one of North America's great caribou migrations. Only the most self-sufficient adventurers venture here, rewarded with a profound and absolute wilderness experience.",
    rating: 4.8,
    reviews: 3210,
    fee: "Free",
    bestTime: "June–August",
    duration: "5–10 days",
    activities: ["Backpacking", "River Float Trips", "Wildlife Watching", "Fishing", "Photography"],
    difficulty: "Strenuous",
    accessibility: false,
    image: "https://picsum.photos/seed/gates-arctic-ak/800/450",
    tags: ["Arctic", "Wilderness", "No Trails", "Caribou Migration"]
  },
  {
    id: 41,
    name: "Biscayne National Park",
    slug: "biscayne-np-fl",
    state: "Florida",
    region: "Southeast",
    category: "National Park",
    description: "Biscayne is 95% water—a remarkable underwater park protecting the northernmost Florida Keys, a living coral reef, and Biscayne Bay just south of Miami. The park's clear shallow waters teem with tropical fish, sea turtles, manatees, and colorful coral formations easily explored by snorkel or glass-bottom boat. Maritime heritage includes shipwrecks from the 1870s to the 1960s that now serve as artificial reefs, and the Stiltsvillehistoric district features wooden houses built over the bay.",
    rating: 4.6,
    reviews: 9430,
    fee: "Free (boat tours extra)",
    bestTime: "December–May",
    duration: "1–2 days",
    activities: ["Snorkeling", "Scuba Diving", "Kayaking", "Glass-Bottom Boat Tours", "Birdwatching"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/biscayne-np-fl/800/450",
    tags: ["Coral Reef", "Underwater", "Florida Keys", "Marine Life"]
  },
  {
    id: 42,
    name: "Dry Tortugas National Park",
    slug: "dry-tortugas-fl",
    state: "Florida",
    region: "Southeast",
    category: "National Park",
    description: "Accessible only by ferry or seaplane 70 miles west of Key West, Dry Tortugas is one of the most remote national parks in the country—and one of the most magical. The hexagonal Fort Jefferson, a 19th-century military fort with 16 million bricks surrounded by electric-blue Caribbean water, anchors an archipelago of seven small islands. The park is renowned for world-class snorkeling around pristine reefs, massive hawksbill turtle nesting sites, and a legendary spring bird migration stopover.",
    rating: 4.9,
    reviews: 14870,
    fee: "$15/person",
    bestTime: "January–June",
    duration: "1–2 days",
    activities: ["Snorkeling", "Scuba Diving", "Camping", "Birdwatching", "Historic Fort Tour"],
    difficulty: "Easy",
    accessibility: false,
    image: "https://picsum.photos/seed/dry-tortugas-fl/800/450",
    tags: ["Remote", "Coral Reef", "Fort Jefferson", "Sea Turtles"]
  },
  {
    id: 43,
    name: "Congaree National Park",
    slug: "congaree-np-sc",
    state: "South Carolina",
    region: "Southeast",
    category: "National Park",
    description: "Congaree protects the largest intact expanse of old-growth bottomland hardwood forest in the United States, sheltering trees of record-breaking height—a phenomenon created by the extremely fertile floodplain soils of the Congaree and Wateree rivers. The park's boardwalk trail winds through a primeval landscape of ancient cypress and tupelo trees rising from dark floodwaters. Each spring, Congaree hosts one of the world's few synchronized firefly displays, where thousands of fireflies flash in unison across the forest.",
    rating: 4.7,
    reviews: 10620,
    fee: "Free",
    bestTime: "March–May, Oct–Nov",
    duration: "Half day–1 day",
    activities: ["Hiking", "Canoe Trail", "Kayaking", "Birdwatching", "Firefly Viewing"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/congaree-np-sc/800/450",
    tags: ["Old-Growth Forest", "Cypress Trees", "Fireflies", "Floodplain"]
  },
  {
    id: 44,
    name: "New River Gorge National Park",
    slug: "new-river-gorge-wv",
    state: "West Virginia",
    region: "Southeast",
    category: "National Park",
    description: "America's newest national park, designated in 2020, protects the stunning gorge carved by the ancient New River—one of the oldest rivers in the world—through the Appalachian Mountains of West Virginia. The dramatic New River Gorge Bridge, the longest single-arch steel bridge in the Western Hemisphere, spans 876 feet above the gorge and draws BASE jumpers on Bridge Day each October. World-class whitewater rafting through Class V rapids and exceptional rock climbing make this an adventure destination unlike any other in the East.",
    rating: 4.7,
    reviews: 15830,
    fee: "Free",
    bestTime: "April–October",
    duration: "1–3 days",
    activities: ["Whitewater Rafting", "Rock Climbing", "Hiking", "Mountain Biking", "Photography"],
    difficulty: "Moderate to Strenuous",
    accessibility: true,
    image: "https://picsum.photos/seed/new-river-gorge-wv/800/450",
    tags: ["Gorge", "Whitewater", "Steel Bridge", "Rock Climbing"]
  },
  {
    id: 45,
    name: "Cuyahoga Valley National Park",
    slug: "cuyahoga-valley-oh",
    state: "Ohio",
    region: "Great Plains",
    category: "National Park",
    description: "Nestled between Cleveland and Akron, Cuyahoga Valley is a surprising green sanctuary along the Cuyahoga River that tells the story of American industrial history and ecological recovery. The Cuyahoga—famously a river so polluted it caught fire in 1969, helping to spark the environmental movement—now runs clear through restored forests and wetlands. The Towpath Trail follows a historic canal route, and the Cuyahoga Valley Scenic Railroad offers leisurely journeys past covered bridges, waterfalls, and wildlife.",
    rating: 4.6,
    reviews: 22480,
    fee: "Free",
    bestTime: "April–November",
    duration: "1–2 days",
    activities: ["Hiking", "Cycling", "Scenic Railroad", "Birdwatching", "Waterfall Viewing"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "https://picsum.photos/seed/cuyahoga-valley-oh/800/450",
    tags: ["Canal History", "River", "Scenic Railroad", "Fall Foliage"]
  },
  {
    id: 46,
    name: "Isle Royale National Park",
    slug: "isle-royale-mi",
    state: "Michigan",
    region: "Great Plains",
    category: "National Park",
    description: "Isle Royale is an island wilderness in Lake Superior, accessible only by ferry or floatplane, offering one of the most pristine backcountry experiences in the eastern United States. The park is famous for its long-running wolf and moose predator-prey study—the longest continuous ecological study of its kind in the world. No roads cross the interior wilderness, and the park closes entirely in winter, preserving an authentically remote experience beneath skies dark enough to show the Milky Way in stunning detail.",
    rating: 4.8,
    reviews: 6540,
    fee: "$7/person/day",
    bestTime: "June–September",
    duration: "3–7 days",
    activities: ["Backpacking", "Kayaking", "Scuba Diving", "Fishing", "Wildlife Watching"],
    difficulty: "Strenuous",
    accessibility: false,
    image: "https://picsum.photos/seed/isle-royale-mi/800/450",
    tags: ["Island Wilderness", "Wolves", "Moose", "Remote"]
  },
  {
    id: 47,
    name: "Voyageurs National Park",
    slug: "voyageurs-np-mn",
    state: "Minnesota",
    region: "Great Plains",
    category: "National Park",
    description: "Voyageurs is a water-based park on the border of Minnesota and Canada, where the only way to explore the heart of the park is by boat—canoe, kayak, houseboat, or motorcraft. The park sits on the Canadian Shield, some of the oldest exposed rock on Earth, and its chain of interconnected lakes and waterways follow the historic route of French-Canadian fur traders. Summer brings bald eagles, loons, otters, and exceptional fishing; winter transforms the park into a snowmobile and ice-fishing destination with the Northern Lights frequently visible overhead.",
    rating: 4.7,
    reviews: 8320,
    fee: "Free",
    bestTime: "June–September",
    duration: "2–5 days",
    activities: ["Houseboating", "Kayaking", "Fishing", "Wildlife Watching", "Northern Lights Viewing"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "https://picsum.photos/seed/voyageurs-np-mn/800/450",
    tags: ["Water Park", "Boating", "Northern Lights", "Boundary Waters"]
  },
  {
    id: 48,
    name: "Theodore Roosevelt National Park",
    slug: "theodore-roosevelt-nd",
    state: "North Dakota",
    region: "Great Plains",
    category: "National Park",
    description: "Theodore Roosevelt National Park honors the President who credited the North Dakota Badlands with inspiring his conservation ethic, protecting the rugged painted badlands along the Little Missouri River where he ranched in the 1880s. Wild horses and bison herds roam freely across the colorful eroded buttes and prairie, while elk, pronghorn, and prairie dog towns add to the abundant wildlife. The park's two units—North and South—offer solitude and scenery that feel far removed from civilization.",
    rating: 4.7,
    reviews: 10890,
    fee: "$30/vehicle",
    bestTime: "May–September",
    duration: "1–2 days",
    activities: ["Scenic Driving", "Hiking", "Wildlife Watching", "Photography", "Horseback Riding"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "https://picsum.photos/seed/theodore-roosevelt-nd/800/450",
    tags: ["Badlands", "Wild Horses", "Bison", "Prairie"]
  },
  {
    id: 49,
    name: "Wind Cave National Park",
    slug: "wind-cave-sd",
    state: "South Dakota",
    region: "Great Plains",
    category: "National Park",
    description: "Wind Cave is one of the longest and most complex caves in the world, famous for rare 'boxwork' cave formations—thin calcite fins resembling a honeycomb that cover 95% of all known boxwork on Earth. The cave breathes audibly through its natural entrance as barometric pressure shifts outside, which is how the Lakota people and early explorers first discovered it. Above ground, one of the nation's first wildlife preserves protects a thriving mixed-grass prairie ecosystem with bison, elk, pronghorn, and black-footed ferrets.",
    rating: 4.7,
    reviews: 13740,
    fee: "$10–30/person (cave tours)",
    bestTime: "May–September",
    duration: "Half day–1 day",
    activities: ["Cave Tours", "Hiking", "Wildlife Watching", "Scenic Driving", "Photography"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "https://picsum.photos/seed/wind-cave-sd/800/450",
    tags: ["Cave", "Boxwork", "Bison", "Subterranean"]
  },
  {
    id: 50,
    name: "Hot Springs National Park",
    slug: "hot-springs-np-ar",
    state: "Arkansas",
    region: "Southeast",
    category: "National Park",
    description: "Hot Springs is the smallest and one of the oldest protected areas in the National Park System, established as a federal reservation in 1832—40 years before Yellowstone. Forty-seven naturally hot springs (143°F) emerge from the western slope of Hot Springs Mountain, and the elegant bathhouses along Bathhouse Row on Central Avenue once drew presidents, gangsters, and celebrities for their healing waters. Several restored bathhouses still offer traditional thermal baths, blending park history with living spa culture in a charming downtown setting.",
    rating: 4.5,
    reviews: 17260,
    fee: "Free (bathhouse fees vary)",
    bestTime: "March–May, Sept–Nov",
    duration: "Half day–1 day",
    activities: ["Hot Spring Baths", "Hiking", "Historic Tours", "Photography", "Cycling"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/hot-springs-np-ar/800/450",
    tags: ["Hot Springs", "Bathhouses", "Historic", "Thermal Waters"]
  }
];
