// U.S. Tourist Attractions — Page 5 (IDs 101–160)
// Missing National Parks + Top National Monuments, Seashores, Recreation Areas, and Historic Sites

const attractionsPage5 = [

  // ─────────────────────────────────────────────────────────────
  // SECTION 1: MISSING OFFICIAL US NATIONAL PARKS (IDs 101–106)
  // ─────────────────────────────────────────────────────────────

  {
    id: 101,
    name: "Haleakalā National Park",
    slug: "haleakala",
    state: "Hawaii",
    region: "Hawaii",
    category: "National Park",
    description: "Haleakalā—'House of the Sun' in Hawaiian—encompasses the world's largest dormant volcano, whose 10,023-foot summit crater stretches seven miles wide and two miles deep, a surreal alien landscape of cinder cones and silversword plants found nowhere else on Earth. Watching sunrise from the summit is so transcendent that visitors must now reserve timed-entry permits months in advance. The park's remote Kīpahulu District on the island's wet eastern coast shelters the breathtaking Ohe'o Gulch with its famous Seven Sacred Pools, surrounded by ancient Hawaiian history and lush rainforest.",
    rating: 4.8,
    reviews: 31200,
    fee: "$30/vehicle",
    bestTime: "April–June, September–November",
    duration: "1–2 days",
    activities: ["Sunrise Viewing", "Hiking", "Stargazing", "Cycling", "Wildlife Watching"],
    difficulty: "Moderate",
    accessibility: true,
    image: "../shared/images/haleakala.jpg",
    tags: ["Volcano", "Sunrise", "Hawaii", "Silversword", "Dark Sky"],
    lodgingCost: "$$$",
    travelTime: { nyc: 11, chi: 10, la: 6, bay: 6 }
  },

  {
    id: 102,
    name: "Great Basin National Park",
    slug: "great-basin",
    state: "Nevada",
    region: "Rocky Mountains",
    category: "National Park",
    description: "One of the least-visited and most underrated parks in the lower 48, Great Basin rises dramatically from Nevada's high desert to the 13,063-foot summit of Wheeler Peak, where a remnant glacier—the southernmost in the United States—persists beneath the rocky cirque. The Lehman Caves are among the finest marble caverns in the country, richly decorated with rare shield formations and aragonite cave popcorn. Above all else, Great Basin is famed for its darkness: as an International Dark Sky Park, it offers some of the most spectacular stargazing accessible by car anywhere in America.",
    rating: 4.7,
    reviews: 8400,
    fee: "$15/vehicle",
    bestTime: "June–September",
    duration: "1–2 days",
    activities: ["Cave Tours", "Hiking", "Stargazing", "Scenic Driving", "Wildlife Watching"],
    difficulty: "Moderate",
    accessibility: true,
    image: "../shared/images/great-basin.jpg",
    tags: ["Dark Sky", "Caves", "Nevada", "Glacier", "Remote"],
    lodgingCost: "$",
    travelTime: { nyc: 7, chi: 5.5, la: 3, bay: 3 }
  },

  {
    id: 103,
    name: "Black Canyon of the Gunnison National Park",
    slug: "black-canyon-gunnison",
    state: "Colorado",
    region: "Rocky Mountains",
    category: "National Park",
    description: "Few canyons on Earth are as sheer, dark, or dramatic as Black Canyon of the Gunnison, where the Gunnison River has carved walls of ancient 1.7-billion-year-old Precambrian schist and gneiss dropping 2,722 feet in just 48 miles—some walls so narrow that sunlight reaches the canyon floor for only minutes a day. The South Rim Drive delivers a series of vertiginous overlooks, each more startling than the last, while the Painted Wall is the tallest cliff face in Colorado at 2,250 feet. Inner canyon routes descend unmarked wilderness routes, rewarding skilled climbers and hikers with a profound sense of being swallowed by the Earth.",
    rating: 4.8,
    reviews: 12600,
    fee: "$30/vehicle",
    bestTime: "May–October",
    duration: "1–2 days",
    activities: ["Scenic Driving", "Hiking", "Rock Climbing", "Stargazing", "Photography"],
    difficulty: "Moderate to Strenuous",
    accessibility: true,
    image: "../shared/images/black-canyon-gunnison.jpg",
    tags: ["Canyon", "Colorado", "Sheer Cliffs", "Dark Sky", "Remote"],
    lodgingCost: "$",
    travelTime: { nyc: 6, chi: 4.5, la: 4.5, bay: 4.5 }
  },

  {
    id: 104,
    name: "Virgin Islands National Park",
    slug: "virgin-islands",
    state: "U.S. Virgin Islands",
    region: "Southeast",
    category: "National Park",
    description: "Covering nearly two-thirds of the island of St. John in the U.S. Virgin Islands, this tropical paradise combines some of the clearest turquoise waters in the Caribbean with lush hillside forests, pristine white-sand beaches, and the haunting ruins of 18th-century Danish sugar plantations. Trunk Bay's underwater snorkel trail is consistently ranked among the world's best snorkeling experiences, threading through coral gardens alive with sea turtles, eagle rays, and hundreds of tropical fish species. The park's remoteness from the mainland keeps crowds manageable, making it feel far more exclusive than its extraordinary beauty would suggest.",
    rating: 4.9,
    reviews: 19800,
    fee: "$35/vehicle (ferry required)",
    bestTime: "December–April",
    duration: "2–5 days",
    activities: ["Snorkeling", "Swimming", "Hiking", "Kayaking", "Wildlife Watching"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/virgin-islands.jpg",
    tags: ["Tropical", "Caribbean", "Snorkeling", "Beach", "Coral Reef"],
    lodgingCost: "$$$",
    travelTime: { nyc: 4.5, chi: 5.5, la: 7, bay: 7.5 }
  },

  {
    id: 105,
    name: "National Park of American Samoa",
    slug: "american-samoa",
    state: "American Samoa",
    region: "Pacific West",
    category: "National Park",
    description: "The only national park south of the equator, American Samoa protects some of the most pristine tropical rainforest and coral reef ecosystems remaining in the Pacific, spread across the rugged volcanic islands of Tutuila, Ofu, and Ta'ū—the largest remnant of the ancient supercontinent Gondwana in the Pacific. The fringing reefs of Ofu Beach are considered among the healthiest coral ecosystems in U.S. waters, with visibility so clear that the bottom is visible in 80 feet of water. Samoan culture, including the fa'asamoa way of life, is woven into the fabric of the park experience, with homestays in traditional Samoan villages offered as the primary form of lodging.",
    rating: 4.8,
    reviews: 2100,
    fee: "Free",
    bestTime: "May–October",
    duration: "3–7 days",
    activities: ["Snorkeling", "Hiking", "Cultural Immersion", "Birdwatching", "Swimming"],
    difficulty: "Moderate to Strenuous",
    accessibility: false,
    image: "../shared/images/american-samoa.jpg",
    tags: ["Tropical", "Pacific", "Coral Reef", "Remote", "Cultural"],
    lodgingCost: "$$",
    travelTime: { nyc: 16, chi: 15, la: 11, bay: 11 }
  },

  {
    id: 106,
    name: "Glacier Bay National Park",
    slug: "glacier-bay",
    state: "Alaska",
    region: "Alaska",
    category: "National Park",
    description: "Just 250 years ago, Glacier Bay was entirely buried under 4,000 feet of glacial ice; today it is one of the world's most stunning laboratories of ecological succession, where visitors can watch nature reclaiming land mile by mile as 1,000 glaciers have retreated. Massive tidewater glaciers like Grand Pacific and Margerie Glacier still calve cathedral-sized icebergs into the frigid waters with thunderous crashes, while humpback whales, orcas, brown bears, and wolf packs inhabit the surrounding wilderness. Accessible only by boat or small plane from Juneau, this UNESCO World Heritage Site receives fewer than 600,000 visitors a year, preserving its profound sense of raw, primordial wilderness.",
    rating: 4.9,
    reviews: 11400,
    fee: "Free",
    bestTime: "May–September",
    duration: "3–5 days",
    activities: ["Boat Tours", "Kayaking", "Wildlife Watching", "Glacier Viewing", "Hiking"],
    difficulty: "Moderate",
    accessibility: false,
    image: "../shared/images/glacier-bay.jpg",
    tags: ["Glacier", "Alaska", "UNESCO", "Tidewater", "Wildlife"],
    lodgingCost: "$$$",
    travelTime: { nyc: 9, chi: 8.5, la: 6.5, bay: 6.5 }
  },

  // ─────────────────────────────────────────────────────────────
  // SECTION 2: TOP NATIONAL MONUMENTS (IDs 107–126)
  // ─────────────────────────────────────────────────────────────

  {
    id: 107,
    name: "Statue of Liberty National Monument",
    slug: "statue-of-liberty",
    state: "New York",
    region: "Northeast",
    category: "National Monument",
    description: "Standing 305 feet from ground to torch tip, the Statue of Liberty has greeted millions of immigrants and symbolized freedom to the world since France gifted her to the United States in 1886. The copper-clad icon—green with a century of patina—stands on Liberty Island in New York Harbor, and crown tickets (offering the most dramatic views from her tiara) are among the most in-demand reservations in the national park system. The Ellis Island immigration museum, just a short ferry ride away, completes one of the most emotionally resonant heritage experiences in America.",
    rating: 4.7,
    reviews: 63400,
    fee: "$24/adult (ferry + grounds); crown tickets extra",
    bestTime: "April–October",
    duration: "Half day–1 day",
    activities: ["Ferry Ride", "Museum", "Photography", "Guided Tours", "History Education"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/statue-of-liberty.jpg",
    tags: ["Iconic", "History", "NYC", "Immigration", "Symbol of Freedom"],
    lodgingCost: "$$$",
    travelTime: { nyc: 0.5, chi: 2.5, la: 6, bay: 6.5 }
  },

  {
    id: 108,
    name: "Grand Staircase-Escalante National Monument",
    slug: "grand-staircase-escalante",
    state: "Utah",
    region: "Southwest",
    category: "National Monument",
    description: "One of the largest national monuments in the continental United States, Grand Staircase-Escalante encompasses nearly 1.9 million acres of remote Utah canyon country—a labyrinthine wilderness of slot canyons, ancient petrified forests, sweeping vermilion cliffs, and some of the world's most productive dinosaur fossil beds. Coyote Gulch, Peek-a-Boo and Spooky slot canyons, and the luminous Lower Calf Creek Falls waterfall are crown jewels of an area so vast and complex that decades of exploration wouldn't exhaust its wonders. No other landscape so perfectly distills the raw, uncompromising character of the American Southwest's canyon country.",
    rating: 4.8,
    reviews: 16800,
    fee: "Free",
    bestTime: "March–May, September–November",
    duration: "2–5 days",
    activities: ["Hiking", "Slot Canyon Exploration", "Photography", "Backpacking", "Stargazing"],
    difficulty: "Moderate to Strenuous",
    accessibility: false,
    image: "../shared/images/grand-staircase-escalante.jpg",
    tags: ["Slot Canyons", "Utah", "Remote", "Fossils", "Canyon Country"],
    lodgingCost: "$",
    travelTime: { nyc: 8, chi: 7, la: 4, bay: 5 }
  },

  {
    id: 109,
    name: "Bears Ears National Monument",
    slug: "bears-ears",
    state: "Utah",
    region: "Southwest",
    category: "National Monument",
    description: "Named for two distinctive buttes that rise like twin ears above Cedar Mesa, Bears Ears is one of the most culturally significant landscapes in North America, containing an estimated 100,000 archaeological sites including cliff dwellings, kivas, rock art panels, and sacred sites of the Navajo, Hopi, Ute, and Zuni peoples. The monument's designation in 2016 followed years of advocacy by five tribal nations—the first time Indigenous communities led a successful national monument campaign. Moon House Ruin, Valley of the Gods, and Comb Ridge offer extraordinary solitude and a palpable connection to ten thousand years of human habitation.",
    rating: 4.8,
    reviews: 9600,
    fee: "Free",
    bestTime: "March–May, September–November",
    duration: "2–4 days",
    activities: ["Hiking", "Archaeology", "Photography", "Off-Roading", "Cultural Interpretation"],
    difficulty: "Moderate",
    accessibility: false,
    image: "../shared/images/bears-ears.jpg",
    tags: ["Archaeology", "Native American", "Utah", "Remote", "Sacred Sites"],
    lodgingCost: "$",
    travelTime: { nyc: 8.5, chi: 7, la: 5, bay: 5.5 }
  },

  {
    id: 110,
    name: "Cascade-Siskiyou National Monument",
    slug: "cascade-siskiyou",
    state: "Oregon",
    region: "Pacific West",
    category: "National Monument",
    description: "The world's first national monument designated specifically to protect a unique biological crossroads, Cascade-Siskiyou sits at the intersection of three major mountain ranges—the Cascade, Siskiyou, and Great Basin—creating a biological hotspot of extraordinary plant and animal diversity. The meeting of these ranges produces microclimates where species from the Pacific rainforest, the Great Basin desert, and the Klamath Mountains intermingle in an ecological tapestry found nowhere else. Hikers on the Pacific Crest Trail pass through the monument's rolling grasslands and oak savannas with panoramic views of Mount Shasta.",
    rating: 4.5,
    reviews: 4200,
    fee: "Free",
    bestTime: "May–October",
    duration: "1–2 days",
    activities: ["Hiking", "Birdwatching", "Wildflower Viewing", "Scenic Driving", "Photography"],
    difficulty: "Moderate",
    accessibility: true,
    image: "../shared/images/cascade-siskiyou.jpg",
    tags: ["Biodiversity", "Oregon", "Pacific Crest Trail", "Grasslands", "Crossroads"],
    lodgingCost: "$",
    travelTime: { nyc: 9, chi: 7.5, la: 4, bay: 4 }
  },

  {
    id: 111,
    name: "Organ Pipe Cactus National Monument",
    slug: "organ-pipe-cactus",
    state: "Arizona",
    region: "Southwest",
    category: "National Monument",
    description: "On the U.S.-Mexico border in Arizona's Sonoran Desert, Organ Pipe Cactus National Monument is the only place in the United States where the majestic organ pipe cactus grows wild—its multi-armed columns clustering in dense forests across the sun-scorched bajadas. A UNESCO Biosphere Reserve, the monument protects the most botanically diverse section of the Sonoran Desert, including 28 cactus species, saguaros, and the night-blooming senita. The Ajo Mountain Drive and Puerto Blanco Loop wind through remote desert landscapes where javelinas, Gila woodpeckers, and desert tortoises roam under skies so dark the Milky Way is visible to the naked eye.",
    rating: 4.6,
    reviews: 7800,
    fee: "$25/vehicle",
    bestTime: "October–April",
    duration: "1–2 days",
    activities: ["Scenic Driving", "Hiking", "Stargazing", "Wildlife Watching", "Photography"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/organ-pipe-cactus.jpg",
    tags: ["Cactus", "Sonoran Desert", "Arizona", "Dark Sky", "UNESCO"],
    lodgingCost: "$",
    travelTime: { nyc: 7, chi: 5.5, la: 3, bay: 4 }
  },

  {
    id: 112,
    name: "Chiricahua National Monument",
    slug: "chiricahua",
    state: "Arizona",
    region: "Southwest",
    category: "National Monument",
    description: "A 'Wonderland of Rocks' hidden in southeastern Arizona's sky island mountains, Chiricahua's volcanic rhyolite has been sculpted over 27 million years of erosion into thousands of soaring balanced rocks, spires, and columns—many balanced impossibly atop narrow pedestals. Known as the homeland of the Chiricahua Apache and the stronghold of Cochise, the area carries deep historical weight alongside its geological spectacle. The Rhyolite Canyon trail network winds through hoodoo forests where elegant trogons, rare coatimundis, and white-tailed deer share this ecological crossroads between the Rocky Mountains and the Sierra Madre.",
    rating: 4.7,
    reviews: 6300,
    fee: "$25/vehicle",
    bestTime: "March–May, September–November",
    duration: "1 day",
    activities: ["Hiking", "Photography", "Birdwatching", "Wildlife Watching", "Scenic Driving"],
    difficulty: "Moderate",
    accessibility: true,
    image: "../shared/images/chiricahua.jpg",
    tags: ["Rock Formations", "Arizona", "Hoodoos", "Sky Island", "Apache History"],
    lodgingCost: "$",
    travelTime: { nyc: 7, chi: 5.5, la: 3.5, bay: 4.5 }
  },

  {
    id: 113,
    name: "Colorado National Monument",
    slug: "colorado-national-monument",
    state: "Colorado",
    region: "Rocky Mountains",
    category: "National Monument",
    description: "Just outside of Grand Junction, Colorado National Monument is one of the American West's hidden gems—a landscape of sheer-walled canyons, towering monoliths, and sweeping desert plateaus carved from dark red Precambrian granite and rose-colored Entrada sandstone. Rim Rock Drive hugs the canyon edge for 23 miles, delivering panoramic views of the Grand Valley and the Book Cliffs beyond. The monument's two free-standing monoliths—Independence Monument and Kissing Couple—are beloved rock climbing destinations, while canyon wrens and canyon tree frogs serenade hikers in the sandstone alcoves below.",
    rating: 4.7,
    reviews: 11200,
    fee: "$25/vehicle",
    bestTime: "April–October",
    duration: "1 day",
    activities: ["Scenic Driving", "Hiking", "Rock Climbing", "Photography", "Cycling"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "../shared/images/colorado-national-monument.jpg",
    tags: ["Canyon", "Colorado", "Monoliths", "Road Trip", "Desert"],
    lodgingCost: "$",
    travelTime: { nyc: 6, chi: 4.5, la: 4, bay: 4 }
  },

  {
    id: 114,
    name: "Bandelier National Monument",
    slug: "bandelier",
    state: "New Mexico",
    region: "Southwest",
    category: "National Monument",
    description: "Carved into the soft volcanic tuff of Frijoles Canyon in New Mexico's Pajarito Plateau, Bandelier protects the ancient cave dwellings, cliff rooms, and great kiva of the Ancestral Puebloan people who lived here from the 12th through 16th centuries. Visitors can climb wooden ladders into alcove houses and walk through kivas—circular ceremonial chambers—that bring the lives of these ancient inhabitants vividly to life. The canyon's lush riparian corridor, watered by a perennial stream, provides a vivid contrast with the surrounding high desert mesas and supports an abundance of wildlife including mule deer and wild turkeys.",
    rating: 4.7,
    reviews: 13600,
    fee: "$25/vehicle",
    bestTime: "April–October",
    duration: "1 day",
    activities: ["Hiking", "Archaeology", "Cliff Dwelling Exploration", "Photography", "Ranger Programs"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "../shared/images/bandelier.jpg",
    tags: ["Cliff Dwellings", "Ancestral Puebloans", "New Mexico", "Archaeology", "Canyon"],
    lodgingCost: "$",
    travelTime: { nyc: 7, chi: 5.5, la: 4.5, bay: 5 }
  },

  {
    id: 115,
    name: "Ocmulgee Mounds National Historical Park",
    slug: "ocmulgee-mounds",
    state: "Georgia",
    region: "Southeast",
    category: "National Monument",
    description: "One of the most significant archaeological sites in the American Southeast, Ocmulgee preserves the earthwork mounds built by the Mississippian culture between 900 and 1600 CE—including a reconstructed earth lodge whose original clay floor is over a thousand years old and still intact. The Great Temple Mound rises 55 feet above a plateau above the Ocmulgee River, offering sweeping views of central Georgia. The site represents 17,000 years of continuous human habitation, one of the longest such records in North America, and remains sacred to the Muscogee (Creek) Nation whose ancestors built and inhabited these structures.",
    rating: 4.6,
    reviews: 5400,
    fee: "Free",
    bestTime: "March–November",
    duration: "Half day",
    activities: ["Archaeology Tours", "Hiking", "History Education", "Photography", "Ranger Programs"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/ocmulgee-mounds.jpg",
    tags: ["Archaeology", "Mounds", "Native American", "Georgia", "History"],
    lodgingCost: "$",
    travelTime: { nyc: 3.5, chi: 3, la: 5.5, bay: 6 }
  },

  {
    id: 116,
    name: "Hohokam Pima National Monument",
    slug: "hohokam-pima",
    state: "Arizona",
    region: "Southwest",
    category: "National Monument",
    description: "Protecting the ruins of Snaketown—one of the most important Hohokam archaeological sites in the American Southwest—Hohokam Pima preserves the remnants of a sophisticated pre-Columbian civilization that developed one of the most extensive canal irrigation systems in the ancient world, channeling water from the Gila River to support a population of thousands between 300 BCE and 1400 CE. The site is managed by the Gila River Indian Community and is rarely open to general public access, making it among the most exclusive protected areas in the national park system. The Hohokam legacy is visible throughout the Phoenix metro area, where their ancient canals still underlie modern irrigation infrastructure.",
    rating: 4.4,
    reviews: 1800,
    fee: "Restricted access (managed by Gila River Indian Community)",
    bestTime: "October–April",
    duration: "Half day",
    activities: ["Archaeology Tours", "Cultural Interpretation", "Photography", "History Education"],
    difficulty: "Easy",
    accessibility: false,
    image: "../shared/images/hohokam-pima.jpg",
    tags: ["Archaeology", "Hohokam", "Arizona", "Ancient Canals", "Native American"],
    lodgingCost: "$",
    travelTime: { nyc: 6.5, chi: 5, la: 3, bay: 4 }
  },

  {
    id: 117,
    name: "Aztec Ruins National Monument",
    slug: "aztec-ruins",
    state: "New Mexico",
    region: "Southwest",
    category: "National Monument",
    description: "Despite its misleading name—the site was built by Ancestral Puebloans, not Aztecs—Aztec Ruins preserves one of the best-preserved great houses in the American Southwest, a 500-room masonry structure built around 1100 CE that served as a ceremonial and trade center for the broader Chacoan world. The fully reconstructed Great Kiva is the only fully restored structure of its kind in existence, offering visitors the rare experience of stepping inside an intact ceremonial space as it appeared nine centuries ago. The monument's location along the Animas River in the Four Corners region places it at the heart of the ancient Pueblo world.",
    rating: 4.6,
    reviews: 5100,
    fee: "$20/vehicle",
    bestTime: "April–October",
    duration: "Half day",
    activities: ["Archaeology Tours", "Guided Tours", "Photography", "History Education", "Ranger Programs"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/aztec-ruins.jpg",
    tags: ["Archaeology", "Ancestral Puebloans", "New Mexico", "Great Kiva", "Four Corners"],
    lodgingCost: "$",
    travelTime: { nyc: 7, chi: 5.5, la: 5, bay: 5.5 }
  },

  {
    id: 118,
    name: "Florissant Fossil Beds National Monument",
    slug: "florissant-fossil-beds",
    state: "Colorado",
    region: "Rocky Mountains",
    category: "National Monument",
    description: "Thirty-four million years ago, a series of volcanic eruptions buried an Eocene-era lake in ash, entombing insects, leaves, fish, birds, and mammals with extraordinary fidelity—creating what may be the world's most diverse fossil insect fauna, with over 1,700 species recorded. Petrified redwood stumps up to 14 feet in diameter punctuate the meadows, the root systems still visible in weathering stone. Today hikers walk trails through wildflower-carpeted meadows with Pikes Peak rising magnificently on the horizon, seemingly unaware that beneath their feet lies a snapshot of ancient life frozen in time.",
    rating: 4.6,
    reviews: 6700,
    fee: "$20/vehicle",
    bestTime: "May–October",
    duration: "Half day–1 day",
    activities: ["Hiking", "Fossil Viewing", "Photography", "Ranger Programs", "Wildlife Watching"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/florissant-fossil-beds.jpg",
    tags: ["Fossils", "Paleontology", "Colorado", "Petrified Wood", "Wildflowers"],
    lodgingCost: "$",
    travelTime: { nyc: 5.5, chi: 4, la: 4.5, bay: 4.5 }
  },

  {
    id: 119,
    name: "Scotts Bluff National Monument",
    slug: "scotts-bluff",
    state: "Nebraska",
    region: "Great Plains",
    category: "National Monument",
    description: "Rising 800 feet above the North Platte River valley, Scotts Bluff was the most recognizable landmark along the Oregon Trail—a massive geological sentinel that 500,000 emigrant pioneers used to orient themselves as they crossed the Great Plains in the 1840s through 1860s. The summit drive or strenuous hiking trail rewards visitors with panoramic views across the valley that closely match the sketches made by frontier artist William Henry Jackson. Exhibits in the visitor center trace the stories of families who staked everything on the journey west, many passing directly below the bluff's towering prow.",
    rating: 4.5,
    reviews: 8900,
    fee: "$20/vehicle",
    bestTime: "May–October",
    duration: "Half day",
    activities: ["Scenic Driving", "Hiking", "History Education", "Photography", "Visitor Center"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "../shared/images/scotts-bluff.jpg",
    tags: ["Oregon Trail", "Pioneer History", "Nebraska", "Geology", "Great Plains"],
    lodgingCost: "$",
    travelTime: { nyc: 5.5, chi: 3.5, la: 5.5, bay: 5.5 }
  },

  {
    id: 120,
    name: "Effigy Mounds National Monument",
    slug: "effigy-mounds",
    state: "Iowa",
    region: "Great Plains",
    category: "National Monument",
    description: "Effigy Mounds preserves 206 prehistoric earthen mounds built by Indigenous peoples between 500 BCE and 1200 CE along the bluffs above the Mississippi River in northeastern Iowa—including 31 in the shapes of birds, bears, and other animals, representing one of the finest surviving examples of the effigy mound tradition in the world. The Great Bear Mound Group contains some of the largest bear effigies known, stretching over 130 feet in length. Forested trails connect the mounds through a landscape of oak savannas and river views that remains largely unchanged from the era when these spiritual monuments were created.",
    rating: 4.5,
    reviews: 5600,
    fee: "Free",
    bestTime: "April–October",
    duration: "Half day",
    activities: ["Hiking", "History Education", "Archaeology", "Photography", "Nature Walks"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "../shared/images/effigy-mounds.jpg",
    tags: ["Mounds", "Native American", "Iowa", "Mississippi River", "Archaeology"],
    lodgingCost: "$",
    travelTime: { nyc: 4.5, chi: 2, la: 6, bay: 6.5 }
  },

  {
    id: 121,
    name: "Cabrillo National Monument",
    slug: "cabrillo",
    state: "California",
    region: "Pacific West",
    category: "National Monument",
    description: "Perched at the tip of the Point Loma peninsula in San Diego, Cabrillo National Monument commemorates the 1542 landing of Portuguese explorer Juan Rodríguez Cabrillo—the first European to set foot on the West Coast of the United States. The monument offers 360-degree panoramas taking in the San Diego skyline, Coronado Island, Mexico's Baja Peninsula, and the open Pacific, while tide pools along the rocky shoreline teem with sea stars, anemones, and hermit crabs. The restored 1855 Old Point Loma Lighthouse stands sentinel above it all, and the Pacific Flyway funnels thousands of migratory birds past the peninsula each fall.",
    rating: 4.6,
    reviews: 18400,
    fee: "$20/vehicle",
    bestTime: "March–November",
    duration: "Half day",
    activities: ["Tide Pooling", "Hiking", "Photography", "Whale Watching", "History Education"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/cabrillo.jpg",
    tags: ["San Diego", "California", "Tide Pools", "History", "Panoramic Views"],
    lodgingCost: "$$$",
    travelTime: { nyc: 6.5, chi: 5, la: 2.5, bay: 2 }
  },

  {
    id: 122,
    name: "Alibates Flint Quarries National Monument",
    slug: "alibates-flint-quarries",
    state: "Texas",
    region: "Southwest",
    category: "National Monument",
    description: "For at least 13,000 years, Indigenous peoples traveled hundreds of miles to the Canadian River breaks of the Texas Panhandle to quarry the brilliant agatized dolomite—Alibates flint—whose rainbow hues of red, purple, orange, and white made it the most prized tool stone on the southern Great Plains. Alibates artifacts have been found throughout the Great Plains, Rocky Mountains, and as far away as the Gulf of Mexico, testament to the stone's extraordinary desirability. Ranger-led hikes to the quarry pits—the only way to access the monument—reveal the ancient mining pits still littered with thousands of years of quarrying debris.",
    rating: 4.5,
    reviews: 3200,
    fee: "Free (ranger-led tours only)",
    bestTime: "April–October",
    duration: "Half day",
    activities: ["Ranger-Led Tours", "Archaeology", "History Education", "Photography", "Hiking"],
    difficulty: "Easy",
    accessibility: false,
    image: "../shared/images/alibates-flint-quarries.jpg",
    tags: ["Archaeology", "Flint Quarries", "Texas", "Native American", "Prehistoric"],
    lodgingCost: "$",
    travelTime: { nyc: 6, chi: 4, la: 5, bay: 5.5 }
  },

  {
    id: 123,
    name: "Petroglyph National Monument",
    slug: "petroglyph",
    state: "New Mexico",
    region: "Southwest",
    category: "National Monument",
    description: "On the West Mesa escarpment at Albuquerque's western edge, Petroglyph National Monument protects one of the largest petroglyph sites in North America—over 24,000 images carved into the dark basalt boulders by ancestral Pueblo peoples and early Spanish settlers over a span of 700 years. Carved images range from geometric designs and animals to spiritual symbols and human figures, each a window into the belief systems and daily life of the people who made them. Three hiking areas—Boca Negra Canyon, Rinconada Canyon, and Piedras Marcadas Canyon—allow visitors to walk among the petroglyphs in a setting of volcanic rock against the backdrop of the Sandia Mountains.",
    rating: 4.5,
    reviews: 12600,
    fee: "$2/vehicle (Boca Negra); other areas free",
    bestTime: "March–November",
    duration: "Half day",
    activities: ["Hiking", "Archaeology", "Photography", "Cultural Interpretation", "Ranger Programs"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/petroglyph.jpg",
    tags: ["Petroglyphs", "Rock Art", "New Mexico", "Ancestral Puebloans", "Volcanic"],
    lodgingCost: "$",
    travelTime: { nyc: 6.5, chi: 5, la: 4.5, bay: 5 }
  },

  {
    id: 124,
    name: "Tonto National Monument",
    slug: "tonto",
    state: "Arizona",
    region: "Southwest",
    category: "National Monument",
    description: "Tucked into the rugged Superstition Mountains above the shores of Roosevelt Lake, Tonto National Monument preserves two remarkably well-preserved cliff dwellings occupied by the Salado people between 1250 and 1450 CE. The Lower Ruin is a self-guided 1-mile round-trip hike with stunning views of the desert lake below; the Upper Ruin, accessible only on ranger-led tours, features a 40-room structure sheltered beneath a massive natural overhang and contains original wooden beams and woven cotton textiles. The juxtaposition of ancient architecture, azure lake water, and cactus-studded Sonoran desert is among the most visually arresting in the Southwest.",
    rating: 4.6,
    reviews: 7100,
    fee: "Free",
    bestTime: "October–April",
    duration: "Half day",
    activities: ["Hiking", "Guided Tours", "Photography", "Archaeology", "Wildlife Watching"],
    difficulty: "Moderate",
    accessibility: false,
    image: "../shared/images/tonto.jpg",
    tags: ["Cliff Dwellings", "Salado", "Arizona", "Desert Lake", "Archaeology"],
    lodgingCost: "$",
    travelTime: { nyc: 6.5, chi: 5, la: 3, bay: 4 }
  },

  {
    id: 125,
    name: "Montezuma Castle National Monument",
    slug: "montezuma-castle",
    state: "Arizona",
    region: "Southwest",
    category: "National Monument",
    description: "One of the best-preserved cliff dwellings in North America, Montezuma Castle is a five-story, 20-room limestone and mortar structure built into a natural limestone alcove 100 feet above Beaver Creek by the Sinagua people around 1100 CE—it was mistakenly named after the Aztec emperor by early European explorers who assumed it must be of Mexican origin. The sheer inaccessibility of the dwelling—originally reached by removable ladders—kept it remarkably intact through the centuries, and today visitors view it from a paved accessible trail below. Nearby Montezuma Well, a spring-fed limestone sinkhole sacred to multiple tribes, harbors unique aquatic species found nowhere else on Earth.",
    rating: 4.6,
    reviews: 15800,
    fee: "$10/person",
    bestTime: "October–April",
    duration: "Half day",
    activities: ["Sightseeing", "Photography", "History Education", "Nature Walks", "Ranger Programs"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/montezuma-castle.jpg",
    tags: ["Cliff Dwellings", "Sinagua", "Arizona", "Well Preserved", "History"],
    lodgingCost: "$",
    travelTime: { nyc: 6.5, chi: 5, la: 3.5, bay: 4 }
  },

  {
    id: 126,
    name: "Canyons of the Ancients National Monument",
    slug: "canyons-of-the-ancients",
    state: "Colorado",
    region: "Rocky Mountains",
    category: "National Monument",
    description: "Canyons of the Ancients contains the highest known density of archaeological sites of any area managed by the Bureau of Land Management in the United States—over 6,000 recorded sites per square mile in some areas, including cliff dwellings, great houses, kiva complexes, reservoirs, towers, and shrines built by the Ancestral Pueblo, Fremont, and Ute peoples over a span of 10,000 years. The Lowry Pueblo, a 40-room great house with one of the largest Great Kivas known, is the monument's most accessible site; the remote Sand Canyon Pueblo complex, connected to the Chacoan road network, ranks among the most significant unexcavated sites in North America. The landscape of pinyon-juniper mesas, canyon-cut drainages, and sweeping high-desert vistas amplifies the profound sense of deep time that permeates the monument.",
    rating: 4.6,
    reviews: 5800,
    fee: "Free",
    bestTime: "April–October",
    duration: "1–2 days",
    activities: ["Archaeology", "Hiking", "Photography", "Off-Roading", "Ranger Programs"],
    difficulty: "Moderate",
    accessibility: false,
    image: "../shared/images/canyons-of-the-ancients.jpg",
    tags: ["Archaeology", "Ancestral Puebloans", "Colorado", "Remote", "Dense Sites"],
    lodgingCost: "$",
    travelTime: { nyc: 7, chi: 5.5, la: 5, bay: 5 }
  },

  // ─────────────────────────────────────────────────────────────
  // SECTION 3: NATIONAL SEASHORES & LAKESHORES (IDs 127–136)
  // ─────────────────────────────────────────────────────────────

  {
    id: 127,
    name: "Cape Cod National Seashore",
    slug: "cape-cod",
    state: "Massachusetts",
    region: "Northeast",
    category: "National Seashore",
    description: "Stretching 40 miles along the outer arm of Cape Cod, this national seashore protects some of the finest barrier beach and dune landscapes in the Northeast—a glacially sculpted coastline of towering clay bluffs, freshwater kettle ponds, pitch pine forests, and legendary Atlantic surf beaches. Nauset Light and Highland Light stand guard over eroding clay headlands that have claimed hundreds of ships; the marshes and tidal flats are critical habitat for piping plovers, terns, and migrating shorebirds. The Cape Cod Rail Trail offers a perfect cycling route through the maritime landscape between the ocean and bay.",
    rating: 4.7,
    reviews: 24600,
    fee: "$25/vehicle",
    bestTime: "June–September",
    duration: "1–3 days",
    activities: ["Swimming", "Cycling", "Birdwatching", "Fishing", "Lighthouse Tours"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/cape-cod.jpg",
    tags: ["Beach", "Massachusetts", "Lighthouse", "Cycling", "Atlantic"],
    lodgingCost: "$$$",
    travelTime: { nyc: 4, chi: 5.5, la: 10, bay: 10.5 }
  },

  {
    id: 128,
    name: "Point Reyes National Seashore",
    slug: "point-reyes",
    state: "California",
    region: "Pacific West",
    category: "National Seashore",
    description: "A triangular peninsula jutting 10 miles into the Pacific north of San Francisco, Point Reyes is one of the windiest spots in North America and among the most ecologically remarkable protected areas on the West Coast. The park sits astride the San Andreas Fault—the 1906 earthquake that destroyed San Francisco caused the land here to shift 20 feet—and its isolation created a unique marine environment where elephant seals, tule elk, and gray whales are easily observed. The historic Point Reyes Lighthouse at the tip of the headland, set against crashing Pacific surf, is one of the most dramatically positioned structures in America.",
    rating: 4.8,
    reviews: 21400,
    fee: "Free",
    bestTime: "April–June, September–November",
    duration: "1–2 days",
    activities: ["Hiking", "Wildlife Watching", "Whale Watching", "Lighthouse Tour", "Birdwatching"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "../shared/images/point-reyes.jpg",
    tags: ["California", "Elk", "Lighthouse", "Elephant Seals", "San Andreas Fault"],
    lodgingCost: "$$",
    travelTime: { nyc: 8, chi: 6.5, la: 3.5, bay: 1.5 }
  },

  {
    id: 129,
    name: "Padre Island National Seashore",
    slug: "padre-island",
    state: "Texas",
    region: "Southwest",
    category: "National Seashore",
    description: "The longest stretch of undeveloped barrier island in the world at 70 miles, Padre Island National Seashore protects a raw, windswept coast along the Texas Gulf that serves as critical nesting habitat for the critically endangered Kemp's ridley sea turtle—the rarest sea turtle on Earth. From June through August, biologists conduct public nest releases where hundreds of hatchlings scramble to the Gulf under the supervision of park rangers and cheering crowds. The wild, undeveloped southern portion of the island, accessible only to high-clearance four-wheel-drive vehicles on the beach, delivers a genuinely remote coastal experience in the continental United States.",
    rating: 4.6,
    reviews: 14800,
    fee: "$10/vehicle",
    bestTime: "April–October",
    duration: "1–3 days",
    activities: ["Swimming", "Fishing", "Sea Turtle Nesting", "4WD Beach Driving", "Birdwatching"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/padre-island.jpg",
    tags: ["Beach", "Texas", "Sea Turtles", "Gulf Coast", "Undeveloped"],
    lodgingCost: "$",
    travelTime: { nyc: 5.5, chi: 4, la: 4.5, bay: 5 }
  },

  {
    id: 130,
    name: "Cumberland Island National Seashore",
    slug: "cumberland-island",
    state: "Georgia",
    region: "Southeast",
    category: "National Seashore",
    description: "Georgia's largest and southernmost barrier island is accessible only by ferry and strictly limits visitors to 300 per day, making it one of the most exclusive beach experiences in America despite being a public park. Wild horses roam freely among the island's ancient live oak forests draped in Spanish moss, and the ruins of the Carnegie family's Dungeness mansion crumble romantically against the blue Atlantic sky. Nearly 18 miles of undeveloped white-sand beach stretch along the Atlantic shore, and loggerhead sea turtles nest here in impressive numbers from May through August.",
    rating: 4.8,
    reviews: 11200,
    fee: "$10/person (ferry extra)",
    bestTime: "April–June, September–November",
    duration: "1–2 days",
    activities: ["Beach, Wildlife Watching", "Hiking", "Historic Ruins", "Birdwatching"],
    difficulty: "Easy to Moderate",
    accessibility: false,
    image: "../shared/images/cumberland-island.jpg",
    tags: ["Wild Horses", "Georgia", "Beach", "Carnegie Ruins", "Remote Island"],
    lodgingCost: "$$",
    travelTime: { nyc: 4, chi: 3.5, la: 5.5, bay: 6 }
  },

  {
    id: 131,
    name: "Fire Island National Seashore",
    slug: "fire-island",
    state: "New York",
    region: "Northeast",
    category: "National Seashore",
    description: "Just 26 miles from Manhattan, Fire Island National Seashore protects a slender barrier island of remarkable wildness where cars are banned (in most areas), communities cluster around ferries, and the Sunken Forest—a magical grove of holly, sassafras, and shadblow sheltered below sea level—creates a fairytale landscape just yards from the Atlantic surf. Fire Island Lighthouse, its 1858 tower restored to full operation, marks the western end of the park. The Otis Pike Fire Island High Dune Wilderness at the island's eastern end is the only federally designated wilderness area in New York State—a windswept, roadless expanse of dunes, heathlands, and marsh.",
    rating: 4.6,
    reviews: 19800,
    fee: "Free (ferry costs vary)",
    bestTime: "June–September",
    duration: "1–2 days",
    activities: ["Beach", "Hiking", "Cycling", "Birdwatching", "Sunken Forest Walk"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/fire-island.jpg",
    tags: ["New York", "Car-Free", "Beach", "Lighthouse", "Sunken Forest"],
    lodgingCost: "$$",
    travelTime: { nyc: 1.5, chi: 3.5, la: 7, bay: 7.5 }
  },

  {
    id: 132,
    name: "Gulf Islands National Seashore",
    slug: "gulf-islands",
    state: "Florida / Mississippi",
    region: "Southeast",
    category: "National Seashore",
    description: "Stretching 160 miles across two states along the Gulf of Mexico, Gulf Islands National Seashore protects some of the most brilliant white-quartz-sand beaches in the world—powdery, sugar-fine shores that stay cool to the touch even in summer heat because of the unique silica composition. The barrier islands harbor rich sea grass beds, nesting sea turtles, and one of the highest concentrations of shorebirds on the Gulf Coast. Historic Fort Pickens on Santa Rosa Island, a massive 19th-century masonry fortification, guarded Pensacola Bay and briefly imprisoned the Apache leader Geronimo in 1886.",
    rating: 4.7,
    reviews: 28400,
    fee: "$25/vehicle",
    bestTime: "October–May",
    duration: "1–3 days",
    activities: ["Swimming", "Snorkeling", "Fishing", "Birdwatching", "Historic Fort"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/gulf-islands.jpg",
    tags: ["White Sand", "Gulf Coast", "Fort Pickens", "Florida", "Beach"],
    lodgingCost: "$$",
    travelTime: { nyc: 3.5, chi: 3, la: 4, bay: 5 }
  },

  {
    id: 133,
    name: "Pictured Rocks National Lakeshore",
    slug: "pictured-rocks-mi",
    state: "Michigan",
    region: "Great Plains",
    category: "National Seashore",
    description: "Multicolored sandstone cliffs streaked with mineral deposits—iron red, copper green, manganese black—rise 200 feet above Lake Superior along Michigan's Upper Peninsula in one of the most visually spectacular lakeshore settings in North America. America's first national lakeshore, designated in 1966, encompasses 42 miles of Superior shoreline including Miners Beach, Chapel Falls, and the extraordinary Chapel Rock arch with a lone white pine growing from its summit. Winter transforms the sea caves into cathedral-like ice formations that attract winter hikers and photographers from around the world, while summer kayakers paddle through turquoise waters past waterfalls plunging directly into the lake.",
    rating: 4.8,
    reviews: 18400,
    fee: "$20/vehicle",
    bestTime: "July–September (kayaking), January–February (ice caves)",
    duration: "2–3 days",
    activities: ["Kayaking", "Hiking", "Photography", "Ice Caves", "Boat Tours"],
    difficulty: "Moderate",
    accessibility: false,
    image: "../shared/images/pictured-rocks-mi.jpg",
    tags: ["Great Lakes", "Michigan", "Ice Caves", "Kayaking", "Cliffs"],
    lodgingCost: "$$",
    travelTime: { nyc: 6, chi: 4, la: 8, bay: 8 }
  },

  {
    id: 134,
    name: "Sleeping Bear Dunes National Lakeshore",
    slug: "sleeping-bear-dunes",
    state: "Michigan",
    region: "Great Plains",
    category: "National Seashore",
    description: "Named by the Ojibwe for a grieving mother bear who swam Lake Michigan and waited for her cubs on the shore—the North and South Manitou Islands visible offshore—Sleeping Bear Dunes National Lakeshore protects 35 miles of Lake Michigan shoreline dominated by massive perched dunes rising 460 feet above the crystal-clear blue waters. The Dune Climb is one of the Midwest's most beloved family experiences, while the Glen Haven Historic District and Sleeping Bear Point preserve the Great Lakes maritime heritage. The park consistently ranks among the most beautiful places in America, voted the 'Most Beautiful Place in America' by viewers of Good Morning America.",
    rating: 4.8,
    reviews: 19600,
    fee: "$25/vehicle",
    bestTime: "June–September",
    duration: "1–3 days",
    activities: ["Dune Climbing", "Swimming", "Hiking", "Kayaking", "Cycling"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "../shared/images/sleeping-bear-dunes.jpg",
    tags: ["Dunes", "Lake Michigan", "Michigan", "Scenic", "Family Friendly"],
    lodgingCost: "$$",
    travelTime: { nyc: 5.5, chi: 3, la: 7, bay: 7 }
  },

  {
    id: 135,
    name: "Canaveral National Seashore",
    slug: "canaveral",
    state: "Florida",
    region: "Southeast",
    category: "National Seashore",
    description: "Adjacent to Kennedy Space Center, Canaveral National Seashore preserves 24 miles of completely undeveloped Florida Atlantic coast—the longest stretch of undisturbed beach on Florida's east coast—where sea turtles nest in extraordinary numbers (over 15,000 nests recorded in a single season), manatees shelter in Mosquito Lagoon, and American alligators sunbathe in the saw grass. The park offers the unique experience of watching Space Coast rocket launches from a pristine wild beach. Seminole Rest, a shell midden complex, adds archaeological depth to what is already one of the most ecologically rich barrier island parks in the system.",
    rating: 4.6,
    reviews: 12400,
    fee: "$20/vehicle",
    bestTime: "October–May",
    duration: "1–2 days",
    activities: ["Swimming", "Sea Turtle Watching", "Fishing", "Rocket Watching", "Hiking"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/canaveral.jpg",
    tags: ["Sea Turtles", "Florida", "Kennedy Space Center", "Undeveloped Beach", "Wildlife"],
    lodgingCost: "$",
    travelTime: { nyc: 3.5, chi: 3, la: 4.5, bay: 5 }
  },

  {
    id: 136,
    name: "Olympic Coast National Marine Sanctuary",
    slug: "olympic-coast-marine",
    state: "Washington",
    region: "Pacific West",
    category: "National Seashore",
    description: "Extending from the jagged sea stacks of the Olympic Peninsula coast 40 miles offshore, Olympic Coast National Marine Sanctuary is one of the nation's largest marine protected areas, harboring some of the most productive cold-water upwelling zones on the West Coast. Gray whales, humpbacks, orcas, Pacific white-sided dolphins, and sea otters share waters with vast seabird colonies—murres, puffins, and cormorants—nesting on offshore rocks. The remote coastline, accessible only by foot, kayak, or boat, is among the wildest and most untouched marine environments in the contiguous United States.",
    rating: 4.7,
    reviews: 8600,
    fee: "Free",
    bestTime: "June–September",
    duration: "2–4 days",
    activities: ["Kayaking", "Whale Watching", "Tidepooling", "Hiking", "Birdwatching"],
    difficulty: "Strenuous",
    accessibility: false,
    image: "../shared/images/olympic-coast-marine.jpg",
    tags: ["Marine Sanctuary", "Washington", "Whales", "Sea Stacks", "Remote"],
    lodgingCost: "$$",
    travelTime: { nyc: 8.5, chi: 7, la: 5, bay: 5 }
  },

  // ─────────────────────────────────────────────────────────────
  // SECTION 4: NATIONAL RECREATION AREAS (IDs 137–146)
  // ─────────────────────────────────────────────────────────────

  {
    id: 137,
    name: "Glen Canyon National Recreation Area",
    slug: "glen-canyon",
    state: "Utah / Arizona",
    region: "Southwest",
    category: "National Recreation Area",
    description: "Glen Canyon NRA encompasses 1.25 million acres centered on Lake Powell—America's second-largest reservoir, formed behind Glen Canyon Dam in 1966—whose 2,000 miles of shoreline weave through some of the most dramatic red-rock canyon country on Earth. Antelope Canyon, the world's most photographed slot canyon famous for its wave-like sandstone walls and heavenly light beams, lies within the recreation area. Though the reservoir level has dropped dramatically due to drought, it has revealed newly accessible hidden canyons and archaeological sites, creating a complex and evolving landscape whose character shifts with each season.",
    rating: 4.7,
    reviews: 34600,
    fee: "$30/vehicle",
    bestTime: "May–October",
    duration: "2–5 days",
    activities: ["Boating", "Slot Canyon Tours", "Hiking", "Swimming", "Photography"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "../shared/images/glen-canyon.jpg",
    tags: ["Lake Powell", "Slot Canyons", "Antelope Canyon", "Utah", "Boating"],
    lodgingCost: "$$",
    travelTime: { nyc: 8, chi: 7, la: 4.5, bay: 5 }
  },

  {
    id: 138,
    name: "Lake Mead National Recreation Area",
    slug: "lake-mead",
    state: "Nevada / Arizona",
    region: "Southwest",
    category: "National Recreation Area",
    description: "Straddling the Nevada-Arizona border just 30 miles from Las Vegas, Lake Mead is the largest reservoir in the United States by volume when full—formed by Hoover Dam on the Colorado River, one of the engineering marvels of the 20th century. The recreation area offers swimming, boating, and fishing on turquoise desert waters, while the historic Hoover Dam itself draws over one million visitors annually to marvel at its art deco architecture and staggering scale. The surrounding Mojave Desert harbors desert bighorn sheep, golden eagles, and the threatened desert tortoise in an ecosystem surprisingly rich given the surrounding urban sprawl.",
    rating: 4.5,
    reviews: 42100,
    fee: "$25/vehicle",
    bestTime: "October–May",
    duration: "1–3 days",
    activities: ["Boating", "Swimming", "Fishing", "Hoover Dam Tour", "Hiking"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/lake-mead.jpg",
    tags: ["Lake", "Hoover Dam", "Nevada", "Desert", "Water Sports"],
    lodgingCost: "$$",
    travelTime: { nyc: 6.5, chi: 5, la: 2.5, bay: 3 }
  },

  {
    id: 139,
    name: "Whiskeytown National Recreation Area",
    slug: "whiskeytown",
    state: "California",
    region: "Pacific West",
    category: "National Recreation Area",
    description: "Tucked in the foothills of the Trinity Alps in Northern California, Whiskeytown is a hidden gem surrounding a clear blue reservoir ringed by forested mountains—a startlingly beautiful setting just 8 miles west of Redding. The park's 39 miles of trails lead to four major waterfalls including Whiskeytown Falls, a 220-foot plunge hidden in a shaded canyon whose existence was unknown to park officials until 2004. The El Dorado Mine and Camden House offer gold rush history, while the reservoir draws swimmers, kayakers, and stand-up paddleboarders against a backdrop of Mount Shasta rising snow-capped on the northern horizon.",
    rating: 4.6,
    reviews: 11800,
    fee: "$15/vehicle",
    bestTime: "May–October",
    duration: "1–2 days",
    activities: ["Swimming", "Kayaking", "Hiking", "Waterfall Viewing", "Gold Panning"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "../shared/images/whiskeytown.jpg",
    tags: ["California", "Lake", "Waterfalls", "Gold Rush", "Hidden Gem"],
    lodgingCost: "$",
    travelTime: { nyc: 8.5, chi: 7, la: 4.5, bay: 4 }
  },

  {
    id: 140,
    name: "Delaware Water Gap National Recreation Area",
    slug: "delaware-water-gap",
    state: "New Jersey / Pennsylvania",
    region: "Northeast",
    category: "National Recreation Area",
    description: "Where the Delaware River cuts through the Kittatinny Ridge of the Appalachian Mountains in a 70,000-acre stretch of forested river valley, Delaware Water Gap National Recreation Area offers remarkable wilderness just 70 miles from New York City. The Appalachian Trail follows Kittatinny Ridge through the park for 27 miles with sweeping valley views; below, the Delaware River provides 40 miles of canoe and kayak paddling through one of the last free-flowing stretches of major river in the northeastern United States. Dingmans Falls—at 130 feet, one of the tallest waterfalls in Pennsylvania—plunges through a hemlock forest accessible by boardwalk.",
    rating: 4.6,
    reviews: 19200,
    fee: "Free",
    bestTime: "May–October",
    duration: "1–2 days",
    activities: ["Canoeing", "Hiking", "Swimming", "Waterfall Viewing", "Cycling"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "../shared/images/delaware-water-gap.jpg",
    tags: ["Delaware River", "Northeast", "Appalachian Trail", "Paddling", "Waterfalls"],
    lodgingCost: "$",
    travelTime: { nyc: 1.5, chi: 3.5, la: 7, bay: 7.5 }
  },

  {
    id: 141,
    name: "Curecanti National Recreation Area",
    slug: "curecanti",
    state: "Colorado",
    region: "Rocky Mountains",
    category: "National Recreation Area",
    description: "A series of three reservoirs on the Gunnison River in the heart of the Colorado Rockies, Curecanti is best known for its dramatic Blue Mesa Reservoir—the largest body of water in Colorado—whose deep blue waters contrast magnificently with the surrounding sagebrush mesas and volcanic Black Canyon cliffs. Kokanee salmon were introduced to Blue Mesa in the 1960s and now support a trophy fishery that draws anglers from across the region. Elk Mesa Overlook and the Morrow Point Boat Tour—a scenic ferry through a spectacular canyon accessible only by water—are among the park's most memorable experiences.",
    rating: 4.6,
    reviews: 9400,
    fee: "$20/vehicle",
    bestTime: "May–October",
    duration: "1–2 days",
    activities: ["Fishing", "Boating", "Hiking", "Wildlife Watching", "Boat Tours"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/curecanti.jpg",
    tags: ["Colorado", "Reservoir", "Fishing", "Gunnison River", "Scenic"],
    lodgingCost: "$",
    travelTime: { nyc: 6, chi: 4.5, la: 4.5, bay: 4.5 }
  },

  {
    id: 142,
    name: "Flaming Gorge National Recreation Area",
    slug: "flaming-gorge",
    state: "Utah / Wyoming",
    region: "Rocky Mountains",
    category: "National Recreation Area",
    description: "Where Flaming Gorge Reservoir fills a dramatic red-walled canyon carved by the Green River through the Uinta Mountains, this recreation area delivers some of the most spectacular desert-canyon-lake scenery in the American West. Explorer John Wesley Powell named Flaming Gorge on his 1869 Colorado River expedition for the brilliant crimson cliffs that glow like fire at sunrise and sunset. The 91-mile reservoir is renowned for world-class trout and kokanee salmon fishing, while the Red Canyon overlooks offer vertiginous views 1,360 feet above the water to where osprey and golden eagles soar below the rim.",
    rating: 4.7,
    reviews: 14200,
    fee: "$15/vehicle",
    bestTime: "May–September",
    duration: "1–3 days",
    activities: ["Fishing", "Boating", "Hiking", "Scenic Driving", "Wildlife Watching"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "../shared/images/flaming-gorge.jpg",
    tags: ["Utah", "Reservoir", "Red Cliffs", "Fishing", "Scenic"],
    lodgingCost: "$",
    travelTime: { nyc: 7, chi: 5.5, la: 5, bay: 5 }
  },

  {
    id: 143,
    name: "Chattahoochee River National Recreation Area",
    slug: "chattahoochee-river",
    state: "Georgia",
    region: "Southeast",
    category: "National Recreation Area",
    description: "One of the most visited units of the national park system, Chattahoochee River National Recreation Area strings together 48 miles of protected river corridor north of Atlanta, offering urban dwellers world-class whitewater tubing, kayaking, and trout fishing within minutes of one of the South's largest cities. The cold, clear tailwaters released from Buford Dam maintain temperatures that support a thriving brown and rainbow trout fishery year-round—an extraordinary resource in the Deep South. Interpretive programs along the river tell the story of the Creek and Cherokee peoples who called this river corridor home for thousands of years.",
    rating: 4.5,
    reviews: 24800,
    fee: "$5/vehicle",
    bestTime: "April–October",
    duration: "Half day–1 day",
    activities: ["Tubing", "Fishing", "Hiking", "Kayaking", "Picnicking"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/chattahoochee-river.jpg",
    tags: ["River", "Atlanta", "Urban Park", "Tubing", "Trout Fishing"],
    lodgingCost: "$",
    travelTime: { nyc: 3.5, chi: 3, la: 5, bay: 5.5 }
  },

  {
    id: 144,
    name: "Lake Roosevelt National Recreation Area",
    slug: "lake-roosevelt",
    state: "Washington",
    region: "Pacific West",
    category: "National Recreation Area",
    description: "Franklin D. Roosevelt Lake stretches 150 miles across the Columbia River Plateau behind Grand Coulee Dam, the largest hydroelectric facility in the United States, cutting through a landscape of basalt coulees and ponderosa pine forest in northeastern Washington. The recreation area's 600 miles of shoreline include dozens of free campgrounds accessible only by boat, creating a water-based camping experience of extraordinary solitude. Fort Spokane and St. Paul's Mission preserve Indigenous history and early American settlement in the inland Northwest, and the dam itself—visited by more people than the Grand Canyon in the 1930s—remains an awe-inspiring monument to New Deal ambition.",
    rating: 4.5,
    reviews: 9800,
    fee: "Free",
    bestTime: "June–September",
    duration: "2–5 days",
    activities: ["Boating", "Camping", "Fishing", "Swimming", "Historic Sites"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/lake-roosevelt.jpg",
    tags: ["Washington", "Lake", "Grand Coulee Dam", "Boating", "Remote Camping"],
    lodgingCost: "$",
    travelTime: { nyc: 8.5, chi: 6.5, la: 5.5, bay: 5.5 }
  },

  {
    id: 145,
    name: "Gateway National Recreation Area",
    slug: "gateway-nra",
    state: "New York / New Jersey",
    region: "Northeast",
    category: "National Recreation Area",
    description: "Gateway is one of the most visited national park units in the country, wrapping the entrance to New York Harbor across three units—Jamaica Bay, Staten Island, and Sandy Hook—and offering beaches, wildlife refuges, and historic military forts just minutes from one of the world's most densely populated urban areas. Sandy Hook's pristine barrier beach was the first federally operated public beach in the country, while Jamaica Bay Wildlife Refuge attracts hundreds of bird species on the Atlantic Flyway and inspired the modern migratory bird conservation movement. Historic fortifications from the Revolutionary War through World War II dot the shoreline, adding layers of American military history to a remarkable natural landscape.",
    rating: 4.4,
    reviews: 21600,
    fee: "Free ($30 parking at beaches)",
    bestTime: "June–September",
    duration: "Half day–1 day",
    activities: ["Beach", "Birdwatching", "Historic Forts", "Cycling", "Swimming"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/gateway-nra.jpg",
    tags: ["New York", "Urban Park", "Beach", "Wildlife Refuge", "Historic Forts"],
    lodgingCost: "$$",
    travelTime: { nyc: 0.5, chi: 3, la: 6.5, bay: 7 }
  },

  {
    id: 146,
    name: "Santa Monica Mountains National Recreation Area",
    slug: "santa-monica-mountains",
    state: "California",
    region: "Pacific West",
    category: "National Recreation Area",
    description: "The Santa Monica Mountains NRA is the world's largest urban national park, protecting 153,000 acres of the only Mediterranean ecosystem in the U.S. national park system—a chaparral-covered mountain range stretching from Griffith Park in Los Angeles to Point Mugu on the Pacific coast. Malibu Creek State Park, Solstice Canyon with its waterfall and ruins, and the Backbone Trail's 67-mile ridgeline route through MASH filming locations and celebrity canyon estates offer extraordinary wilderness within one of the world's largest metropolitan areas. Mountain lions, bobcats, and mule deer navigate habitat corridors between the mountains and the sea, making the park a living laboratory for urban wildlife conservation.",
    rating: 4.6,
    reviews: 31400,
    fee: "Free (some day-use fees)",
    bestTime: "October–June",
    duration: "Half day–2 days",
    activities: ["Hiking", "Cycling", "Horseback Riding", "Swimming", "Photography"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "../shared/images/santa-monica-mountains.jpg",
    tags: ["Los Angeles", "Urban Park", "Mediterranean", "Mountain Lions", "Coastal"],
    lodgingCost: "$$$",
    travelTime: { nyc: 6, chi: 4.5, la: 0.5, bay: 2 }
  },

  // ─────────────────────────────────────────────────────────────
  // SECTION 5: TOP NATIONAL HISTORIC SITES (IDs 147–156)
  // ─────────────────────────────────────────────────────────────

  {
    id: 147,
    name: "Martin Luther King Jr. National Historical Park",
    slug: "martin-luther-king-jr",
    state: "Georgia",
    region: "Southeast",
    category: "Historic Site",
    description: "In Atlanta's Sweet Auburn neighborhood, this national historical park preserves the birthplace, church, and burial site of the Reverend Dr. Martin Luther King Jr.—the most celebrated leader of the American civil rights movement and recipient of the 1964 Nobel Peace Prize. The shotgun-style Victorian home where King was born in 1929, Ebenezer Baptist Church where he preached alongside his father, and the flame-flanked reflecting pool above his tomb create a circuit of profound emotional power. The Freedom Hall complex interprets the arc of the civil rights movement, contextualizing King's life within the broader struggle for racial justice that transformed America.",
    rating: 4.8,
    reviews: 21400,
    fee: "Free",
    bestTime: "Year-round",
    duration: "Half day",
    activities: ["Guided Tours", "Historic Sites", "Photography", "History Education", "Ranger Programs"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/martin-luther-king-jr.jpg",
    tags: ["Civil Rights", "Atlanta", "American History", "MLK", "Free"],
    lodgingCost: "$$",
    travelTime: { nyc: 3.5, chi: 3, la: 5.5, bay: 6 }
  },

  {
    id: 148,
    name: "Harpers Ferry National Historical Park",
    slug: "harpers-ferry",
    state: "West Virginia",
    region: "Southeast",
    category: "Historic Site",
    description: "At the dramatic confluence of the Potomac and Shenandoah Rivers, Harpers Ferry is one of the most scenically situated historic sites in America—Thomas Jefferson called the view here 'perhaps one of the most stupendous scenes in Nature.' John Brown's 1859 raid on the federal armory here, intended to spark a slave rebellion, became a catalytic event leading directly to the Civil War. The historic lower town, restored to its 1859 appearance, immerses visitors in three centuries of American history—from the Revolutionary War through the Civil War and the establishment of Storer College, one of the nation's first schools for freed slaves.",
    rating: 4.7,
    reviews: 16800,
    fee: "$20/vehicle",
    bestTime: "April–November",
    duration: "Half day–1 day",
    activities: ["Historic Tours", "Hiking", "Photography", "History Education", "Rafting"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "../shared/images/harpers-ferry.jpg",
    tags: ["Civil War", "John Brown", "West Virginia", "Rivers", "History"],
    lodgingCost: "$",
    travelTime: { nyc: 3, chi: 3.5, la: 6, bay: 6.5 }
  },

  {
    id: 149,
    name: "Minute Man National Historical Park",
    slug: "minute-man",
    state: "Massachusetts",
    region: "Northeast",
    category: "Historic Site",
    description: "On April 19, 1775, the first shots of the American Revolution rang out along the 22-mile Battle Road between Concord and Lexington—and Minute Man National Historical Park preserves the landscape where colonists stood against British Regulars and lit what Emerson called 'the shot heard round the world.' The North Bridge in Concord, where the first British regulars fell, stands in the exact location of that pivotal confrontation, while the Battle Road Trail connects the engagement sites through a remarkably intact 18th-century agricultural landscape. The park also honors the literary legacy of Concord—home of Thoreau, Emerson, Hawthorne, and the Alcotts.",
    rating: 4.7,
    reviews: 18200,
    fee: "Free",
    bestTime: "April–October",
    duration: "Half day–1 day",
    activities: ["Hiking", "History Education", "Cycling", "Photography", "Ranger Programs"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/minute-man.jpg",
    tags: ["American Revolution", "Massachusetts", "Concord", "Lexington", "History"],
    lodgingCost: "$$",
    travelTime: { nyc: 4, chi: 5, la: 10, bay: 10.5 }
  },

  {
    id: 150,
    name: "Boston National Historical Park",
    slug: "boston-nhp",
    state: "Massachusetts",
    region: "Northeast",
    category: "Historic Site",
    description: "The 2.5-mile Freedom Trail is the spine of Boston National Historical Park, threading through 16 Revolutionary-era sites including Paul Revere's House, the Old South Meeting House, Bunker Hill Monument, and the USS Constitution—'Old Ironsides'—the oldest commissioned naval vessel still afloat in the world. The park's sites are embedded in the living fabric of a vibrant modern city, creating a dynamic encounter with history where 18th-century buildings share blocks with Boston's Italian North End bakeries and Irish pubs. Ranger programs at Faneuil Hall, where Samuel Adams roused colonists to revolution, bring the founding era vividly to life.",
    rating: 4.7,
    reviews: 31600,
    fee: "Free (Bunker Hill Monument $3; USS Constitution free)",
    bestTime: "April–October",
    duration: "1 day",
    activities: ["Walking Tours", "History Education", "Museum Visits", "Photography", "USS Constitution Tour"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/boston-nhp.jpg",
    tags: ["American Revolution", "Freedom Trail", "Boston", "USS Constitution", "History"],
    lodgingCost: "$$$",
    travelTime: { nyc: 4, chi: 5, la: 10, bay: 10.5 }
  },

  {
    id: 151,
    name: "Abraham Lincoln Birthplace National Historical Park",
    slug: "abraham-lincoln-birthplace",
    state: "Kentucky",
    region: "Southeast",
    category: "Historic Site",
    description: "In the gently rolling knob country of central Kentucky, this national historical park preserves the farm where Abraham Lincoln was born on February 12, 1809—a log cabin symbolic of the frontier origins of America's 16th president and most revered national figure. The Memorial Building, a neoclassical granite structure completed in 1911, houses a symbolic log cabin of the period; 56 steps lead to its entrance, one for each year of Lincoln's life. The nearby Knob Creek Farm, where Lincoln spent his earliest childhood years, is preserved as a second unit of the park just a few miles away.",
    rating: 4.6,
    reviews: 14200,
    fee: "Free",
    bestTime: "Year-round",
    duration: "Half day",
    activities: ["Guided Tours", "History Education", "Photography", "Nature Walks", "Visitor Center"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/abraham-lincoln-birthplace.jpg",
    tags: ["Lincoln", "Kentucky", "American History", "Log Cabin", "Presidents"],
    lodgingCost: "$",
    travelTime: { nyc: 4, chi: 2.5, la: 5.5, bay: 6 }
  },

  {
    id: 152,
    name: "Tuskegee Airmen National Historic Site",
    slug: "tuskegee-airmen",
    state: "Alabama",
    region: "Southeast",
    category: "Historic Site",
    description: "Moton Field in Tuskegee, Alabama is where the first African American military aviators in U.S. history—the legendary Tuskegee Airmen—trained, flew, and proved definitively that Black Americans were equal to any challenge the nation could present. The Tuskegee Airmen compiled a distinguished combat record during World War II, flying over 1,500 missions and earning more than 150 Distinguished Flying Crosses, directly challenging segregation in the military. The restored hangars, control tower, and aircraft at Moton Field tell an essential American story of courage, skill, and perseverance in the face of systemic discrimination.",
    rating: 4.7,
    reviews: 9600,
    fee: "Free",
    bestTime: "Year-round",
    duration: "Half day",
    activities: ["Museum Tours", "Historic Hangars", "Photography", "History Education", "Flight Demonstrations"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/tuskegee-airmen.jpg",
    tags: ["African American History", "WWII", "Aviation", "Alabama", "Civil Rights"],
    lodgingCost: "$",
    travelTime: { nyc: 4, chi: 3, la: 5, bay: 5.5 }
  },

  {
    id: 153,
    name: "Manzanar National Historic Site",
    slug: "manzanar",
    state: "California",
    region: "Pacific West",
    category: "Historic Site",
    description: "At the base of the eastern Sierra Nevada in the Owens Valley, Manzanar preserves the site of one of ten War Relocation Authority camps where the U.S. government forcibly incarcerated 120,000 Japanese Americans following the attack on Pearl Harbor during World War II. The interpretive center, housed in the restored camp auditorium, presents an unflinching account of this chapter in American history through the voices and photographs of those who lived it. A self-guided driving tour connects reconstructed guard towers, barracks, and the cemetery monument—a place of quiet reflection on constitutional rights, racism, and the resilience of community.",
    rating: 4.7,
    reviews: 12800,
    fee: "Free",
    bestTime: "March–November",
    duration: "Half day–1 day",
    activities: ["Museum Tours", "Self-Guided Driving Tour", "Photography", "History Education", "Ranger Programs"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/manzanar.jpg",
    tags: ["Japanese American Incarceration", "WWII", "California", "Civil Rights", "History"],
    lodgingCost: "$",
    travelTime: { nyc: 7, chi: 5.5, la: 3, bay: 3.5 }
  },

  {
    id: 154,
    name: "Ford's Theatre National Historic Site",
    slug: "fords-theatre",
    state: "District of Columbia",
    region: "Northeast",
    category: "Historic Site",
    description: "On the evening of April 14, 1865—just days after the Civil War effectively ended—President Abraham Lincoln was shot by John Wilkes Booth in the presidential box of Ford's Theatre, changing the course of American history. The fully restored theater continues to operate as both an active performance venue and a historic site, where visitors can stand in the presidential box and view Booth's derringer pistol and Lincoln's blood-stained clothes in the adjacent museum. The Petersen House across the street, where Lincoln died the following morning, offers the final, somber chapter of the visit.",
    rating: 4.8,
    reviews: 28400,
    fee: "$4/person",
    bestTime: "Year-round",
    duration: "Half day",
    activities: ["Guided Tours", "Museum", "Theater Performances", "History Education", "Photography"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/fords-theatre.jpg",
    tags: ["Lincoln", "Assassination", "Washington DC", "History", "Theater"],
    lodgingCost: "$$$",
    travelTime: { nyc: 2.5, chi: 2.5, la: 6, bay: 6.5 }
  },

  {
    id: 155,
    name: "San Antonio Missions National Historical Park",
    slug: "san-antonio-missions",
    state: "Texas",
    region: "Southwest",
    category: "Historic Site",
    description: "San Antonio Missions preserves four Spanish colonial missions—Mission Concepción, Mission San José, Mission San Juan, and Mission Espada—built in the 18th century along the San Antonio River to convert Indigenous peoples of the region to Christianity and Spanish colonial culture. Mission San José, 'Queen of the Missions,' is the largest and most complete, featuring a fully restored limestone church, ornate Spanish Baroque Rose Window, and reconstructed granary. All four missions are part of the San Antonio Missions UNESCO World Heritage Site (along with the Alamo), and many are still active parishes with weekly Mass services celebrated in their 300-year-old churches.",
    rating: 4.7,
    reviews: 22600,
    fee: "Free",
    bestTime: "Year-round",
    duration: "Half day–1 day",
    activities: ["Guided Tours", "Cycling Trail", "Photography", "History Education", "Church Visits"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/san-antonio-missions.jpg",
    tags: ["Spanish Colonial", "Texas", "UNESCO", "Missions", "History"],
    lodgingCost: "$$",
    travelTime: { nyc: 5, chi: 3.5, la: 4, bay: 4.5 }
  },

  {
    id: 156,
    name: "Salem Maritime National Historic Site",
    slug: "salem-maritime",
    state: "Massachusetts",
    region: "Northeast",
    category: "Historic Site",
    description: "Salem's Derby Street waterfront preserves the historic core of one of early America's most prosperous seaports, where merchant ships returned laden with spices, silks, and exotic goods from Asia, the Pacific, and Africa in the late 18th and early 19th centuries. The Custom House—where Nathaniel Hawthorne worked as a surveyor and found the source material for The Scarlet Letter—anchors a district of restored counting houses, warehouses, and wharves. The tall ship Friendship of Salem, a full-scale replica of an 1797 East Indiaman, offers deck tours and occasional educational sails, while the park's proximity to the Salem Witch Museum makes this New England's most historically layered coastal town.",
    rating: 4.6,
    reviews: 14600,
    fee: "Free",
    bestTime: "June–October",
    duration: "Half day",
    activities: ["Historic Tours", "Ship Tours", "Photography", "History Education", "Whale Watching"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/salem-maritime.jpg",
    tags: ["Maritime History", "Massachusetts", "Salem", "Tall Ships", "Colonial"],
    lodgingCost: "$$",
    travelTime: { nyc: 4, chi: 5.5, la: 10.5, bay: 11 }
  },

  // ─────────────────────────────────────────────────────────────
  // SECTION 6: ADDITIONAL NOTABLE NPS UNITS (IDs 157–160)
  // ─────────────────────────────────────────────────────────────

  {
    id: 157,
    name: "National Mall and Memorial Parks",
    slug: "national-mall",
    state: "District of Columbia",
    region: "Northeast",
    category: "National Monument",
    description: "The 2-mile green corridor stretching from the Capitol to the Lincoln Memorial is America's front yard and the greatest concentration of national monuments and memorials in the world—the Washington Monument, the Lincoln, Jefferson, FDR, Martin Luther King Jr., and World War II memorials are all here, plus the Vietnam Veterans Memorial Wall bearing 58,000 names and the Korean War Veterans Memorial. Free summer concerts, the Smithsonian Museums that line its flanks, and the annual Fourth of July fireworks draw tens of millions of visitors each year to the symbolic heart of American democracy. The Reflecting Pool at dawn, mist rising as joggers circle its edge and the Washington Monument mirror perfect on its surface, is one of the defining images of American civic life.",
    rating: 4.9,
    reviews: 124000,
    fee: "Free",
    bestTime: "March–June, September–November",
    duration: "1–2 days",
    activities: ["Memorials", "Museum Visits", "Walking Tours", "Photography", "Events"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/national-mall.jpg",
    tags: ["Washington DC", "Memorials", "American History", "Monuments", "Free"],
    lodgingCost: "$$$",
    travelTime: { nyc: 2.5, chi: 2.5, la: 6, bay: 6.5 }
  },

  {
    id: 158,
    name: "Antietam National Battlefield",
    slug: "antietam",
    state: "Maryland",
    region: "Northeast",
    category: "Historic Site",
    description: "September 17, 1862, was the bloodiest single day in American military history: over 22,700 soldiers were killed, wounded, or missing in 12 hours of savage fighting along Antietam Creek in western Maryland. The battlefield is among the best-preserved in the country—a pastoral landscape of cornfields, sunken roads, and stone bridges where the tactical movements of the day can be traced on foot or by car in haunting intimacy. Lincoln's visit to the battlefield five days after the fight prompted him to issue the preliminary Emancipation Proclamation, making Antietam one of the most consequential pieces of ground in American history.",
    rating: 4.8,
    reviews: 19800,
    fee: "$20/vehicle",
    bestTime: "April–November",
    duration: "Half day–1 day",
    activities: ["Auto Tours", "Hiking", "History Education", "Photography", "Ranger Programs"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/antietam.jpg",
    tags: ["Civil War", "Battlefield", "Maryland", "Emancipation Proclamation", "History"],
    lodgingCost: "$",
    travelTime: { nyc: 3, chi: 3, la: 6, bay: 6.5 }
  },

  {
    id: 159,
    name: "Mammoth Cave National Park",
    slug: "mammoth-cave",
    state: "Kentucky",
    region: "Southeast",
    category: "National Park",
    description: "With over 426 miles of surveyed passageways, Mammoth Cave is the world's longest known cave system—and explorers continue to add miles each year as new connections are discovered between previously separate cave systems beneath the Kentucky karst. Ranger-led tours range from a 30-minute Historic Tour of the main cavern (where early visitors left smoke signatures from candle tours in the 1800s) to the strenuous five-hour Wild Cave Tour through tight crawlways. Above ground, the Green River winds through a UNESCO World Heritage Site biosphere reserve rich in aquatic life, including 130 species of fish and the highest concentration of endemic aquatic species of any cave system in the world.",
    rating: 4.7,
    reviews: 26400,
    fee: "$25/vehicle (cave tours extra)",
    bestTime: "Year-round (55°F underground)",
    duration: "1–2 days",
    activities: ["Cave Tours", "Hiking", "Canoeing", "Wildlife Watching", "Spelunking"],
    difficulty: "Easy to Strenuous",
    accessibility: true,
    image: "../shared/images/mammoth-cave.jpg",
    tags: ["World's Longest Cave", "Kentucky", "Underground", "UNESCO", "Speleothems"],
    lodgingCost: "$",
    travelTime: { nyc: 4, chi: 2, la: 5.5, bay: 6 }
  },

  {
    id: 160,
    name: "Natchez Trace Parkway",
    slug: "natchez-trace-parkway",
    state: "Mississippi / Alabama / Tennessee",
    region: "Southeast",
    category: "National Recreation Area",
    description: "The 444-mile Natchez Trace Parkway follows the path of one of North America's most historic roads, tracing a route used for centuries by Choctaw and Chickasaw peoples, colonial traders, and figures as varied as Meriwether Lewis and Andrew Jackson through the piney woods and cypress swamps of the Deep South. The parkway is managed as a scenic road with no commercial traffic, allowing cyclists and motorcyclists to travel in peace through a corridor of hardwood forests, antebellum plantation ruins, Civil War sites, and Native American mounds. Meriwether Lewis's mysterious death site, the Ross Barnett Reservoir overlook, and the Double Arch Bridge—the first segmental concrete arch bridge built in the United States—are highlights of a drive rich with American stories.",
    rating: 4.7,
    reviews: 16800,
    fee: "Free",
    bestTime: "March–May, September–November",
    duration: "1–3 days",
    activities: ["Scenic Driving", "Cycling", "Hiking", "History Education", "Birdwatching"],
    difficulty: "Easy",
    accessibility: true,
    image: "../shared/images/natchez-trace-parkway.jpg",
    tags: ["Scenic Byway", "Deep South", "History", "Cycling", "Native American"],
    lodgingCost: "$",
    travelTime: { nyc: 4, chi: 3, la: 4.5, bay: 5.5 }
  }

];
