// U.S. Tourist Attractions — Page 3 (IDs 51–75)
// National Monuments, Historic Sites, Cultural Sites, and Landmarks

const attractionsPage3 = [
  {
    id: 51,
    name: "Mount Rushmore National Memorial",
    slug: "mount-rushmore-sd",
    state: "South Dakota",
    region: "Great Plains",
    category: "Historic Site",
    description: "Carved into the granite face of the Black Hills, Mount Rushmore features the 60-foot-tall portraits of Presidents Washington, Jefferson, Roosevelt, and Lincoln—a monumental achievement of American ambition completed between 1927 and 1941. The Avenue of Flags leads visitors to the Grand View Terrace, where the faces emerge dramatically from the forested ridgeline. A nightly illumination ceremony brings the memorial to glowing life after dark.",
    rating: 4.7,
    reviews: 38420,
    fee: "$10/vehicle",
    bestTime: "May–September",
    duration: "Half day",
    activities: ["Sightseeing", "Photography", "Ranger Programs", "Hiking", "Visitor Center"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/mount-rushmore-sd/800/450",
    tags: ["Presidents", "Sculpture", "American History", "Iconic"]
  },
  {
    id: 52,
    name: "Crazy Horse Memorial",
    slug: "crazy-horse-memorial-sd",
    state: "South Dakota",
    region: "Great Plains",
    category: "Historic Site",
    description: "The world's largest mountain carving in progress, Crazy Horse Memorial honors the legendary Oglala Lakota leader and the spirit of the North American Indian people. Sculptor Korczak Ziolkowski began blasting the Black Hills granite in 1948, and the work continues today—the completed face alone is taller than the faces at Mount Rushmore. The Indian Museum of North America and Native American Cultural Center make this as much an education experience as a scenic wonder.",
    rating: 4.6,
    reviews: 18750,
    fee: "$16/person",
    bestTime: "May–October",
    duration: "Half day",
    activities: ["Sightseeing", "Photography", "Museum", "Cultural Programs", "Night Blasts"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/crazy-horse-memorial-sd/800/450",
    tags: ["Native American", "Sculpture", "History", "Mountain Carving"]
  },
  {
    id: 53,
    name: "Gateway Arch National Monument",
    slug: "gateway-arch-mo",
    state: "Missouri",
    region: "Great Plains",
    category: "National Monument",
    description: "Soaring 630 feet above the western bank of the Mississippi River, the Gateway Arch is the tallest man-made monument in the United States and a gleaming symbol of westward expansion. Visitors can ride tram pods to the observation deck at the top for sweeping views of St. Louis and the river below. The underground Museum at the Gateway Arch tells the story of Thomas Jefferson's Louisiana Purchase and the pioneers who followed.",
    rating: 4.7,
    reviews: 29640,
    fee: "$3/person (tram $15/adult)",
    bestTime: "April–October",
    duration: "Half day",
    activities: ["Sightseeing", "Tram Ride", "Museum", "Photography", "Riverboat Tours"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/gateway-arch-mo/800/450",
    tags: ["Architecture", "American History", "Urban", "Iconic Landmark"]
  },
  {
    id: 54,
    name: "Independence Hall",
    slug: "independence-hall-pa",
    state: "Pennsylvania",
    region: "Northeast",
    category: "Historic Site",
    description: "Independence Hall is the birthplace of American democracy—the red-brick Georgian building where the Declaration of Independence was adopted in 1776 and the U.S. Constitution was drafted in 1787. Ranger-led tours guide visitors through the Assembly Room, where delegates debated the very foundations of the nation. As a UNESCO World Heritage Site, it stands as a global symbol of liberty and self-governance.",
    rating: 4.8,
    reviews: 22180,
    fee: "Free (timed-entry ticket required)",
    bestTime: "April–June, September–November",
    duration: "Half day",
    activities: ["Guided Tours", "Sightseeing", "Photography", "History Education", "Walking Tours"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/independence-hall-pa/800/450",
    tags: ["American History", "UNESCO", "Founding Documents", "Philadelphia"]
  },
  {
    id: 55,
    name: "Liberty Bell Center",
    slug: "liberty-bell-center-pa",
    state: "Pennsylvania",
    region: "Northeast",
    category: "Historic Site",
    description: "The Liberty Bell, with its famous crack and inscription from Leviticus, has been an enduring symbol of freedom and civil rights since it rang to call colonists to hear the first reading of the Declaration of Independence. The glassed-in pavilion frames the bell against the backdrop of Independence Hall across the street, creating one of America's most photographed views. Exhibits trace the bell's journey from colonial symbol to an icon embraced by abolitionists, suffragists, and civil rights leaders.",
    rating: 4.7,
    reviews: 19850,
    fee: "Free",
    bestTime: "April–June, September–November",
    duration: "Half day",
    activities: ["Sightseeing", "Photography", "Museum Exhibits", "History Education", "Walking Tours"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/liberty-bell-pa/800/450",
    tags: ["American History", "Freedom", "Philadelphia", "Iconic Symbol"]
  },
  {
    id: 56,
    name: "Ellis Island National Museum of Immigration",
    slug: "ellis-island-ny",
    state: "New York",
    region: "Northeast",
    category: "Historic Site",
    description: "Between 1892 and 1954, more than 12 million immigrants passed through the Great Hall of Ellis Island in search of a new life in America, making it the most visited immigration station in U.S. history. The beautifully restored Beaux-Arts main building now houses a world-class museum where visitors can trace ancestors through digitized records and walk the very halls their forebears once nervously awaited inspection. Accessible only by ferry from Battery Park, the island offers striking views of the Statue of Liberty across the harbor.",
    rating: 4.8,
    reviews: 31200,
    fee: "$24/adult (ferry + museum)",
    bestTime: "April–October",
    duration: "1 day",
    activities: ["Museum", "Genealogy Research", "Guided Tours", "Photography", "Ferry Ride"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/ellis-island-ny/800/450",
    tags: ["Immigration", "American History", "Museum", "NYC"]
  },
  {
    id: 57,
    name: "Gettysburg National Military Park",
    slug: "gettysburg-nmp-pa",
    state: "Pennsylvania",
    region: "Northeast",
    category: "Historic Site",
    description: "The three-day Battle of Gettysburg in July 1863 was the bloodiest engagement of the Civil War, and the hallowed fields, ridges, and peach orchards where it unfolded are preserved in haunting detail. Over 1,300 monuments and markers dot the 6,000-acre battlefield, and the Gettysburg Address—delivered by Lincoln four months after the battle—still resonates from Little Round Top to Cemetery Ridge. The museum and cyclorama bring the immense scale of the conflict vividly to life.",
    rating: 4.8,
    reviews: 24560,
    fee: "$15/adult (museum); battlefield free",
    bestTime: "April–October",
    duration: "1-2 days",
    activities: ["Auto Tours", "Guided Battlefield Tours", "Hiking", "Museum", "Photography"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "https://picsum.photos/seed/gettysburg-nmp-pa/800/450",
    tags: ["Civil War", "American History", "Battlefield", "Lincoln"]
  },
  {
    id: 58,
    name: "Little Bighorn Battlefield National Monument",
    slug: "little-bighorn-battlefield-mt",
    state: "Montana",
    region: "Rocky Mountains",
    category: "National Monument",
    description: "On June 25–26, 1876, Lt. Col. George Armstrong Custer and the 7th Cavalry suffered a catastrophic defeat at the hands of Lakota Sioux and Northern Cheyenne warriors led by Crazy Horse and Sitting Bull—a battle that became the most famous clash of the American Indian Wars. White marble markers dot the rolling hills where soldiers fell, and the Indian Memorial honors the warriors who fought to preserve their way of life. Rangers tell both sides of this complex and deeply moving story.",
    rating: 4.6,
    reviews: 9870,
    fee: "$20/vehicle",
    bestTime: "May–September",
    duration: "Half day",
    activities: ["Ranger Programs", "Auto Tours", "Hiking", "Photography", "History Education"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/little-bighorn-battlefield-mt/800/450",
    tags: ["Native American", "American History", "Battlefield", "19th Century"]
  },
  {
    id: 59,
    name: "Chaco Culture National Historical Park",
    slug: "chaco-culture-nhp-nm",
    state: "New Mexico",
    region: "Southwest",
    category: "Historic Site",
    description: "Between 850 and 1150 CE, the Chacoan people constructed massive multi-storied stone great houses—including the extraordinary Pueblo Bonito with its 600-plus rooms—that served as ceremonial, astronomical, and trade centers for a vast road network spanning the Four Corners region. Chaco Canyon's remote high-desert setting preserves both the ancient architecture and some of the darkest night skies in the American West. Its sophisticated solar and lunar alignments have earned it recognition as a UNESCO World Heritage Site.",
    rating: 4.7,
    reviews: 7340,
    fee: "$25/vehicle",
    bestTime: "March–May, September–November",
    duration: "1-2 days",
    activities: ["Archaeology Tours", "Hiking", "Stargazing", "Photography", "Ranger Programs"],
    difficulty: "Easy to Moderate",
    accessibility: false,
    image: "https://picsum.photos/seed/chaco-culture-nhp-nm/800/450",
    tags: ["Archaeology", "Native American", "UNESCO", "Ancestral Puebloans"]
  },
  {
    id: 60,
    name: "Devils Tower National Monument",
    slug: "devils-tower-wy",
    state: "Wyoming",
    region: "Rocky Mountains",
    category: "National Monument",
    description: "Rising 867 feet above the Belle Fourche River, Devils Tower is a stunning igneous monolith of vertically fluted columns that has been sacred to Northern Plains tribes for thousands of years and is America's first national monument, designated in 1906. Rock climbers from around the world come to test themselves on its sheer faces, while the Belle Fourche River loop trail circles the base through ponderosa pine forest populated with prairie dogs and deer. The tower achieves an almost otherworldly presence, especially at dawn when mist clings to the surrounding valley.",
    rating: 4.8,
    reviews: 14230,
    fee: "$25/vehicle",
    bestTime: "May–October",
    duration: "Half day",
    activities: ["Rock Climbing", "Hiking", "Photography", "Wildlife Watching", "Ranger Programs"],
    difficulty: "Easy to Strenuous",
    accessibility: true,
    image: "https://picsum.photos/seed/devils-tower-wy/800/450",
    tags: ["Geology", "Rock Climbing", "Native American Sacred Site", "Monolith"]
  },
  {
    id: 61,
    name: "Muir Woods National Monument",
    slug: "muir-woods-nm-ca",
    state: "California",
    region: "Pacific West",
    category: "National Monument",
    description: "Just 12 miles north of San Francisco's Golden Gate Bridge, Muir Woods shelters one of the last old-growth coastal redwood forests in the Bay Area, where giants over 1,000 years old soar 250 feet into a cathedral canopy. Redwood Creek winds through the valley floor, and the filtered light that pierces the fog-dampened groves creates an atmosphere of ancient, hushed majesty. Named for conservationist John Muir and designated a monument by Theodore Roosevelt in 1908, it is a living tribute to the American conservation movement.",
    rating: 4.8,
    reviews: 33580,
    fee: "$15/person",
    bestTime: "March–May, September–November",
    duration: "Half day",
    activities: ["Hiking", "Photography", "Nature Walks", "Birdwatching", "Ranger Programs"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/muir-woods-nm-ca/800/450",
    tags: ["Redwoods", "Old-Growth Forest", "Conservation", "Bay Area"]
  },
  {
    id: 62,
    name: "Golden Gate National Recreation Area",
    slug: "golden-gate-nra-ca",
    state: "California",
    region: "Pacific West",
    category: "National Recreation Area",
    description: "Stretching from the Marin Headlands to the San Francisco Peninsula, Golden Gate National Recreation Area is one of the most visited units of the National Park System, wrapping the iconic Golden Gate Bridge in a mosaic of rugged coastline, rolling hills, historic forts, and sandy beaches. Hawk Hill draws thousands of migrating raptors each fall, while the Lands End trail reveals hidden coves and shipwreck views above the crashing Pacific surf. Fort Point stands directly beneath the bridge's south tower, offering an unparalleled perspective on the engineering marvel above.",
    rating: 4.8,
    reviews: 42100,
    fee: "Free (some areas have parking fees)",
    bestTime: "April–October",
    duration: "1-2 days",
    activities: ["Hiking", "Cycling", "Photography", "Birdwatching", "Beach Visits"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "https://picsum.photos/seed/golden-gate-nra-ca/800/450",
    tags: ["Golden Gate Bridge", "Coastline", "Urban Parks", "San Francisco"]
  },
  {
    id: 63,
    name: "Alcatraz Island",
    slug: "alcatraz-island-ca",
    state: "California",
    region: "Pacific West",
    category: "Historic Site",
    description: "Sitting in the fog-swept waters of San Francisco Bay, Alcatraz served as a forbidding federal penitentiary from 1934 to 1963, housing notorious criminals including Al Capone and Robert 'Birdman' Stroud—no inmate ever successfully escaped its cold-water isolation. The self-guided audio tour, narrated by former guards and inmates, leads visitors through the cell block, exercise yard, and solitary confinement chambers with chilling intimacy. The island also offers sweeping views of the Bay Bridge and San Francisco skyline, and its rocky shores are home to nesting seabird colonies.",
    rating: 4.8,
    reviews: 47920,
    fee: "$44/adult (ferry + tour)",
    bestTime: "Year-round",
    duration: "Half day",
    activities: ["Audio Tours", "Photography", "History Education", "Birdwatching", "Scenic Views"],
    difficulty: "Moderate",
    accessibility: false,
    image: "https://picsum.photos/seed/alcatraz-island-ca/800/450",
    tags: ["Prison History", "San Francisco", "Island", "Crime History"]
  },
  {
    id: 64,
    name: "Monument Valley Navajo Tribal Park",
    slug: "monument-valley-navajo-az",
    state: "Arizona",
    region: "Southwest",
    category: "Tribal Park",
    description: "Rising from a vast rust-colored desert plain, the sandstone buttes and mesas of Monument Valley—The Mittens, Merrick Butte, and the iconic John Ford's Point—are among the most photographed landscapes on Earth, immortalized in countless Westerns and road-trip photographs. The Navajo Nation administers this 91,000-acre tribal park, and Navajo guides offer jeep tours that venture beyond the visitor loop into sacred areas rarely seen by outsiders. Dawn and dusk transform the towering formations into silhouettes of fiery copper against the vast Southwest sky.",
    rating: 4.9,
    reviews: 36870,
    fee: "$20/vehicle",
    bestTime: "March–May, September–November",
    duration: "1 day",
    activities: ["Scenic Driving", "Jeep Tours", "Photography", "Horseback Riding", "Guided Tours"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/monument-valley-navajo-az/800/450",
    tags: ["Desert", "Navajo Nation", "Buttes", "Iconic Landscape"]
  },
  {
    id: 65,
    name: "Rainbow Bridge National Monument",
    slug: "rainbow-bridge-nm-ut",
    state: "Utah",
    region: "Southwest",
    category: "National Monument",
    description: "Rainbow Bridge is the world's largest known natural bridge, spanning 275 feet across a canyon with a height of 290 feet—tall enough to encompass the U.S. Capitol beneath its arch. Sacred to Navajo, Hopi, San Juan Southern Paiute, and Ute Mountain peoples, the site lies within Glen Canyon National Recreation Area and is most easily reached by boat across Lake Powell. The salmon-pink sandstone arch frames an impossibly blue sky, making it one of the most spectacular geological wonders in the American Southwest.",
    rating: 4.7,
    reviews: 5820,
    fee: "$30/person (boat tour) or $6/person (hiking permit)",
    bestTime: "April–October",
    duration: "1 day",
    activities: ["Boat Tours", "Hiking", "Photography", "Sightseeing", "Cultural Interpretation"],
    difficulty: "Moderate",
    accessibility: false,
    image: "https://picsum.photos/seed/rainbow-bridge-nm-ut/800/450",
    tags: ["Natural Arch", "Native American Sacred Site", "Geology", "Lake Powell"]
  },
  {
    id: 66,
    name: "Natural Bridges National Monument",
    slug: "natural-bridges-nm-ut",
    state: "Utah",
    region: "Southwest",
    category: "National Monument",
    description: "Natural Bridges contains three of the world's largest natural bridges—Sipapu, Kachina, and Owachomo—carved by White Canyon's meandering stream through cream-colored Cedar Mesa Sandstone over millions of years. The 9-mile Bridge View Drive connects overlooks above each span, while a challenging trail links all three bridges in a rewarding backcountry loop through ancient Ancestral Puebloan ruins. Designated the world's first International Dark Sky Park in 2007, the monument offers extraordinary stargazing after dark.",
    rating: 4.7,
    reviews: 6430,
    fee: "$20/vehicle",
    bestTime: "March–May, September–November",
    duration: "1 day",
    activities: ["Hiking", "Scenic Driving", "Stargazing", "Photography", "Archaeology"],
    difficulty: "Moderate",
    accessibility: true,
    image: "https://picsum.photos/seed/natural-bridges-nm-ut/800/450",
    tags: ["Natural Arches", "Dark Sky", "Ancestral Puebloans", "Canyon Country"]
  },
  {
    id: 67,
    name: "Craters of the Moon National Monument",
    slug: "craters-of-the-moon-nm-id",
    state: "Idaho",
    region: "Rocky Mountains",
    category: "National Monument",
    description: "Craters of the Moon preserves one of the best-preserved and most geologically recent basaltic lava fields in the continental United States—a surreal black moonscape of cinder cones, lava tubes, spatter cones, and twisted pahoehoe flows stretching across 750,000 acres of the Snake River Plain. Visitors can descend into several lava tube caves, climb cinder cones for panoramic views over the alien terrain, and discover how wildflowers and limber pines stubbornly colonize the harshest of substrates. NASA astronauts trained here before the Apollo lunar missions.",
    rating: 4.6,
    reviews: 8910,
    fee: "$20/vehicle",
    bestTime: "May–September",
    duration: "1 day",
    activities: ["Cave Exploration", "Hiking", "Scenic Driving", "Photography", "Stargazing"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "https://picsum.photos/seed/craters-of-the-moon-nm-id/800/450",
    tags: ["Volcanic", "Geology", "Lava Tubes", "Unique Landscape"]
  },
  {
    id: 68,
    name: "Lava Beds National Monument",
    slug: "lava-beds-nm-ca",
    state: "California",
    region: "Pacific West",
    category: "National Monument",
    description: "Lava Beds offers one of the highest concentrations of lava tube caves in North America—over 800 known caves formed when the outer crust of lava flows cooled and solidified while molten rock drained away inside. Visitors can explore more than two dozen caves independently, from the strolling-easy Mushpot Cave to wild crawls through tight squeeze passages. The monument is also the site of the Modoc War of 1872–73, where a small band of Modoc warriors held off the U.S. Army for months in the labyrinthine lava rock fortifications of Captain Jack's Stronghold.",
    rating: 4.6,
    reviews: 5670,
    fee: "$25/vehicle",
    bestTime: "April–October",
    duration: "1-2 days",
    activities: ["Cave Exploration", "Hiking", "Birdwatching", "History Education", "Photography"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "https://picsum.photos/seed/lava-beds-nm-ca/800/450",
    tags: ["Lava Tubes", "Caves", "Volcanic", "Native American History"]
  },
  {
    id: 69,
    name: "Dinosaur National Monument",
    slug: "dinosaur-nm-co",
    state: "Colorado",
    region: "Rocky Mountains",
    category: "National Monument",
    description: "Dinosaur National Monument straddles the Colorado-Utah border where the Green and Yampa Rivers carve deep canyons through colorful rock layers—and where paleontologists discovered one of the world's richest dinosaur bone quarries in 1909. The Quarry Exhibit Hall is built directly over an exposed rock face containing over 1,500 fossilized dinosaur bones in their original positions, providing a visceral window into the Jurassic period. Whitewater rafting through the remote canyons of the Yampa River remains one of the most thrilling backcountry river experiences in the American West.",
    rating: 4.7,
    reviews: 9240,
    fee: "$25/vehicle",
    bestTime: "May–September",
    duration: "1-2 days",
    activities: ["Paleontology Tours", "Rafting", "Hiking", "Scenic Driving", "Photography"],
    difficulty: "Easy to Moderate",
    accessibility: true,
    image: "https://picsum.photos/seed/dinosaur-nm-co/800/450",
    tags: ["Dinosaurs", "Fossils", "Rafting", "Geology"]
  },
  {
    id: 70,
    name: "Jewel Cave National Monument",
    slug: "jewel-cave-nm-sd",
    state: "South Dakota",
    region: "Great Plains",
    category: "National Monument",
    description: "With over 220 miles of surveyed passages, Jewel Cave is the third-longest known cave in the world, and explorers continue to map new sections each year in the limestone beneath the Black Hills. The cave earns its name from sparkling calcite crystals called nailhead spar and dogtooth spar that encrust the walls, creating an underground jewel box of glittering formations. Ranger-guided tours range from a 30-minute scenic walk to the historic candlelight tour and the demanding half-mile spelunking Wild Caving Tour.",
    rating: 4.7,
    reviews: 8120,
    fee: "$12/adult (tour)",
    bestTime: "May–September",
    duration: "Half day",
    activities: ["Cave Tours", "Spelunking", "Photography", "Visitor Center", "Hiking"],
    difficulty: "Easy to Strenuous",
    accessibility: true,
    image: "https://picsum.photos/seed/jewel-cave-nm-sd/800/450",
    tags: ["Caves", "Geology", "Black Hills", "Underground Exploration"]
  },
  {
    id: 71,
    name: "Timpanogos Cave National Monument",
    slug: "timpanogos-cave-nm-ut",
    state: "Utah",
    region: "Rocky Mountains",
    category: "National Monument",
    description: "Timpanogos Cave is a system of three interconnected caverns high on the flanks of 11,749-foot Mount Timpanogos, reached by a steep 1.5-mile trail that climbs 1,065 feet above American Fork Canyon. Inside, visitors discover intricate helictites—twisting crystal formations that defy gravity—and vivid pools of multicolored cave coral that make this one of the most ornately decorated show caves in the West. The 3-mile round-trip trail through Rocky Mountain foliage, combined with the cave tour, makes for an unforgettable day in Utah's Wasatch Range.",
    rating: 4.7,
    reviews: 7380,
    fee: "$16/adult (cave tour)",
    bestTime: "May–October",
    duration: "Half day",
    activities: ["Cave Tours", "Hiking", "Photography", "Wildlife Watching", "Ranger Programs"],
    difficulty: "Moderate",
    accessibility: false,
    image: "https://picsum.photos/seed/timpanogos-cave-nm-ut/800/450",
    tags: ["Caves", "Mountain Hiking", "Crystal Formations", "Wasatch Range"]
  },
  {
    id: 72,
    name: "Oregon Caves National Monument & Preserve",
    slug: "oregon-caves-nm-or",
    state: "Oregon",
    region: "Pacific West",
    category: "National Monument",
    description: "Nestled in the Siskiyou Mountains of southern Oregon, Oregon Caves is a rare marble cavern carved by slightly acidic groundwater seeping through ancient metamorphic rock, decorated with ghostly white stalactites, stalagmites, and flowstone curtains. The National Historic Landmark Chateau, a six-story rustic lodge built in 1934 inside the mouth of the cave, is one of the most architecturally distinctive structures in the National Park System. Above ground, old-growth Douglas fir and Port Orford cedar forests shade the surrounding wilderness preserve.",
    rating: 4.6,
    reviews: 5240,
    fee: "$10/adult (cave tour)",
    bestTime: "June–September",
    duration: "Half day",
    activities: ["Cave Tours", "Hiking", "Photography", "Wildlife Watching", "Historic Lodge Visit"],
    difficulty: "Moderate",
    accessibility: false,
    image: "https://picsum.photos/seed/oregon-caves-nm-or/800/450",
    tags: ["Marble Caves", "Old-Growth Forest", "Siskiyou Mountains", "Historic Lodge"]
  },
  {
    id: 73,
    name: "Sunset Crater Volcano National Monument",
    slug: "sunset-crater-volcano-nm-az",
    state: "Arizona",
    region: "Southwest",
    category: "National Monument",
    description: "Sunset Crater, which last erupted around 1085 CE, is the youngest volcanic feature in the San Francisco volcanic field, its black cinder cone summit dusted in red and orange oxidized rock that appears perpetually lit by a setting sun. The Lava Flow Trail winds through a dramatic landscape of hardened basalt lava fields punctuated by ice caves, lava tubes, and cinder spatter cones rising above the ponderosa pine forest north of Flagstaff. The eruption dramatically transformed the ancestral homeland of the Sinagua people, whose rebuilt settlements are preserved just two miles away at Wupatki.",
    rating: 4.6,
    reviews: 6780,
    fee: "$25/vehicle (combined with Wupatki)",
    bestTime: "April–October",
    duration: "Half day",
    activities: ["Hiking", "Photography", "Scenic Driving", "Geology Exploration", "Ranger Programs"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/sunset-crater-volcano-nm-az/800/450",
    tags: ["Volcanic", "Cinder Cone", "Arizona", "Geology"]
  },
  {
    id: 74,
    name: "Wupatki National Monument",
    slug: "wupatki-nm-az",
    state: "Arizona",
    region: "Southwest",
    category: "National Monument",
    description: "Wupatki preserves hundreds of ancestral Puebloan sites scattered across the red-rock Painted Desert north of Flagstaff, most spectacularly the four-story, 100-room Wupatki Pueblo that was one of the largest buildings in the region around 1100–1225 CE. The site features a remarkable natural blowhole—a crack in the earth that breathes air in and out as atmospheric pressure changes—and a prehistoric ball court that hints at cultural connections reaching as far as Mesoamerica. The juxtaposition of crimson Moenkopi sandstone ruins against the vast high desert panorama creates an atmosphere of profound solitude and ancient mystery.",
    rating: 4.7,
    reviews: 7050,
    fee: "$25/vehicle (combined with Sunset Crater)",
    bestTime: "April–October",
    duration: "Half day",
    activities: ["Archaeology Tours", "Hiking", "Photography", "Ranger Programs", "Scenic Driving"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/wupatki-nm-az/800/450",
    tags: ["Ancestral Puebloans", "Archaeology", "Arizona", "High Desert"]
  },
  {
    id: 75,
    name: "Cliff Palace at Mesa Verde",
    slug: "mesa-verde-cliff-palace-co",
    state: "Colorado",
    region: "Rocky Mountains",
    category: "Historic Site",
    description: "Cliff Palace is the largest cliff dwelling in North America, a 150-room, 23-kiva masterwork of Ancestral Puebloan architecture tucked beneath a sweeping sandstone alcove in Mesa Verde National Park. Built between 1190 and 1260 CE, it was home to approximately 100 people and served as a social and ceremonial hub for the surrounding community. Ranger-led tours descend into the alcove via stone steps and four original hand-and-toe-hold ladders, providing an intimate encounter with one of the most extraordinary engineering achievements of pre-Columbian North America.",
    rating: 4.9,
    reviews: 19480,
    fee: "$6/person (tour ticket, included with park entry)",
    bestTime: "May–October",
    duration: "Half day",
    activities: ["Guided Tours", "Archaeology", "Photography", "Hiking", "History Education"],
    difficulty: "Moderate",
    accessibility: false,
    image: "https://picsum.photos/seed/mesa-verde-cliff-palace-co/800/450",
    tags: ["Cliff Dwellings", "Ancestral Puebloans", "UNESCO", "Archaeology"]
  }
];
