const attractionsPage4 = [
  {
    id: 76,
    name: "Na Pali Coast",
    slug: "na-pali-coast",
    state: "Hawaii",
    region: "Hawaii",
    category: "National Park",
    description: "Na Pali Coast's impossibly dramatic sea cliffs soar 4,000 feet above the Pacific on Kauai's northwest shore. Accessible only by boat, helicopter, or the grueling 11-mile Kalalau Trail, this untamed wilderness rewards adventurers with emerald valleys, hidden sea caves, and cascading waterfalls plunging directly into the ocean.",
    rating: 4.9,
    reviews: 28400,
    fee: "$35/vehicle",
    bestTime: "May–September",
    duration: "1–3 days",
    activities: ["Hiking", "Kayaking", "Snorkeling", "Boat Tours", "Photography"],
    difficulty: "Strenuous",
    accessibility: false,
    image: "https://picsum.photos/seed/na-pali-coast/800/450",
    tags: ["cliffs", "ocean", "hawaii", "tropical", "remote"]
  },
  {
    id: 77,
    name: "Horseshoe Bend",
    slug: "horseshoe-bend",
    state: "Arizona",
    region: "Southwest",
    category: "Natural Wonder",
    description: "The Colorado River makes an almost perfect 270-degree oxbow loop around a massive sandstone peninsula, creating one of the American Southwest's most iconic vistas. The short 1.5-mile round-trip hike rewards visitors with a vertiginous 1,000-foot drop into the turquoise river below, best photographed at golden hour.",
    rating: 4.8,
    reviews: 52100,
    fee: "$10/vehicle",
    bestTime: "March–May, September–November",
    duration: "Half day",
    activities: ["Hiking", "Photography", "Scenic Views", "Sunrise/Sunset"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/horseshoe-bend/800/450",
    tags: ["canyon", "river", "arizona", "photography", "iconic"]
  },
  {
    id: 78,
    name: "The Wave",
    slug: "the-wave",
    state: "Arizona",
    region: "Southwest",
    category: "Natural Wonder",
    description: "Hidden in the Coyote Buttes of the Vermilion Cliffs Wilderness, The Wave is a swirling sandstone formation of undulating red and orange layers that look sculpted by a master artist. Access requires a lottery permit (only 64 visitors per day), making this one of America's most exclusive and coveted hiking destinations.",
    rating: 4.9,
    reviews: 8200,
    fee: "$7/person",
    bestTime: "October–April",
    duration: "Full day",
    activities: ["Hiking", "Photography", "Geology", "Wilderness"],
    difficulty: "Moderate",
    accessibility: false,
    image: "https://picsum.photos/seed/the-wave-arizona/800/450",
    tags: ["sandstone", "lottery", "arizona", "geology", "rare"]
  },
  {
    id: 79,
    name: "Havasu Falls",
    slug: "havasu-falls",
    state: "Arizona",
    region: "Southwest",
    category: "Natural Wonder",
    description: "Deep within the Grand Canyon on Havasupai tribal land, Havasu Falls cascades 100 feet into a vivid turquoise pool—its otherworldly blue-green color created by high calcium carbonate content. The 10-mile trail through red canyon walls is one of America's most spectacular backcountry hikes, requiring advance permits that sell out within minutes.",
    rating: 4.9,
    reviews: 19600,
    fee: "$100/person (tribal permit)",
    bestTime: "March–June, September–October",
    duration: "2–4 days",
    activities: ["Hiking", "Swimming", "Camping", "Photography", "Backpacking"],
    difficulty: "Strenuous",
    accessibility: false,
    image: "https://picsum.photos/seed/havasu-falls/800/450",
    tags: ["waterfall", "turquoise", "tribal", "backpacking", "arizona"]
  },
  {
    id: 80,
    name: "Blue Ridge Parkway",
    slug: "blue-ridge-parkway",
    state: "Virginia / North Carolina",
    region: "Southeast",
    category: "Scenic Byway",
    description: "America's most-visited national park unit stretches 469 miles along the crest of the Appalachian Mountains, linking Shenandoah and Great Smoky Mountains National Parks. Known as 'America's Favorite Drive,' the parkway offers endless overlooks, wildflower meadows, cascading waterfalls, and charming Appalachian communities—a different palette every season.",
    rating: 4.8,
    reviews: 61300,
    fee: "Free",
    bestTime: "October (fall foliage), May–June (wildflowers)",
    duration: "1–5 days",
    activities: ["Scenic Drive", "Hiking", "Cycling", "Photography", "Wildlife Watching"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/blue-ridge-parkway/800/450",
    tags: ["road trip", "foliage", "appalachian", "scenic", "drive"]
  },
  {
    id: 81,
    name: "Going-to-the-Sun Road",
    slug: "going-to-the-sun-road",
    state: "Montana",
    region: "Rocky Mountains",
    category: "Scenic Byway",
    description: "Carved into the face of the Continental Divide in Glacier National Park, this 50-mile road is an engineering marvel and a breathtaking journey through alpine wilderness. Crossing Logan Pass at 6,646 feet, the route traverses hanging gardens of wildflowers, sheer cliff faces, and panoramic vistas of glacially carved valleys.",
    rating: 4.9,
    reviews: 34700,
    fee: "$35/vehicle",
    bestTime: "July–September",
    duration: "1–2 days",
    activities: ["Scenic Drive", "Hiking", "Wildlife Watching", "Photography", "Cycling"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/going-to-the-sun-road/800/450",
    tags: ["glacier", "alpine", "road trip", "montana", "mountain"]
  },
  {
    id: 82,
    name: "Pacific Coast Highway",
    slug: "pacific-coast-highway",
    state: "California",
    region: "Pacific West",
    category: "Scenic Byway",
    description: "Highway 1 winds along the California coastline for over 650 miles, offering one of the world's great drives where rugged Big Sur cliffs, elephant seal beaches, charming coastal towns, and endless Pacific vistas unfold around every curve. The stretch from San Francisco to Los Angeles passes through some of the most dramatic coastal scenery on Earth.",
    rating: 4.8,
    reviews: 87500,
    fee: "Free (some day use fees at parks)",
    bestTime: "March–May, September–November",
    duration: "3–7 days",
    activities: ["Scenic Drive", "Surfing", "Wildlife Watching", "Photography", "Whale Watching"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/pacific-coast-highway/800/450",
    tags: ["california", "ocean", "road trip", "big sur", "coastal"]
  },
  {
    id: 83,
    name: "Appalachian Trail",
    slug: "appalachian-trail",
    state: "Maine to Georgia",
    region: "Southeast",
    category: "National Scenic Trail",
    description: "The granddaddy of American long trails stretches 2,190 miles from Springer Mountain, Georgia to Mount Katahdin, Maine through 14 states and some of the East's most wild and beautiful landscapes. Thousands attempt a thru-hike each year; millions more enjoy day hikes at access points, from the iconic balds of Tennessee to the fog-shrouded peaks of Vermont.",
    rating: 4.8,
    reviews: 43200,
    fee: "Free",
    bestTime: "Varies by section (March–June southbound, NOBO start)",
    duration: "5–7 months (thru-hike) or day hike",
    activities: ["Hiking", "Backpacking", "Camping", "Wildlife Watching", "Photography"],
    difficulty: "Strenuous",
    accessibility: false,
    image: "https://picsum.photos/seed/appalachian-trail/800/450",
    tags: ["thru-hike", "east coast", "backpacking", "epic", "trail"]
  },
  {
    id: 84,
    name: "Cape Hatteras National Seashore",
    slug: "cape-hatteras",
    state: "North Carolina",
    region: "Southeast",
    category: "National Seashore",
    description: "The Outer Banks of North Carolina form a slender barrier island chain stretching 70 miles, home to America's first national seashore and the iconic black-and-white spiral Cape Hatteras Lighthouse—the tallest brick lighthouse in the US at 198 feet. Wild ponies roam the beaches, and the waters are famous for world-class surfing and offshore fishing.",
    rating: 4.7,
    reviews: 22800,
    fee: "Free",
    bestTime: "May–September",
    duration: "2–4 days",
    activities: ["Swimming", "Surfing", "Fishing", "Birdwatching", "Lighthouse Tour"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/cape-hatteras/800/450",
    tags: ["beach", "lighthouse", "north carolina", "outer banks", "ocean"]
  },
  {
    id: 85,
    name: "Assateague Island",
    slug: "assateague-island",
    state: "Maryland / Virginia",
    region: "Northeast",
    category: "National Seashore",
    description: "A 37-mile barrier island straddling Maryland and Virginia, Assateague is most famous for its herds of feral Chincoteague ponies that have roamed free for centuries. The pristine beach offers excellent surf fishing, camping under the stars, and the rare chance to watch wild horses graze on salt marshes at sunset.",
    rating: 4.7,
    reviews: 18400,
    fee: "$25/vehicle",
    bestTime: "May–September",
    duration: "1–3 days",
    activities: ["Beach", "Wildlife Watching", "Camping", "Fishing", "Photography"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/assateague-island/800/450",
    tags: ["wild ponies", "beach", "maryland", "camping", "wildlife"]
  },
  {
    id: 86,
    name: "Indiana Dunes National Park",
    slug: "indiana-dunes",
    state: "Indiana",
    region: "Great Plains",
    category: "National Park",
    description: "Surprisingly close to Chicago, Indiana Dunes National Park protects 15 miles of Lake Michigan shoreline featuring massive sand dunes, rare oak savannas, and bogs harboring over 1,100 plant species—more than in any other national park. Mount Baldy, a 126-foot-tall living dune, slowly migrates inland and swallows the forest in its path.",
    rating: 4.6,
    reviews: 14200,
    fee: "Free",
    bestTime: "June–September",
    duration: "1–2 days",
    activities: ["Beach", "Hiking", "Birdwatching", "Sandboarding", "Swimming"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/indiana-dunes/800/450",
    tags: ["dunes", "lake michigan", "beach", "midwest", "hidden gem"]
  },
  {
    id: 87,
    name: "Congaree National Park",
    slug: "congaree",
    state: "South Carolina",
    region: "Southeast",
    category: "National Park",
    description: "Congaree protects the largest intact expanse of old-growth bottomland hardwood forest in the United States, where cypress and tupelo trees rise from flooded floodplains to create a cathedral-like canopy. Firefly season in late May–early June brings thousands of synchronous fireflies blinking in unison—a rare natural phenomenon that draws visitors from around the world.",
    rating: 4.7,
    reviews: 11800,
    fee: "Free",
    bestTime: "March–May, October–November",
    duration: "1–2 days",
    activities: ["Canoeing", "Hiking", "Birdwatching", "Wildlife Watching", "Photography"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/congaree-national-park/800/450",
    tags: ["cypress", "swamp", "fireflies", "south carolina", "old growth"]
  },
  {
    id: 88,
    name: "Pictured Rocks National Lakeshore",
    slug: "pictured-rocks",
    state: "Michigan",
    region: "Great Plains",
    category: "National Lakeshore",
    description: "Multicolored sandstone cliffs streaked with mineral stains—iron red, copper green, manganese black—rise 200 feet above Lake Superior along Michigan's Upper Peninsula. Sea caves hollowed by centuries of wave action become magical ice caves in winter, while summer kayakers paddle through turquoise waters past waterfalls and hidden arches.",
    rating: 4.8,
    reviews: 16500,
    fee: "$20/vehicle",
    bestTime: "July–September (kayaking), January–February (ice caves)",
    duration: "2–3 days",
    activities: ["Kayaking", "Hiking", "Photography", "Ice Caves", "Boat Tours"],
    difficulty: "Moderate",
    accessibility: false,
    image: "https://picsum.photos/seed/pictured-rocks/800/450",
    tags: ["cliffs", "great lakes", "michigan", "kayaking", "ice caves"]
  },
  {
    id: 89,
    name: "Great Sand Dunes National Park",
    slug: "great-sand-dunes",
    state: "Colorado",
    region: "Rocky Mountains",
    category: "National Park",
    description: "North America's tallest sand dunes rise 750 feet against the backdrop of Colorado's snow-capped Sangre de Cristo Mountains, creating a surreal landscape where desert meets alpine. Medano Creek, a seasonal stream, runs along the dune's base each spring—children wade in its warm current before climbing the massive dunes under brilliant blue skies.",
    rating: 4.7,
    reviews: 19300,
    fee: "$25/vehicle",
    bestTime: "May–June (creek), September–October (cooler dunes)",
    duration: "1–2 days",
    activities: ["Sand Boarding", "Hiking", "Swimming", "Stargazing", "Photography"],
    difficulty: "Moderate",
    accessibility: false,
    image: "https://picsum.photos/seed/great-sand-dunes/800/450",
    tags: ["dunes", "colorado", "mountains", "unique", "surreal"]
  },
  {
    id: 90,
    name: "Apostle Islands National Lakeshore",
    slug: "apostle-islands",
    state: "Wisconsin",
    region: "Great Plains",
    category: "National Lakeshore",
    description: "Twenty-one islands dot Lake Superior's Chequamegon Bay, harboring the largest collection of historic lighthouses in the national park system. The sea caves carved into the red sandstone of the mainland shore freeze into a crystalline wonderland each winter, while summer brings pristine kayaking, sailing, and some of the clearest freshwater in the world.",
    rating: 4.8,
    reviews: 12100,
    fee: "Free",
    bestTime: "July–August (kayaking), January–February (ice caves)",
    duration: "2–4 days",
    activities: ["Kayaking", "Sailing", "Hiking", "Ice Caves", "Lighthouse Tours"],
    difficulty: "Moderate",
    accessibility: false,
    image: "https://picsum.photos/seed/apostle-islands/800/450",
    tags: ["great lakes", "wisconsin", "sea caves", "kayaking", "lighthouses"]
  },
  {
    id: 91,
    name: "Theodore Roosevelt National Park",
    slug: "theodore-roosevelt",
    state: "North Dakota",
    region: "Great Plains",
    category: "National Park",
    description: "The rugged North Dakota Badlands inspired a young Theodore Roosevelt's conservation ethic when he came here to grieve his mother and wife and found solace in the untamed wilderness. Today the park preserves the stunning painted buttes and petrified forests where free-roaming bison herds, wild horses, and prairie dogs go about their ancient routines.",
    rating: 4.7,
    reviews: 9800,
    fee: "$30/vehicle",
    bestTime: "June–September",
    duration: "1–2 days",
    activities: ["Scenic Drive", "Wildlife Watching", "Hiking", "Horseback Riding", "Photography"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/theodore-roosevelt/800/450",
    tags: ["badlands", "bison", "north dakota", "history", "prairie"]
  },
  {
    id: 92,
    name: "Kenai Fjords National Park",
    slug: "kenai-fjords",
    state: "Alaska",
    region: "Pacific West",
    category: "National Park",
    description: "Where the Harding Icefield—one of the largest in North America—calves glaciers into icy fjords teeming with Steller sea lions, orca pods, and puffin colonies, Kenai Fjords delivers Alaska's most accessible wilderness spectacle. Exit Glacier, reachable by road, offers the sobering experience of walking beside a living glacier and reading markers showing its dramatic retreat.",
    rating: 4.8,
    reviews: 14700,
    fee: "Free",
    bestTime: "June–August",
    duration: "2–3 days",
    activities: ["Boat Tours", "Glacier Hiking", "Wildlife Watching", "Kayaking", "Photography"],
    difficulty: "Moderate",
    accessibility: false,
    image: "https://picsum.photos/seed/kenai-fjords/800/450",
    tags: ["alaska", "glacier", "fjords", "wildlife", "orca"]
  },
  {
    id: 93,
    name: "Wrangell-St. Elias National Park",
    slug: "wrangell-st-elias",
    state: "Alaska",
    region: "Pacific West",
    category: "National Park",
    description: "America's largest national park at 13.2 million acres—larger than Switzerland—encompasses four major mountain ranges, nine of North America's sixteen highest peaks, and the world's largest concentration of glaciers outside polar regions. The abandoned Kennecott copper mines, a National Historic Landmark perched impossibly on a moraine, adds a ghost-town adventure to the wilderness.",
    rating: 4.8,
    reviews: 6500,
    fee: "Free",
    bestTime: "June–August",
    duration: "3–7 days",
    activities: ["Backpacking", "Flightseeing", "Glacier Travel", "Wildlife Watching", "Historic Sites"],
    difficulty: "Strenuous",
    accessibility: false,
    image: "https://picsum.photos/seed/wrangell-st-elias/800/450",
    tags: ["alaska", "largest park", "glacier", "wilderness", "remote"]
  },
  {
    id: 94,
    name: "Mesa Verde National Park",
    slug: "mesa-verde-cliff-dwellings",
    state: "Colorado",
    region: "Southwest",
    category: "National Park",
    description: "Perched in the canyon alcoves of a 15-mile mesa in southwest Colorado, the ancestral Puebloan cliff dwellings of Mesa Verde are among the most remarkable archaeological sites in North America. Cliff Palace—the continent's largest cliff dwelling—housed 150 people in 150 rooms and 23 kivas, offering an intimate look into a civilization that flourished here for 700 years.",
    rating: 4.8,
    reviews: 21400,
    fee: "$35/vehicle",
    bestTime: "May–October",
    duration: "1–2 days",
    activities: ["Guided Tours", "Hiking", "Archaeology", "Photography", "Cultural History"],
    difficulty: "Moderate",
    accessibility: false,
    image: "https://picsum.photos/seed/mesa-verde/800/450",
    tags: ["cliff dwellings", "ancestral puebloan", "colorado", "archaeology", "history"]
  },
  {
    id: 95,
    name: "Biscayne National Park",
    slug: "biscayne",
    state: "Florida",
    region: "Southeast",
    category: "National Park",
    description: "Just south of Miami, Biscayne protects the northernmost Florida Keys and the largest maritime mangrove forest in the national park system—yet 95% of its 172,000 acres is water. The living coral reef, one of the world's third-largest barrier reef systems, nurtures sea turtles, manatees, and rainbow-colored tropical fish that snorkelers can explore by boat or kayak.",
    rating: 4.6,
    reviews: 8700,
    fee: "Free",
    bestTime: "December–April",
    duration: "1–2 days",
    activities: ["Snorkeling", "Scuba Diving", "Kayaking", "Boat Tours", "Fishing"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/biscayne-national-park/800/450",
    tags: ["florida", "coral reef", "underwater", "miami", "snorkeling"]
  },
  {
    id: 96,
    name: "Cuyahoga Valley National Park",
    slug: "cuyahoga-valley",
    state: "Ohio",
    region: "Great Plains",
    category: "National Park",
    description: "Nestled between Cleveland and Akron, Cuyahoga Valley protects a forested river valley that represents a remarkable comeback story—from a heavily polluted industrial river to a thriving natural corridor. The historic Ohio & Erie Canal towpath follows the river for 20 miles, and Brandywine Falls drops 65 feet through a sandstone gorge draped in ferns.",
    rating: 4.6,
    reviews: 17300,
    fee: "Free",
    bestTime: "April–November",
    duration: "1–2 days",
    activities: ["Hiking", "Cycling", "Birdwatching", "Scenic Railroad", "Waterfall"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/cuyahoga-valley/800/450",
    tags: ["ohio", "waterfall", "trail", "midwest", "urban park"]
  },
  {
    id: 97,
    name: "Guadalupe Mountains National Park",
    slug: "guadalupe-mountains",
    state: "Texas",
    region: "Southwest",
    category: "National Park",
    description: "The Guadalupe Mountains contain the highest peaks in Texas and one of the world's greatest fossil reef complexes—the Capitan Reef, formed 265 million years ago in a vast inland sea. El Capitan's sheer limestone escarpment towers 1,000 feet above the Chihuahuan Desert, and the annual fall foliage in McKittrick Canyon rivals New England for color despite Texas's desert setting.",
    rating: 4.7,
    reviews: 7900,
    fee: "$15/person",
    bestTime: "October–April",
    duration: "1–2 days",
    activities: ["Hiking", "Backpacking", "Stargazing", "Photography", "Fossil Study"],
    difficulty: "Moderate",
    accessibility: false,
    image: "https://picsum.photos/seed/guadalupe-mountains/800/450",
    tags: ["texas", "fossil reef", "hiking", "desert", "stargazing"]
  },
  {
    id: 98,
    name: "Kobuk Valley National Park",
    slug: "kobuk-valley",
    state: "Alaska",
    region: "Pacific West",
    category: "National Park",
    description: "One of the least-visited national parks in the US, Kobuk Valley is a true wilderness accessible only by small aircraft or river travel, lying above the Arctic Circle in Alaska's Brooks Range. The Great Kobuk Sand Dunes—25 square miles of towering Arctic sand dunes—create one of the world's most unexpected landscapes, where temperatures can soar to 90°F in summer while caribou herds of 500,000 migrate through.",
    rating: 4.7,
    reviews: 1200,
    fee: "Free",
    bestTime: "June–August",
    duration: "3–5 days",
    activities: ["Flightseeing", "River Travel", "Wildlife Watching", "Photography", "Wilderness"],
    difficulty: "Strenuous",
    accessibility: false,
    image: "https://picsum.photos/seed/kobuk-valley/800/450",
    tags: ["alaska", "arctic", "sand dunes", "remote", "wilderness"]
  },
  {
    id: 99,
    name: "Saguaro National Park",
    slug: "saguaro",
    state: "Arizona",
    region: "Southwest",
    category: "National Park",
    description: "Surrounding Tucson in two districts east and west, Saguaro National Park protects the symbol of the American West—the giant saguaro cactus. These slow-growing giants can live 150 years, reach 40 feet in height, and weigh 4 tons when fully hydrated; the white blooms that crown their arms are Arizona's state flower. Sunset over a saguaro forest is one of the Southwest's signature experiences.",
    rating: 4.7,
    reviews: 16800,
    fee: "$25/vehicle",
    bestTime: "October–April",
    duration: "1–2 days",
    activities: ["Hiking", "Cycling", "Wildlife Watching", "Stargazing", "Photography"],
    difficulty: "Easy",
    accessibility: true,
    image: "https://picsum.photos/seed/saguaro-national-park/800/450",
    tags: ["cactus", "arizona", "desert", "sunset", "tucson"]
  },
  {
    id: 100,
    name: "Channel Islands National Park",
    slug: "channel-islands",
    state: "California",
    region: "Pacific West",
    category: "National Park",
    description: "Just 14 miles off the Southern California coast yet receiving fewer than 400,000 visitors a year, the five Channel Islands are a wildlife paradise often called the 'Galapagos of North America.' Island foxes found nowhere else on Earth, 2,000 breeding elephant seals, and kelp forests sheltering giant sea bass make this one of the most ecologically unique parks in the country.",
    rating: 4.8,
    reviews: 10400,
    fee: "$15/person (boat required)",
    bestTime: "March–November",
    duration: "1–3 days",
    activities: ["Kayaking", "Snorkeling", "Scuba Diving", "Wildlife Watching", "Camping"],
    difficulty: "Moderate",
    accessibility: false,
    image: "https://picsum.photos/seed/channel-islands/800/450",
    tags: ["california", "islands", "wildlife", "ocean", "kayaking"]
  }
];
