const PARK_REVIEWS = {
  "yellowstone": [
    {name:"BrakiWorldTraveler",rating:5,text:"Nature at its best - long time wish fulfilled. I strongly suggest reserving the very first morning slot 7-8 AM. This will benefit you not waiting in long lines to enter the park gates. Furthermore you won't have to wait at parking lots for someone..."},
    {name:"Sherry R",rating:5,text:"My heart now lives in Yellowstone! It's healing for the Soul.\" Describes a 12-day trip including Grand Teton and Cody, Wyoming, recommending minimum week-long visits with guided tours and spotting scopes for wildlife observation."},
    {name:"Bill L",rating:3,text:"Old Faithful is historic, Grand Prismatic Spring is spectacular. Park traffic is HORRENDOUS... This literally sucked all the joy out of our day."},
    {name:"GeorgiaTravelers51",rating:2,text:"Like so many national parks now, Yellowstone has become too crowded to enjoy in the summer... could not enjoy the major sights for the extreme crowds and traffic."},
    {name:"Barry S",rating:1,text:"The traffic was HORRENDOUS from the West Gate to Old Faithful... The Park in its present state cannot handle the volume of vehicles being allowed in."},
  ],
  "yosemite": [
    {name:"Toblje",rating:5,text:"Yosemite National Park is one of the most visited national parks in the United States for a reason. The landscape is magnificent: steep granite walls, dense forests, tranquil lakes and – depending on the season – impressive waterfalls. The main at..."},
    {name:"Jad",rating:5,text:"Yosemite is hard to describe to someone who has never visited the park. It is of course a National Park with the expected sweeping landscapes and nature but, having been to 9 National Parks, I have to say there is something special here. Gazing ou..."},
    {name:"Ruth P",rating:5,text:"Yosemite is simply breathtaking! Towering granite cliffs, sparkling waterfalls, peaceful meadows, and the giant sequoias all come together to create scenery that feels almost unreal. We visited over Labor Day weekend and had to make a reservation ..."},
    {name:"SMECM",rating:5,text:"We so enjoyed everything about Yosemite. We visited during firefall season just after a snowstorm. The rangers are really nice and helpful. Don't forget to visit the waterfalls more than once as they're constantly changing."},
    {name:"Toblje",rating:4,text:"Accommodation in the national park is very expensive and below average quality. Cheaper and better alternatives can be found outside, but with a longer journey. Depending on the accommodation you have to expect a drive of one to one and a half hours."},
  ],
  "grand-canyon": [
    {name:"Tianxingzhe",rating:5,text:"Pictures and videos don't do the actual experience justice. Bright Angel Trail and South Kaibab Trail are recommended. The South Rim is a truly amazing place to visit."},
    {name:"HighlandLass24",rating:5,text:"Of course you have to go. It's really something to see. Definitely worth it to see with your own eyes even if you don't get instagram worth photos."},
    {name:"grannyjohnson531",rating:3,text:"We were there in late March, the crowds were overwhelming due partly due to Spring Break. We waited over two hours to get into the park even tho there were four lanes of traffic going into the park. The views from Mather Point are amazingly beauti..."},
    {name:"Dieuwer",rating:3,text:"After spending a day at the Grand Canyon, I think I find it overrated as a National Park. I entered the park through the east entrance and drove along the rim to Grand Canyon village. After several scenic vistas everything starts to look the same...."},
    {name:"Suryanarayana K",rating:4,text:"We started from Phoenix and reached the Grand Canyon Village by noon. What surprised me was lack of protective barriers on the rim trail and so many visitors were climbing onto adjoining rocks taking pictures in a very risky way. It was a very hot..."},
  ],
  "zion": [
    {name:"Holly C",rating:5,text:"What an absolutely amazing trip. This hike up the Narrows is not to be missed. Highly recommend to rent the water hiking boots, waders and walking stick ($60)."},
    {name:"Sherry T",rating:5,text:"We took the advice and caught the shuttle on a Saturday in August at 7:30 AM — absolutely the way to go! No lines, no need for a park pass that early."},
    {name:"BrakiWorldTraveler",rating:4,text:"Zion NP is another amazing park, however after visiting Bryce the day before, it left a weaker impression on us."},
    {name:"Go4ItSoon",rating:2,text:"Beautiful, but Congested & Expensive. If you go there during the prime season, when the kids are out of school, and all the families are on vacation, you may be talking about WalMart on Black Friday. We definitely found Zion to be the most congest..."},
    {name:"samdogNY",rating:5,text:"Zion is Majestic. We had concerns about going in August due to heat and crowds. As many will tell you - get up and out early."},
  ],
  "glacier": [
    {name:"christopherbO9687MP",rating:5,text:"Glacier National Park has excellent views of the Rocky Mountains and surrounding lakes, making this one of the jewels of the National Park Service. The Park can get very crowded during the peak summer season, particularly when driving on the famou..."},
    {name:"Ash & Jon (Elevateverything)",rating:5,text:"We have been to many national parks, and this is our favorite! The combination of the view on Going to the Sun Road which all ages can enjoy with the hiking opportunities from easy to challenging is unbeatable!"},
    {name:"Rehoboth5",rating:4,text:"First visited Glacier in 1967. We live in Montana, and try to visit every couple of years. It is a gem, truly one of the natural wonders of the world. Glacier is breaking records for numbers of visitors, and in the summer some areas of the park ar..."},
    {name:"PlugdudeTX",rating:4,text:"The views and hikes are amazing, but don't go during the high season if you can help it. We did the Avalanche Lake trail early in the morning (entered the park at 6:45 AM) and we felt like part of an ant colony - there was a ridiculous number of p..."},
    {name:"TheFamGuy1",rating:5,text:"It's a huge park to drive and hike around. The beauty of views and sounds was interrupted by hikers playing music loudly, having loud conversations and generally not sharing paths. The worst parking and experience is at the St Mary visitor center...."},
  ],
  "great-smoky": [
    {name:"Sandrita",rating:5,text:"Absolutely breathtaking!! This was my first time visiting a national park and it set a high bar on what to expect for the remaining 62."},
    {name:"Alejandro C",rating:5,text:"We visited Great Smoky Mountains National Park during Thanksgiving 2025 while staying in Gatlinburg, traveling with our two kids (11 and 8), and it was absolutely unforgettable."},
    {name:"Sierra D",rating:4,text:"Beautiful scenery in Great Smoky NP! Although it's disappointing with the latest road closures in the park, we made the best of our day trip and there's lots to see!"},
    {name:"Tammy P",rating:5,text:"What an amazing trip! I'll start with a couple of negatives: first, the road to Cherokee is closed due to a landslide, and second, the trails to Laurel Falls are closed until Fall 2026 for maintenance."},
    {name:"Sleepymoose88",rating:1,text:"My wife and I went to visit the Smokies on our 2 year anniversary, and after having visited several other popular national parks, this one was by far the worst experience. We went in September, which is the off season, but due to the popularity of..."},
  ],
  "rocky-mountain": [
    {name:"JDSoui",rating:5,text:"The park in one word is marvelous. The variety of trails, wildlife and elements/weather coupled with the views were simply amazing. The hikes to Bear, Nymph, Dream, Emerald and Haiyaha lakes were phenomenal. A suggestion is to arrive very early es..."},
    {name:"TravelingSoccerLoon",rating:5,text:"Rocky Mountain National Park is a spectacular place to visit. Driving on the Trail Ridge Road is exhilarating and provides some stunning scenery. It is the highest continuous paved road in the country at over 14,000 ft. You will need to book a tim..."},
    {name:"Fly",rating:5,text:"The visitors center didn't have much beyond the gift shop, but the women working were knowledgeable and gave us good advice for the day. There really is something for everyone in this park. I would love to see this in May when everything is alive...."},
    {name:"Jerri L",rating:5,text:"This National Park is absolutely amazing! We entered early and drove in from Grand Lake Entrance. It seemed as though this entrance was less busy which made the traffic flow easier. We stopped at all of the overlooks and had amazing views."},
    {name:"Don J",rating:3,text:"Mt. Rainier is a wonderful place but is now over run with too many people. Like many of our National Parks, Mt. Rainier is being loved to death.\" (Note: This reviewer's language applies equally to RMNP, and is a common refrain on the RMNP page as ..."},
  ],
  "acadia": [
    {name:"Eileen19",rating:5,text:"This park is so beautiful. I was impressed by the diversity of environments given that this is one of the smallest national parks. There's a sandy beach, rugged and rocky coastlines, cliffs, mountains, forests, marshes, rivers, lakes, and waterfalls."},
    {name:"USASUN",rating:5,text:"We had planned 2 whole days for this national park. We were lucky with the weather, it turned very cool but bright blue. After visiting the Visitor Center we drove along the Park Loop and have made various stops. Thunder Hole, Otter Cliff were the..."},
    {name:"Justin J",rating:4,text:"Online advertising said there was no cost to enter the park, but that is very untrue. They do offer discounts for Veterans. The views of both forest and ocean are beautiful, and easy to access by car or on foot. It will be more crowded during the ..."},
    {name:"SeniorTravelerTF",rating:4,text:"As someone who is a fan of national parks it hurts not to be able to rate 5-5, but it is hard to separate the Acadia experience from the city of Bar Harbor (and others). Both are interesting, both are crowded."},
    {name:"tywebb1980",rating:2,text:"Not the best National Park for the hype. I didn't have the best weather, but I was disappointed with the landscape regardless. The hikes were small. Very populated. Beauty was marginal. Definitely does not compare to parks out west. Not worth the ..."},
  ],
  "grand-teton": [
    {name:"Edward Q",rating:5,text:"Grand Teton National Park is a spectacular place. Truly an experience that I will remember for the rest of my life."},
    {name:"Eric E",rating:5,text:"I did not expect Grand Teton to hit like it did! The park has views of the Tetons for about 95% of all the roads."},
    {name:"Craig S",rating:5,text:"This park, like Yellowstone, is very busy. Visiting Jenny Lake must be done early or else you will walk an extra mile."},
    {name:"Charles S",rating:5,text:"We saved the best until last...A fantastic journey taking wonderful photographs, one was so good my wife's picture was voted 'Photo of the Year' by our local town's photo club!"},
    {name:"[Parkscollecting.com compiled]",rating:1,text:"There is nothing special about this national park. Nothing that we thought was a Wow factor. A lot of the trails were falling apart and swarming with mosquitos. Except the view of the three Teton peaks, it has no alluring vistas."},
  ],
  "joshua-tree": [
    {name:"worleybird98",rating:5,text:"We are big national park fans, so when spending a week in Palm Springs this was a must visit. The cactus gardens were amazing, and definitely take the short hike through them to really appreciate the area. As the day progressed the volume of visit..."},
    {name:"Sarah M",rating:5,text:"Joshua Tree National Park is absolutely stunning! I loved exploring spots like Hidden Valley and Keys View – the views were breathtaking. Be sure to download the tour beforehand, as it works offline once you're there."},
    {name:"The Monkey Traveler",rating:5,text:"What an amazing place. You feel like you stepped into a different world...almost another planet. The rock formations that are almost everywhere and at sizes that impress are breathtaking. Nature at its best. Be aware - there is NO water anywhere, ..."},
    {name:"allifromWI",rating:3,text:"This wasn't my favorite national park, by far. The Joshua Trees are unique. You don't see them elsewhere, so if you want to see them in person, this is the place. However, we went during the slower season and even then, the lines took 15-20 minute..."},
    {name:"JoeFRocklin",rating:5,text:"Even on a cloudy and foggy January morning, it was worth visiting. If the weather suits you, there are lots of hikes you can do, from easy to challenging. On hot or inclement days, you can tour the park easily from your car."},
  ],
  "arches": [
    {name:"BrakiWorldTraveler",rating:5,text:"Certainly one of top US NP. I strongly suggest reserving the very first morning slot 7-8 AM. This will benefit you not waiting in long lines to enter the park gates. Once inside, around 7:15 AM drive directly to the main star - Delicate Arch. At t..."},
    {name:"Brendan S",rating:5,text:"Arches is wildly - and deservedly - popular for its soaring stone arches, over 2,000 of them. It's a very easy park to visit, just 4 miles outside of Moab. The park is relatively compact and the entire park road can be driven in an hour. Arches do..."},
    {name:"Gwen C",rating:5,text:"Kudos to Utah for their efforts to keep Arches National Park open during the government shutdown October 2025. The State of Utah hired private vendors to maintain and stock the facilities throughout the NP. Beautiful and well maintained trails for..."},
    {name:"jbg74",rating:5,text:"Arches National Park is definitely worth a visit. You can see the highlights in a day, but an extra day or two will really allow you to experience the whole park. My favorite arch in the park was Double Arch."},
    {name:"[Parkscollecting.com compiled]",rating:1,text:"This place is worthless. Couple holes in the rocks. Don't see what the big deal is. Both of the arches were not what we expected."},
  ],
  "olympic": [
    {name:"Neemr22",rating:5,text:"There are many experiences to have in one park. Hiking to hurricane ridge to see the view. Walking among moss draped conifers in the Hoh rain forest where you think you are Luke Skywalker looking for Yoda. Then dip your toes in the Pacific in the ..."},
    {name:"waldentenn",rating:5,text:"We spent almost a week in the Park, working our way counterclockwise around the park. There is no way to drive through the park, so you have to drive into the park at various points then return to US 101. This is a spectacular park with three dist..."},
    {name:"DannyWasserman",rating:5,text:"We were taking in all the national parks in Washington, and Olympic National Park was second on our list after visiting Mount Rainier. This is a beautiful area and should not be missed. We enjoyed the mountains, hiking, waterfalls, and so much more."},
    {name:"lucilion",rating:5,text:"The park is very big and all the areas are very beautiful, each one is a different experience. You should stay at least four days to visit the principal areas as the distances between them are long. Do not miss the beaches, the contrast between th..."},
    {name:"[Parkscollecting.com compiled]",rating:1,text:"I don't think this is something too great, just another forest. Pretty much like every other forest except for some hanging moss and bugs. Just don't. Absolutely not worth it. We paid $30 to drive this road only to see absolutely nothing but clouds."},
  ],
  "bryce-canyon": [
    {name:"Kate S",rating:5,text:"This is one of my favorite National Parks because of the splendor of its beauty — the hoodoos, red rocks, pine trees. The Queen's Garden Trail (1-2 hrs depending on how fast you can hike up the switchbacks, unpaved, moderate) is a highlight."},
    {name:"Marshall B",rating:5,text:"It is hard to say enough about how spectacular this park is, particularly when there is still some snow on the ground. We stopped at most of the parking areas to admire the views, so it was about 2 1/2 hours from start to finish."},
    {name:"Kurt H",rating:5,text:"Endlessly fascinating, we never tire of Bryce. This time we were there in January and it definitely requires good winter clothes. The snow adds a nice visual feature for memories and photos."},
    {name:"Daniele_Gorizia",rating:5,text:"For us this is one of the most beautiful parks visited on our western itinerary. Rock formations that the weather has smoothed over millennia, giving them original pointed shapes called 'hoodoos'."},
    {name:"[Parkscollecting.com compiled]",rating:1,text:"This by far is one of the most boring parks to visit. Only come here if you're passing by. The walks are a bit mediocre and not all that scenic. Same hoodoos, slightly different angle."},
  ],
  "death-valley": [
    {name:"Ann C",rating:5,text:"Death Valley is known for its harsh, barren landscape, but every 10 years, it experiences a rare and beautiful super-bloom, where the desert floor is covered in vibrant wildflowers. This year, the park is lucky enough to have one of these spectacu..."},
    {name:"150rajibs",rating:5,text:"Easy visit - and a very different world - from Las Vegas on good roads, prone to flooding and closure. The visitor center is an excellent source of information and advice. We heeded their advice to go to Badwater the afternoon we arrived as rains ..."},
    {name:"Shivraj Saxena",rating:5,text:"Driving through it was one of the most beautiful parts of our California honeymoon road trip. The scenery constantly changed, offering stunning desert landscapes, dramatic terrain, and wide open views that made the journey feel truly special. Expe..."},
    {name:"CDTrip72",rating:5,text:"With my daughter's school schedule, we could only visit during the summer and while we were expecting it to be hot, it got as hot as 122 degrees, so it was brutal. Despite that, we still really enjoyed our stay here. We were surprised to hear that..."},
    {name:"[Compiled negative]",rating:3,text:"Fuel costs are notably high at $5.85 per gallon in the park, and the distances between attractions mean you're almost certainly going to spend a lot just on gas. The park is massive — visitors travel an average of 107 miles per day just to see the..."},
  ],
  "denali": [
    {name:"hms917",rating:5,text:"This was a key highlight of our trip, and we took the green shuttle buses. We saw moose, porcupine, brown bears, a fox, ptarmigans, dall sheep, and lots of caribou. It was an epic few days."},
    {name:"Colleen C",rating:5,text:"We spent a few days in the Denali area, and the park was amazing! We were able to see the peaks of Denali both days. We also learned that we were in the lucky 5% of people who have seen the Denali peaks cloudless, which was spectacular!"},
    {name:"F L Eveline",rating:4,text:"The park is beautiful. The Horseshoe Lake Trail was a highlight, where we saw a moose up close drinking from the lake. Would love to come back one day and go deeper into the park."},
    {name:"georgiatrekker",rating:2,text:"Did the Holland American land/sea tour, and wish we would have skipped the 'land' portion. Next day another 8 hours on a Denali bus tour with damp, overcast weather. Visibility was about zero which apparently is quite common. We were told only abo..."},
    {name:"The_Travel_Family123",rating:2,text:"We are a well-travelled family of over 35 National Parks. Visitors to the park can only drive the first 15 miles of the road. To go further you can only book a bus tour through a completely separate company — the park offers 'no' free shuttle beyo..."},
  ],
  "mount-rainier": [
    {name:"Robert B",rating:5,text:"We had a magnificent day in Mount Rainier National Park. At first we were a little concerned that the weather would not cooperate but we ended up enjoying wonderful views of the peak and other parts of the park. We actually drove above the clouds!"},
    {name:"marield1990",rating:5,text:"We came in here the beginning of October and went on a Tuesday and Wednesday which was a smart decision. Driving in on our first day we had perfect weather. Sunny and clear. The second was foggy all day. Very pretty in a different way, but we were..."},
    {name:"Jo Z",rating:5,text:"I have been here before and loved it, so this time I came early in the season in June with a friend to show her when there was plenty of snow around. This is my favourite volcano in the world and I recommend this park for hiking the many trails, s..."},
    {name:"Don J",rating:3,text:"Mt. Rainier is a wonderful place but is now over run with too many people. Like many of our National Parks, Mt. Rainier is being loved to death."},
    {name:"[Parkscollecting.com compiled]",rating:1,text:"It was like a juicy piece of steak presented on a trash can lid. Spending 30 dollars to drive 30 min up a mountain and then almost everything closed. Really is a one trick pony. We couldn't see the mountain from Paradise Point due to heavy fog."},
  ],
  "sequoia": [
    {name:"CDTrip72",rating:5,text:"Sequoia is unique as it is the only joint run national park, as it's right next to Kings Canyon National Park, so you only need one admission fee. The General Sherman Tree is the main attraction, and it is very impressive — it's the largest tree (..."},
    {name:"Adam J",rating:5,text:"Worth going and camping or RVing in the park. We stayed at Lodgepole campground, a very quiet area with lots of deer and various chipmunks. Worth seeing the giant Sequoias."},
    {name:"Miguel Quintanilla",rating:5,text:"It is an excellent park, with many attractions and paths to travel and everything very well signposted. It is difficult to move in your own vehicle inside the park as there are areas where parking is quite limited."},
    {name:"Christian P",rating:5,text:"It was awesome, a must see. Just beware: the road is a bit difficult and must be very aware to drive. Recommend you take shorts and good shoes to walk, a lot."},
    {name:"Chriscrew",rating:2,text:"We drove through, could not park in the parking next to the generals tree visitors center. We had a pick up camper and vehicles jack-ass parked in the RV area. Beautiful trees and area anyway but we just cruised on through. Too many people in Apri..."},
  ],
  "everglades": [
    {name:"Grover R",rating:5,text:"Everglades National Park is simply one of my favorite national parks, so I was so excited to have the opportunity to show it to 4 other couples who had never visited it last spring. Everglades National Park is a collection of 8-10 different ecosys..."},
    {name:"Sally C",rating:5,text:"We spent the day visiting Everglades National Park. We downloaded the Shaka Guide Tour for this park and found it very informative. The trails are very well marked and flat. I recommend doing them all. We did Anhinga (saw many alligators), Gumbo L..."},
    {name:"Tina",rating:5,text:"On the guided tram tour we could see many birds, alligators and turtles. As a small tip, please be sure to use Mosquito Spray. The little bloodsuckers are everywhere."},
    {name:"William B",rating:5,text:"This is my second visit in about 18 years. The sunsets are amazing over Florida Bay. It's a $35.00 entry fee and it's good for a 6 day pass. It's a 38 mile drive from the Homestead entrance to where the road ends at Flamingo."},
    {name:"Fraser C",rating:1,text:"Wanted to go to the ENP for years, looks great when you see programmes on TV about it, but it was a waste of time. Easily most disappointing part of our entire month long road trip around Florida. I don't know if it was due to time of year we were..."},
  ],
  "shenandoah": [
    {name:"Zeec201457",rating:5,text:"We did the skyline drive and the views are stunning. Make sure to bring food because there's limited places to purchase food in the park. There was a lot to do at the visitor center. We even met Smokey the bear."},
    {name:"DLP",rating:5,text:"Spring had not sprung yet when we visited, so I can only imagine how much more beautiful this Park must be when Spring finally arrives. None the less, we were not disappointed — the views were absolutely gorgeous, especially the panoramic ones. Pl..."},
    {name:"Lisa J",rating:5,text:"We have driven through the park 3 times now and I just got my passport book stamped. It's a very beautiful park, with lots of hiking trails and places to pull off and view. If you decide you need gas there is some at the Big Meadows visitor center."},
    {name:"PuzzleSolver855",rating:4,text:"Gotta say, Autumn is probably a better time for views. Some of the viewpoints were congested and a few trails closed due to rain. One we took was open but an inch under water in places. Wear your boots! Stopped at Elkwallow Wayside for food option..."},
    {name:"wohdonkey",rating:4,text:"We enjoyed this park with the hiking and the beautiful views from the tops of the hikes. The issues we had were weather related with rain and clouds as well as the waterfalls not having enough water due to little rain this summer. On the fourth da..."},
  ],
};
