const PARK_REVIEWS = {
  "yellowstone": [
    {name:"Sherry R",rating:5,text:"My heart now lives in Yellowstone! It's healing for the Soul.\" Describes a 12-day trip including Grand Teton and Cody, Wyoming, recommending minimum week-long visits with guided tours and spotting scopes for wildlife observation."},
    {name:"Bill L",rating:3,text:"Old Faithful is historic, Grand Prismatic Spring is spectacular. Park traffic is HORRENDOUS... This literally sucked all the joy out of our day."},
    {name:"GeorgiaTravelers51",rating:2,text:"Like so many national parks now, Yellowstone has become too crowded to enjoy in the summer... could not enjoy the major sights for the extreme crowds and traffic."},
    {name:"Barry S",rating:1,text:"The traffic was HORRENDOUS from the West Gate to Old Faithful... The Park in its present state cannot handle the volume of vehicles being allowed in."},
  ],
  "yosemite": [
    {name:"SMECM",rating:5,text:"We so enjoyed everything about Yosemite. We visited during firefall season just after a snowstorm. The rangers are really nice and helpful. Don't forget to visit the waterfalls more than once as they're constantly changing."},
    {name:"Toblje",rating:4,text:"Accommodation in the national park is very expensive and below average quality. Cheaper and better alternatives can be found outside, but with a longer journey. Depending on the accommodation you have to expect a drive of one to one and a half hours."},
  ],
  "grand-canyon": [
    {name:"Tianxingzhe",rating:5,text:"Pictures and videos don't do the actual experience justice. Bright Angel Trail and South Kaibab Trail are recommended. The South Rim is a truly amazing place to visit."},
    {name:"HighlandLass24",rating:5,text:"Of course you have to go. It's really something to see. Definitely worth it to see with your own eyes even if you don't get instagram worth photos."},
  ],
  "zion": [
    {name:"Holly C",rating:5,text:"What an absolutely amazing trip. This hike up the Narrows is not to be missed. Highly recommend to rent the water hiking boots, waders and walking stick ($60)."},
    {name:"Sherry T",rating:5,text:"We took the advice and caught the shuttle on a Saturday in August at 7:30 AM — absolutely the way to go! No lines, no need for a park pass that early."},
    {name:"BrakiWorldTraveler",rating:4,text:"Zion NP is another amazing park, however after visiting Bryce the day before, it left a weaker impression on us."},
    {name:"samdogNY",rating:5,text:"Zion is Majestic. We had concerns about going in August due to heat and crowds. As many will tell you - get up and out early."},
  ],
  "glacier": [
    {name:"Ash & Jon (Elevateverything)",rating:5,text:"We have been to many national parks, and this is our favorite! The combination of the view on Going to the Sun Road which all ages can enjoy with the hiking opportunities from easy to challenging is unbeatable!"},
  ],
  "great-smoky": [
    {name:"Sandrita",rating:5,text:"Absolutely breathtaking!! This was my first time visiting a national park and it set a high bar on what to expect for the remaining 62."},
    {name:"Alejandro C",rating:5,text:"We visited Great Smoky Mountains National Park during Thanksgiving 2025 while staying in Gatlinburg, traveling with our two kids (11 and 8), and it was absolutely unforgettable."},
    {name:"Sierra D",rating:4,text:"Beautiful scenery in Great Smoky NP! Although it's disappointing with the latest road closures in the park, we made the best of our day trip and there's lots to see!"},
    {name:"Tammy P",rating:5,text:"What an amazing trip! I'll start with a couple of negatives: first, the road to Cherokee is closed due to a landslide, and second, the trails to Laurel Falls are closed until Fall 2026 for maintenance."},
  ],
  "rocky-mountain": [
    {name:"Jerri L",rating:5,text:"This National Park is absolutely amazing! We entered early and drove in from Grand Lake Entrance. It seemed as though this entrance was less busy which made the traffic flow easier. We stopped at all of the overlooks and had amazing views."},
  ],
  "acadia": [
    {name:"Eileen19",rating:5,text:"This park is so beautiful. I was impressed by the diversity of environments given that this is one of the smallest national parks. There's a sandy beach, rugged and rocky coastlines, cliffs, mountains, forests, marshes, rivers, lakes, and waterfalls."},
    {name:"SeniorTravelerTF",rating:4,text:"As someone who is a fan of national parks it hurts not to be able to rate 5-5, but it is hard to separate the Acadia experience from the city of Bar Harbor (and others). Both are interesting, both are crowded."},
  ],
  "grand-teton": [
    {name:"Edward Q",rating:5,text:"Grand Teton National Park is a spectacular place. Truly an experience that I will remember for the rest of my life."},
    {name:"Eric E",rating:5,text:"I did not expect Grand Teton to hit like it did! The park has views of the Tetons for about 95% of all the roads."},
    {name:"Craig S",rating:5,text:"This park, like Yellowstone, is very busy. Visiting Jenny Lake must be done early or else you will walk an extra mile."},
    {name:"Charles S",rating:5,text:"We saved the best until last...A fantastic journey taking wonderful photographs, one was so good my wife's picture was voted 'Photo of the Year' by our local town's photo club!"},
    {name:"[Parkscollecting.com compiled]",rating:1,text:"There is nothing special about this national park. Nothing that we thought was a Wow factor. A lot of the trails were falling apart and swarming with mosquitos. Except the view of the three Teton peaks, it has no alluring vistas."},
  ],
  "joshua-tree": [
    {name:"Sarah M",rating:5,text:"Joshua Tree National Park is absolutely stunning! I loved exploring spots like Hidden Valley and Keys View – the views were breathtaking. Be sure to download the tour beforehand, as it works offline once you're there."},
    {name:"JoeFRocklin",rating:5,text:"Even on a cloudy and foggy January morning, it was worth visiting. If the weather suits you, there are lots of hikes you can do, from easy to challenging. On hot or inclement days, you can tour the park easily from your car."},
  ],
  "arches": [
    {name:"jbg74",rating:5,text:"Arches National Park is definitely worth a visit. You can see the highlights in a day, but an extra day or two will really allow you to experience the whole park. My favorite arch in the park was Double Arch."},
    {name:"[Parkscollecting.com compiled]",rating:1,text:"This place is worthless. Couple holes in the rocks. Don't see what the big deal is. Both of the arches were not what we expected."},
  ],
  "olympic": [
    {name:"DannyWasserman",rating:5,text:"We were taking in all the national parks in Washington, and Olympic National Park was second on our list after visiting Mount Rainier. This is a beautiful area and should not be missed. We enjoyed the mountains, hiking, waterfalls, and so much more."},
    {name:"[Parkscollecting.com compiled]",rating:1,text:"I don't think this is something too great, just another forest. Pretty much like every other forest except for some hanging moss and bugs. Just don't. Absolutely not worth it. We paid $30 to drive this road only to see absolutely nothing but clouds."},
  ],
  "bryce-canyon": [
    {name:"Kate S",rating:5,text:"This is one of my favorite National Parks because of the splendor of its beauty — the hoodoos, red rocks, pine trees. The Queen's Garden Trail (1-2 hrs depending on how fast you can hike up the switchbacks, unpaved, moderate) is a highlight."},
    {name:"Marshall B",rating:5,text:"It is hard to say enough about how spectacular this park is, particularly when there is still some snow on the ground. We stopped at most of the parking areas to admire the views, so it was about 2 1/2 hours from start to finish."},
    {name:"Kurt H",rating:5,text:"Endlessly fascinating, we never tire of Bryce. This time we were there in January and it definitely requires good winter clothes. The snow adds a nice visual feature for memories and photos."},
    {name:"Daniele_Gorizia",rating:5,text:"For us this is one of the most beautiful parks visited on our western itinerary. Rock formations that the weather has smoothed over millennia, giving them original pointed shapes called 'hoodoos'."},
    {name:"[Parkscollecting.com compiled]",rating:1,text:"This by far is one of the most boring parks to visit. Only come here if you're passing by. The walks are a bit mediocre and not all that scenic. Same hoodoos, slightly different angle."},
  ],
  "death-valley": [
  ],
  "denali": [
    {name:"hms917",rating:5,text:"This was a key highlight of our trip, and we took the green shuttle buses. We saw moose, porcupine, brown bears, a fox, ptarmigans, dall sheep, and lots of caribou. It was an epic few days."},
    {name:"Colleen C",rating:5,text:"We spent a few days in the Denali area, and the park was amazing! We were able to see the peaks of Denali both days. We also learned that we were in the lucky 5% of people who have seen the Denali peaks cloudless, which was spectacular!"},
    {name:"F L Eveline",rating:4,text:"The park is beautiful. The Horseshoe Lake Trail was a highlight, where we saw a moose up close drinking from the lake. Would love to come back one day and go deeper into the park."},
  ],
  "mount-rainier": [
    {name:"Robert B",rating:5,text:"We had a magnificent day in Mount Rainier National Park. At first we were a little concerned that the weather would not cooperate but we ended up enjoying wonderful views of the peak and other parts of the park. We actually drove above the clouds!"},
    {name:"Don J",rating:3,text:"Mt. Rainier is a wonderful place but is now over run with too many people. Like many of our National Parks, Mt. Rainier is being loved to death."},
    {name:"[Parkscollecting.com compiled]",rating:1,text:"It was like a juicy piece of steak presented on a trash can lid. Spending 30 dollars to drive 30 min up a mountain and then almost everything closed. Really is a one trick pony. We couldn't see the mountain from Paradise Point due to heavy fog."},
  ],
  "sequoia": [
    {name:"Adam J",rating:5,text:"Worth going and camping or RVing in the park. We stayed at Lodgepole campground, a very quiet area with lots of deer and various chipmunks. Worth seeing the giant Sequoias."},
    {name:"Miguel Quintanilla",rating:5,text:"It is an excellent park, with many attractions and paths to travel and everything very well signposted. It is difficult to move in your own vehicle inside the park as there are areas where parking is quite limited."},
    {name:"Christian P",rating:5,text:"It was awesome, a must see. Just beware: the road is a bit difficult and must be very aware to drive. Recommend you take shorts and good shoes to walk, a lot."},
  ],
  "everglades": [
    {name:"Tina",rating:5,text:"On the guided tram tour we could see many birds, alligators and turtles. As a small tip, please be sure to use Mosquito Spray. The little bloodsuckers are everywhere."},
    {name:"William B",rating:5,text:"This is my second visit in about 18 years. The sunsets are amazing over Florida Bay. It's a $35.00 entry fee and it's good for a 6 day pass. It's a 38 mile drive from the Homestead entrance to where the road ends at Flamingo."},
  ],
  "shenandoah": [
    {name:"Zeec201457",rating:5,text:"We did the skyline drive and the views are stunning. Make sure to bring food because there's limited places to purchase food in the park. There was a lot to do at the visitor center. We even met Smokey the bear."},
    {name:"Lisa J",rating:5,text:"We have driven through the park 3 times now and I just got my passport book stamped. It's a very beautiful park, with lots of hiking trails and places to pull off and view. If you decide you need gas there is some at the Big Meadows visitor center."},
  ],
  "crater-lake": [
    {name:"George A.",rating:5,text:"An absolutely stunning natural site! I've been to a lot of the US national parks, and this is at the top in terms of sheer beauty."},
    {name:"Our Next Adventure",rating:5,text:"Crater Lake is honestly unreal...The water is a crazy, crystal clear blue that doesn't even look real. Driving the 33 mile Rim Drive gives you insane views."},
    {name:"carlotaTravel4fun",rating:4,text:"The lake is breathtaking...Yes, it was crowded and you couldn't get near the trail down to lake level...The other disappointment was the road closure.\" [MIXED]"},
    {name:"Experience Junkies",rating:5,text:"The views of the lake from every pullout is extraordinary, however they were very crowded. We were very disappointed that the Park didn't have the Park Unigrid."},
    {name:"ConfederateMike",rating:5,text:"The hike down Cleetwood trail is worth the effort...It takes effort to get back to the top. It's a good idea to bring water shoes."},
  ],
  "badlands": [
    {name:"M M",rating:5,text:"Spend several days in the Badlands National Park, and you will create memories to last forever.\" Praised knowledgeable rangers and varied hiking options."},
    {name:"Melabaffi",rating:5,text:"It enchanted me!\" Found the landscape breathtaking with beautiful views and enjoyed spotting eagles at the visitor center."},
    {name:"MikeB1952",rating:4,text:"Appreciated the geology displays and bison sightings but noted the visitor center video was 'poor quality; grey and not very vivid,' impacting the experience.\" [MIXED]"},
    {name:"RetiredTravelerTN",rating:5,text:"Dramatic variety of landscape texture and soil color\" and recommended timing overlook visits by light conditions for optimal views."},
    {name:"Stacy H.",rating:5,text:"Visited in February and enjoyed fewer crowds and stunning snow-covered scenery, though noted a prairie dog plague prevented wildlife viewing that season.\" [MIXED]"},
  ],
  "hawaii-volcanoes": [
    {name:"Ilene",rating:5,text:"We watched the live volcano cams on YouTube carefully and bided our time until Saturday, January 24 — the day that the scientists said that Kīlauea would erupt.\" Witnessed an extraordinary eruption event with fountaining lava."},
    {name:"Heather",rating:5,text:"This is a huge park so make sure you plan in advance to make sure you don't miss anything.\" Notes the visitor center is under construction, recommending advance planning."},
    {name:"Good Names All Gone",rating:4,text:"Our one big disappointment is that when we visited Kilauea was erupting in episodes.\" The reviewer regretted missing active lava fountains by one day, though still appreciated steam vents and volcanic views. [MIXED]"},
    {name:"rbhogaraju",rating:5,text:"The park requires a full day — there is so much to do and see.\" Highlights the dramatic contrast between lush rainforests and stark lava fields, calling it an awe-inspiring experience."},
    {name:"Explorer43768791328",rating:4,text:"Bring plenty of water!\" Mixed experience—enjoyed the unique opportunity to stand inside a volcano but found the descent and ascent moderately challenging. [MIXED]"},
  ],
  "channel-islands-ca": [
    {name:"BruinDan",rating:5,text:"We saw a couple of adorable Island Foxes\" and \"a large pod of playful dolphins\" on the return journey, making it an unforgettable experience."},
    {name:"Christine D.",rating:5,text:"This traveler encountered whales and sharks during crossing and had \"enough time to take a walk and see the small foxes."},
    {name:"Natty Park Traveler",rating:5,text:"Saw the island scrub jay and the island fox\" and expressed regret about not scheduling longer on the island."},
    {name:"Ry Ry",rating:5,text:"Amazing cliff views,\" but notes this \"is not recommended for those that need physical assistance\" due to graveled trails. [MIXED]"},
    {name:"Cohoman",rating:5,text:"I only saw one fox despite park suggestions of abundance,\" and required about three 8-ounce bottles of water during the hike due to limited shade. [MIXED/NEGATIVE]"},
  ],
  "north-cascades-wa": [
    {name:"Bellaire56",rating:5,text:"Loved, loved, loved. The Rainy lake hike ends at the lake with cool stone reflections. So tranquil."},
    {name:"Dana Wilson",rating:5,text:"It was absolutely beautiful, and we had such a great time...The mountains and lakes we came across were like something out of a postcard."},
    {name:"Ron S.",rating:5,text:"This park is very special. No one is there asking for money when you enter...The big plus was lack of crowds."},
    {name:"Samona K.",rating:3,text:"We were really looking forward to the park but are kind of disappointed...there is nothing to do except hiking. The park itself is free of charge, but the accommodation is very expensive.\" [NEGATIVE]"},
    {name:"Aaron Ross",rating:5,text:"The scenery is on another level, and the turquoise water (caused by glacial flour reflecting in the sun) is unlike anything I have ever seen."},
  ],
  "redwood-np-ca": [
    {name:"Great_Beer_Now",rating:5,text:"One of America's great natural wonders...leaves a lasting impression that few other National Parks can match.\" Praised the magnificent trees and recommended taking a short hike."},
    {name:"Kennet",rating:5,text:"It was completely like entering the Hobbit movie...so much peace inside.\" Reviewer felt the experience was transformative and plans to return."},
    {name:"moodblu",rating:5,text:"I would have liked more signage with information about the trees and the forest ecosystem.\" Despite constructive feedback, found the redwoods \"a great new experience\" but noted confusion about park boundaries. [MIXED]"},
    {name:"Sue M.",rating:5,text:"If you only have one day, start at the Thomas Kuchel Visitor Center...just stop at the Big Tree for photo ops.\" Practical advice for time-limited visitors."},
    {name:"Moath Ibrahim",rating:5,text:"This was one of the best trips I've ever taken!...Pictures don't do justice to how massive and awe-inspiring these trees are.\" Appreciated the peaceful atmosphere compared to crowded parks like Yosemite."},
  ],
  "carlsbad-caverns-nm": [
    {name:"Sarah B.",rating:5,text:"We arrived five minutes prior to opening and a line was wrapped around the visitor's center...the 500th ticket was given out at 10:45 am.\" Describes a successful strategy for obtaining same-day timed entry tickets."},
    {name:"njoireading247",rating:5,text:"You could definitely see that they were short-staffed, but the rangers were still polite and helpful.\" Despite noting understaffing, praised the cavern's 1.6-mile paved loop. [MIXED]"},
    {name:"Cheri Davis",rating:5,text:"This so far is the best and biggest Cavern I have ever been in!\" She logged over 10,000 steps and found the $1 timed entry reservation system straightforward."},
    {name:"NatSteveC",rating:5,text:"Never once felt claustrophobic as the caverns were so vast...they should not be missed.\" Overcame initial fears about underground exploration and called it a favorite national park."},
    {name:"Michelle",rating:5,text:"The vastness and views of this NP are unexplainable!\" Praised the King's Palace tour and found the gift shop offered quality souvenirs across multiple price ranges."},
  ],
  "white-sands-nm": [
    {name:"tinaNtravel",rating:5,text:"It feels like you are in another world. It is amazing and beautiful.\" Praised the visitor center and marked hiking trails."},
    {name:"srikanth0435",rating:4,text:"Worth seeing during sunrise or sunset timings. Others timings don't give much good views.\" Noted long entrance lines but recommended purchasing passes online. [MIXED]"},
    {name:"Escape49937438969",rating:5,text:"Legit the coolest place I've ever been, the sand goes for miles.\" Urged others to catch sunset or sunrise views."},
    {name:"Biblublu",rating:5,text:"It's doable but challenging, far from 'flat', but wonderful!\" Italian hiker found the Alkali trail difficult despite its beauty, emphasizing the need for water and sun protection. [MIXED]"},
    {name:"Excursion287061",rating:5,text:"If you're anywhere near this NP make sure to visit!\" Warned about overpriced gift shop merchandise and suggested buying sleds at Walmart instead of renting inside the park. [MIXED]"},
  ],
  "big-bend-tx": [
    {name:"Ian S.",rating:5,text:"Wonderful place. Wild desert fantastic scenery. In April it was far from busy and I was able to drive nice and easy along the well paved roads.\" Advises being careful on unpaved roads unless in a 4x4."},
    {name:"Lydia J.",rating:5,text:"This area provides for some pretty scenic pictures as well as some nice views you can pull off at exhibit points."},
    {name:"minimize940314",rating:5,text:"If you are trying to go to Chisos area at high season, be prepare to enter as early as possible, as traffic control and lack of parking space would soon emerge as problems.\" [MIXED]"},
    {name:"TennisStar602",rating:5,text:"It was gorgeous to look at these aspen trees with cacti in the middle of a desert...colder here than it was at Santa Elena Canyon due to the higher elevation."},
    {name:"RichardIII",rating:2,text:"The open spaces and the vastness just too much\" during their hot summer visit and found it disappointing overall. They felt the scale overwhelmed rather than impressed. [NEGATIVE]"},
  ],
  "mesa-verde-cliff": [
    {name:"Daniele",rating:5,text:"Park less frequented than other more famous in the area...definitely worth visiting.\" Notes the park requires advance booking due to remote location and limited tour slots."},
    {name:"HouTexGal",rating:5,text:"The Cliff Palace tour was a 5/5.\" Cautions that the tour \"requires a lot of physical exertion going up/down steep and primitive stairs and ladders.\" [MIXED]"},
    {name:"George A.",rating:5,text:"Most extensive cliff dwellings I've seen...great vantage points for viewing them.\" Recommends planning at least half a day due to driving between sites."},
    {name:"Stephane",rating:4,text:"Beautiful and very surprising site...nothing just the viewpoint at height justifies the visit.\" Mixed review noting the long, winding drive but acknowledging scenic value. [MIXED]"},
    {name:"RecreationV",rating:4,text:"Huge, with so many areas to explore\" but mentions mild altitude sickness challenges on otherwise easy trails like Soda Canyon Overlook. [MIXED]"},
  ],
  "great-sand-dunes": [
    {name:"Ellen S.",rating:5,text:"Watching my 10yr old grandson enjoy sliding on & playing in the sand was a joy to me.\" Appreciated the family-friendly experience during an ideal August visit."},
    {name:"Michele L.",rating:5,text:"Just sat on a dune for 30-45 minutes taking pictures, running my fingers through the pristine sand\" and found the experience transformative. Recommends visiting in late September."},
    {name:"CocoChanel05",rating:4,text:"It was SO hot in July (about 100 degrees and the sand was 110-120 degrees) so could not go out on the actual sand dunes.\" Extreme summer heat prevented enjoying the main attraction. [NEGATIVE]"},
    {name:"Jeri Jo S.",rating:5,text:"You sink in to the sand with every step\" and the environment is \"VERY windy.\" Despite challenges, praised the unique landscape and recommended ear coverings and bandanas. [MIXED]"},
    {name:"Brendan S.",rating:5,text:"This park offers \"really only one thing...the titular dunes\" but it's magnificent. Most visitors can thoroughly experience it within a few hours unless pursuing intensive hiking."},
  ],
  "mammoth-cave": [
    {name:"Callie S.",rating:5,text:"The experience was great. The view was amazing... Your legs might get tired but it's worth it."},
    {name:"A & M Travels",rating:5,text:"Buy your tickets ahead of time if you are looking for a specific time and tour...there are several options for your skill level."},
    {name:"Cat B.",rating:4,text:"Praised the Historic and Domes & Dripstones tours as \"very good choices,\" but noted the lodging accommodations needed updating, stating \"carpeting, bathroom and doors were all pretty shoddy.\" [MIXED]"},
    {name:"Cheri D.",rating:5,text:"This was on my must visit list for a while and I was not disappointed... Park Rangers are pleasant and most helpful."},
    {name:"Phonia337",rating:5,text:"Did the Domes and Dripstones cave tour and it was excellent!...Cave temperatures are 54 degrees Fahrenheit year-round."},
  ],
  "canyonlands-ut": [
    {name:"Gwen C.",rating:5,text:"Beautiful and well maintained trails for all levels of hiking experience. The payoffs are the incredible arches and forever canyon views."},
    {name:"HennySchaijk",rating:5,text:"Improbably impressive is this national park...beautiful points are often near the road\" for those with limited mobility."},
    {name:"jbg74",rating:5,text:"Mesa Arch in Canyonlands was my favorite arch, even better than the arches in Arches National Park."},
    {name:"slhokie",rating:4,text:"The plane tour showed how immense and varied the landscape is\" though \"the restroom facilities are a hole in the ground with no water.\" [MIXED]"},
    {name:"TripPhotographer52",rating:4,text:"Many canyon formations\" are interesting in the Island in the Sky area, but overall \"it was not as beautiful as anticipated.\" [NEGATIVE]"},
  ],
  "capitol-reef-ut": [
    {name:"Michelle L.",rating:5,text:"So this is one of the lesser visited parks as it's fairly remote as a result parking is very limited at all trailheads."},
    {name:"Jerri L.",rating:5,text:"We spent two nights camping in the park and although it rained much of that time, we were able to enjoy trails, hikes, the orchards, the history."},
    {name:"g8rslp01",rating:5,text:"I have hiked the Mighty Five of Utah, and I have to say that Capitol Reef comes in as a favorite. It was uncrowded and so ruggedly beautiful."},
    {name:"Laurie M.",rating:4,text:"If you plan on hiking during the summer you must hit the rocks by 8 am...The hike starts out very flat then ends with some serious uphill to the arch.\" [MIXED]"},
    {name:"ThomUSA",rating:5,text:"Some of the dirt roads are passable by regular 2WD vehicles...Some trails were not well marked. For example visiting the tanks at the Capitol Gorge.\" [MIXED]"},
  ],
  "wind-cave-sd": [
    {name:"Jerri L.",rating:5,text:"The prairie dogs are always fun to watch and were found along all the hiking trails and roadsides.\" Explored extensively over two days, spotting bison herds, elk, and pronghorn."},
    {name:"Hatzlacha",rating:4,text:"Found the experience somewhat disappointing overall. \"It really should be listed as for children\" regarding the tour guide's presentation level. Preferred the Jewel Cave experience for educational value. [NEGATIVE]"},
    {name:"Godsgirl",rating:5,text:"The cave is well worth touring.\" Praised guide Kaci's expertise and humor, appreciated abundant prairie dogs and bison sightings throughout the park."},
    {name:"MikeB1952",rating:4,text:"Noted that \"most of the tour is small passages\" with few large rooms. While impressed by the cave's length, found formations less interesting compared to other cave experiences. [MIXED]"},
    {name:"Jennifer A.",rating:3,text:"Ground was beautiful but couldn't access cave tours.\" Advises planning ahead: cave reservations required approximately three weeks in advance. [NEGATIVE]"},
  ],
  "hot-springs-np-ar": [
    {name:"njoireading247",rating:5,text:"This is a national park that is free, does not require timed reservations and in the heart of the city...\" Praised the restored bathhouses from the 1930s and the scenic loop drive."},
    {name:"Art and Ginny",rating:4,text:"This is an urban park. Be prepared for a lack of parking, congested streets, loud music...\" Despite congestion challenges, found charm in Bathhouse Row and appreciated the mountain trails. [MIXED]"},
    {name:"bylandorbyair",rating:4,text:"This isn't one of the wondrous, awesome national parks in the US system, but it is historical...\" Worthwhile and appreciated that dogs could access most areas. [MIXED]"},
    {name:"francisc077",rating:3,text:"Felt lukewarm about the experience, stating the town outside Bathhouse Row seemed \"run down and kind of sad\" with excessive noise from cruising vehicles. [NEGATIVE]"},
    {name:"Lynnette27",rating:3,text:"Of the 9 places we visited (8 were the state parks), this was our least favorite.\" Felt disconnected from nature due to urban surroundings and found the hiking experience disrupted by street noise. [NEGATIVE]"},
  ],
  "lassen-volcanic-ca": [
    {name:"Jill H.",rating:5,text:"Did not disappoint. The road is only open to Bumpass Hell trail.\" Appreciated beautiful views despite limited access due to snow closures in June."},
    {name:"djmathews",rating:4,text:"This remote national park in northern California I found extremely unique.\" Mixed review praising the park's geothermal features and wildlife, though noting it deals with both snow and fire issues. [MIXED]"},
    {name:"kevan j.",rating:5,text:"Amazing hike! It's pretty steep but only about 5 miles up and back.\" This 62-year-old hiker called it \"one of my top ten hikes of all time."},
    {name:"John E.",rating:4,text:"The entrance fee is $30. The trails are very informative about the volcanic eruption.\" Positive assessment of educational trails, though noting the entrance cost may deter some visitors. [MIXED]"},
    {name:"SeattleReebs",rating:5,text:"We almost had the place to ourselves...the park itself is breathtaking.\" Enthusiastic review of an underrated destination with pristine road conditions."},
  ],
  "pinnacles-ca": [
    {name:"Our Next Adventure",rating:5,text:"Pinnacles is such an underrated gem! The massive rock spires and jagged peaks are stunning\" with unique talus cave exploration and potential California Condor sightings."},
    {name:"Brendan S.",rating:5,text:"Pinnacles is always ranked near the bottom of the 63 national parks, making my expectations low. But it's well-worthy of the National Park distinction."},
    {name:"LukeS",rating:5,text:"The Condor Gulch-High Peaks-Bear Gulch Cave loop is one of my all time favorite day hikes.\" Best visited during early spring or late fall due to intense summer heat."},
    {name:"FAFNAR",rating:4,text:"The hike to Bear Gulch reservoir was fun, especially climbing around the rocks and up the waterfall\" but questioned whether visiting warrants extra effort unless camping or doing longer hikes. [MIXED]"},
    {name:"luv4phood",rating:5,text:"Completed a rewarding 6-mile loop in approximately 4 hours. The campground lacks privacy and sits directly on the main visitor road, which was noted as a drawback. [MIXED]"},
  ],
  "congaree-np-sc": [
    {name:"Brian E.",rating:5,text:"The Park Service does a magnificent job between the Visitor Center ecosystem and history explanations."},
    {name:"Gina B.",rating:5,text:"This hidden gem in South Carolina far exceeded our expectations. Wildlife was abundant—we spotted owls, snakes, and skinks."},
    {name:"BruinDan",rating:4,text:"You can expect a very humid environment, so plan accordingly.\" Also praised it as \"one of the most unique environments we had ever experienced.\" [MIXED]"},
    {name:"Hannah S.",rating:4,text:"Well maintained national park - super friendly staff and clean! The boardwalk is slippery in spots so take it careful.\" [MIXED]"},
    {name:"It may be a free park but to u",rating:2,text:"It may be a free park but to us that's more than it should be...do the boardwalk trail only, or otherwise don't waste your time.\" Described the mosquitoes as \"awful\" and noted that \"when you stopped walking, you were swarmed.\" [NEGATIVE]"},
  ],
  "dry-tortugas-fl": [
    {name:"Kbenoithake",rating:5,text:"We opted out of the boat and splurged on the all day sea plane excursion...So worth it!\" Praised the scenic seaplane ride and exclusive island time before ferry arrivals."},
    {name:"Barry L.",rating:5,text:"The Fort at the park is very interesting. The rookery is extraordinary.\" Recommended wearing sneakers instead of sandals due to course, shelly beaches."},
    {name:"Fran B.",rating:5,text:"It is a lot of walking so wear comfortable shoes & wear sunscreen there is not much shade.\" Highlighted historical significance and amazing views from Fort Jefferson's top."},
    {name:"hd4me",rating:3,text:"Boat little bumpy with some getting sick...Would probably not go back.\" Complained about rough waters causing seasickness and high costs for limited activities. [NEGATIVE]"},
    {name:"Grover R.",rating:5,text:"American Treasure — Both Historically and Naturally...amazing things to do and see here.\" Detailed guide covering fort history, snorkeling, and bird sanctuaries."},
  ],
  "biscayne-np-fl": [
    {name:"Jodi307",rating:5,text:"Twice a month, the Biscayne Institute offers a 4-hour lighthouse boat tour that departs from Deering Estate.\" Praised seeing multiple lighthouses and dolphins."},
    {name:"Elizabeth C.",rating:5,text:"Our guide, Sienna, was wonderfully kind, helpful and knowledgeable.\" The family enjoyed kayaking through mangrove tunnels on their 2-hour tour experience."},
    {name:"Grover R.",rating:5,text:"Best way to experience Biscayne National Park.\" Highlighted paddling in Jones Lagoon and encountering marine life, though weather prevented the planned snorkeling portion."},
    {name:"Departure31426160252",rating:4,text:"The trip was great!\" However, noted overcrowding: \"The head count was 34 people. The website says under boat information 'It could hold a max of 30 passengers'.\" [MIXED/NEGATIVE]"},
    {name:"J S.",rating:4,text:"Visitor noted the boat was \"fairly packed and the seats faced the inside of the boat, which made seeing the view a little tough,\" though Boca Chita Key was described as phenomenal. [MIXED]"},
  ],
  "indiana-dunes": [
    {name:"DLP",rating:5,text:"Sun, sand and water…what's not to like? Many of the trails are by dunes that lead to beautiful views of Lake Michigan."},
    {name:"Duraiya K.",rating:4,text:"Indiana Dunes National Park is a fantastic spot for a trail adventure, and the Dunes Trail is a real gem."},
    {name:"Deanna A.",rating:3,text:"Worth a trip if you are checking off all national parks. If that's not a goal, you can skip this one...the visitor center was completely unorganized.\" [NEGATIVE]"},
    {name:"Jeff M.",rating:4,text:"Really nice views of Lake Michigan and a great place to relax at the beach when it's nice out. Trails could be kept up a bit better though.\" [MIXED]"},
    {name:"dizzneegirl",rating:4,text:"The water and beach are nice at west beach but surrounded by industry so it felt strange and not like a national park.\" [MIXED]"},
  ],
  "cuyahoga-valley-oh": [
    {name:"rzahm",rating:5,text:"A nice gem between Akron and Cleveland\" with beautiful geography and many accessible trails. Appreciated the frozen and flowing waterfalls."},
    {name:"wirttravelers",rating:4,text:"The Ledges Trail stood out as particularly beautiful with rock formations and shaded paths. Found it less spectacular than other national parks but still worthwhile. [MIXED]"},
    {name:"lithlith",rating:3,text:"Constant noise\" from highways detracts from the natural experience throughout the park. Suggests visiting Hocking Hills instead for superior features and hiking. [NEGATIVE]"},
    {name:"Rosanne S.",rating:3,text:"Found Brandywine Falls beautiful but warns that \"parking was at a premium\" on busy Sundays. Recommends the GuideAlong app for discovering lesser-known waterfalls. [MIXED]"},
    {name:"Gage113",rating:5,text:"Appreciated that \"no park pass\" is needed and enjoyed the Ledges hike. Notes the park is spread out requiring multiple driving stops for different attractions."},
  ],
  "new-river-gorge-wv": [
    {name:"Dane C.",rating:5,text:"For the family there is the New River Gorge Bridge standing unbelievably high above the New river it is a marvel.\" Recommends the Fayette Station Road."},
    {name:"Kathy R.",rating:4,text:"Praised the scenic views and knowledgeable rangers but noted: \"There are many cross-cutting trails, so it is often unclear which one to take to stay on the primary trail.\" [MIXED]"},
    {name:"Suzanne",rating:5,text:"The main overlook is located to the side of the visitor center and it's truly amazing!\" Highlights diverse landscapes and recommends visiting Grandview and Sandstone sections."},
    {name:"Jeanne S.",rating:5,text:"Visited with 17 family members and appreciated \"the natural beauty and lack of commercialization of this area.\" Notes trails were uncrowded."},
    {name:"THINGS2LIVE4",rating:5,text:"Compares the Long Point Trail experience to Zion's Angel's Landing and praises the preserved ghost town of Thurmond, noting \"the bridge walk you have to book way in advance."},
  ],
  "gateway-arch-mo": [
    {name:"arleye",rating:5,text:"Riding the tram to the top is absolutely worth it—but it's not for everyone!\" Notes the pods are tight and claustrophobic, yet describes reaching the summit as a \"once-in-a-lifetime moment."},
    {name:"parksvisitor",rating:5,text:"The arch is very impressive\" and the grounds are excellent. However, felt the museum \"goes a little overboard\" connecting westward expansion history to the arch. [MIXED]"},
    {name:"TravelingSoccerLoon",rating:5,text:"The exterior views of the Arch are more impressive than the views from inside.\" Recommended scheduling a riverboat cruise at sunset for optimal viewing. [MIXED]"},
    {name:"Ashley R.",rating:4,text:"The ride up to the top isn't my favorite, as it's a little claustrophobic.\" Despite this discomfort, noted efficient operations and found the limited time at the summit sufficient. [MIXED]"},
    {name:"jkweebs",rating:4,text:"The arch is an incredible structure\" with fascinating construction history. Yet this national parks collector noted these sites function \"as national monuments, not national parks.\" [MIXED]"},
  ],
  "mount-rushmore-sd": [
    {name:"BrakiWorldTraveler",rating:5,text:"Got there very early, around 8 AM and I strongly suggest that. First, you'll find your parking spot immediately, second more important - there are very few visitors at that time."},
    {name:"Tom",rating:4,text:"Opinions about this attraction are going to be far ranging but since this was a bucket list item since my childhood I'm on the more positive end."},
    {name:"Jill E.",rating:4,text:"The visitor center closure during the government shutdown was disappointing, yet the carving itself remained \"beautiful, with photo opportunities from various angles.\" [MIXED]"},
    {name:"Rick_2785",rating:4,text:"Mount Rushmore is undeniably impressive to see in person—the size, detail, and history of the carving are remarkable. However, there really wasn't much to do beyond simply viewing the monument.\" [MIXED]"},
    {name:"Barry S.",rating:5,text:"Enjoyed \"the film 'Carved in Stone' that's presented in the Visitor Center\" and found it \"very informative and got me thinking differently about the Monument."},
  ],
  "glacier-bay": [
    {name:"theoriginalchrz",rating:5,text:"No photo will do justice to this beautiful National Park.\" Visitors praise the breathtaking landscape and recommend bringing binoculars for wildlife spotting."},
    {name:"46oceangirl",rating:5,text:"Truly amazing if you're on a cruise and you have the opportunity to pick your itinerary Glacier Bay is a must see.\" Enjoyed exceptional weather and witnessed glacier calving."},
    {name:"K B.",rating:4,text:"Despite poor weather conditions, spotted humpback whales, orcas, sea lions, and mountain goats. Notes large cruise ships have limitations for close viewing compared to smaller vessels. [MIXED]"},
    {name:"Emptynester",rating:5,text:"If you have an opportunity to go on a cruise to this area look for one that includes sailing through this park.\" Park rangers provided excellent wildlife commentary throughout."},
    {name:"D H.",rating:2,text:"This trip amounted to an all day boat ride\" with minimal glacier viewing and disappointing wildlife encounters. Found Tracy Arm glacier tours more exciting by comparison. [NEGATIVE]"},
  ],
  "wrangell-st-elias": [
    {name:"Wendy N.",rating:4,text:"Nice visitor center right off the Richardson Hwy\" with informative ranger talks and nearby forest trails offering \"stunning views of the copper river, the valley and the Wrangell mountains."},
    {name:"Nancy T.",rating:5,text:"This is a very remote park but well worth visiting.\" Despite challenging conditions and flat tires on McCarthy Road, the visitor would return."},
    {name:"terrapinproud",rating:3,text:"While acknowledging the park itself is \"SPECTACULAR,\" criticized staff knowledge at exhibits and noted the visitor center's distance from the park's heart, making it feel disconnected. [MIXED/NEGATIVE]"},
    {name:"CrankingChick",rating:4,text:"Praised the facility's attractive buildings and informative exhibits. However, noted \"mosquitoes were very bad here—some of the worst we encountered in Alaska.\" [MIXED]"},
    {name:"Shavy",rating:4,text:"Described it as \"the biggest park we ever been\" with helpful staff and films about park activities, though emphasized the park remains \"relatively inaccessible.\" [MIXED]"},
  ],
  "kenai-fjords-ak": [
    {name:"NorthStar819606",rating:5,text:"The park is amazing! I really enjoyed learning about glaciers and all the wildlife the area supports.\" Appreciated ranger-guided tours and boat trips to Northwestern Glacier."},
    {name:"TFAtravel",rating:5,text:"Most of Kenai Fjords NP is inaccessible wilderness...The areas that are accessible, however, are a must see.\" Highlighted Exit Glacier hike and wildlife sightings including whales, otters, and eagles."},
    {name:"Firefly78",rating:5,text:"I saw the most abundant array of wildlife in this location (much more than Denali).\" Documented sightings of black bears, sea otters, bald eagles, whales, seals, and puffins."},
    {name:"Violeta M.",rating:5,text:"Simply awesome, beautiful. Must see, carry bear spray. Lots of trails, stunning views.\" Recommended budget-friendly free trails alongside popular Exit Glacier."},
    {name:"Guide37396532207",rating:1,text:"After driving to Seward and booking a hotel room they canceled the trip...with less than a 24hrs notice.\" Expressed frustration over tour cancellation affecting their plans. [NEGATIVE]"},
  ],
  "isle-royale-mi": [
    {name:"Sue F.",rating:5,text:"We stayed at the Rock Harbor Lodge and enjoyed our room with its view of the water and the peace and quiet."},
    {name:"THINGS2LIVE4",rating:5,text:"I would LOVE to come back and spend a couple of nights here. If you want a wild, unique, and awesome place with no tv and limited Wi-Fi Isle Royale is for you!"},
    {name:"Raintree_Thailand",rating:4,text:"Isle Royale is the least-visited national park in the 48 contiguous states...it's costly to get to — $160 round trip per person.\" Praises the destination but highlights expense and accessibility challenges. [MIXED]"},
    {name:"midwesterner5",rating:3,text:"Not blown away by the National Park Service on this visit\" — Critical of unfriendly ranger attitudes and high lodge costs (2.5x more than comparable state park accommodations), though acknowledges good nature experiences. [NEGATIVE]"},
    {name:"Toby M.",rating:5,text:"Special place that sneaks up on you.\" Enthusiastically recommends the seaplane option, warns about Lake Superior waves, and highlights that lodge stays include canoe rentals and stunning Tobin Harbor views."},
  ],
};
